// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dap$0 from "../../ide/dap/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as run$0 from "../../ide/run/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";

/**
 * ArchBody è il tipo del corpo di una richiesta o risposta; Ref punta a uno schema del report.
 */
export class ArchBody {
    "type": string;
    "ref"?: string;
    "array"?: boolean;

    /** Creates a new ArchBody instance. */
    constructor($$source: Partial<ArchBody> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchBody instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchBody {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchBody($$parsedSource as Partial<ArchBody>);
    }
}

export class ArchContextCall {
    "from": string;
    "to": string;
    "origin": string;
    "timeout"?: boolean;
    "site": ArchSite;

    /** Creates a new ArchContextCall instance. */
    constructor($$source: Partial<ArchContextCall> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchContextCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchContextCall {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField4_0($$parsedSource["site"]);
        }
        return new ArchContextCall($$parsedSource as Partial<ArchContextCall>);
    }
}

/**
 * ArchEdge collega due nodi (package o funzioni) con un peso.
 */
export class ArchEdge {
    "from": string;
    "to": string;
    "count": number;

    /** Creates a new ArchEdge instance. */
    constructor($$source: Partial<ArchEdge> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchEdge($$parsedSource as Partial<ArchEdge>);
    }
}

/**
 * ArchEntry è un punto d'ingresso o un servizio rilevato nel codice.
 * Kind: main, init, http, middleware, grpc, kafka-producer, kafka-consumer, repository, job, cli.
 */
export class ArchEntry {
    "kind": string;
    "name": string;
    "detail"?: string;
    "package": string;
    "function"?: string;
    "topics"?: string[];

    /**
     * Solo Kafka: consumer group, formato dei messaggi e topic di retry/dead-letter riconosciuti dal nome.
     */
    "group"?: string;
    "serializer"?: string;
    "topicRoles"?: { [_ in string]?: string };
    "site": ArchSite;

    /**
     * Solo per le route HTTP: handler, middleware e corpi di richiesta e risposta riconosciuti.
     */
    "handler"?: string;
    "handlerSite"?: ArchSite | null;
    "middleware"?: string[];
    "request"?: ArchBody | null;
    "response"?: ArchBody | null;

    /** Creates a new ArchEntry instance. */
    constructor($$source: Partial<ArchEntry> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchEntry {
        const $$createField5_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType0;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType5;
        const $$createField14_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topics" in $$parsedSource) {
            $$parsedSource["topics"] = $$createField5_0($$parsedSource["topics"]);
        }
        if ("topicRoles" in $$parsedSource) {
            $$parsedSource["topicRoles"] = $$createField8_0($$parsedSource["topicRoles"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField9_0($$parsedSource["site"]);
        }
        if ("handlerSite" in $$parsedSource) {
            $$parsedSource["handlerSite"] = $$createField11_0($$parsedSource["handlerSite"]);
        }
        if ("middleware" in $$parsedSource) {
            $$parsedSource["middleware"] = $$createField12_0($$parsedSource["middleware"]);
        }
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField13_0($$parsedSource["request"]);
        }
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField14_0($$parsedSource["response"]);
        }
        return new ArchEntry($$parsedSource as Partial<ArchEntry>);
    }
}

export class ArchField {
    "name": string;
    "goName": string;

    /**
     * string, integer, number, boolean, array, object
     */
    "type": string;
    "format"?: string;
    "ref"?: string;

    /**
     * tipo degli elementi di un array
     */
    "items"?: string;
    "required"?: boolean;

    /** Creates a new ArchField instance. */
    constructor($$source: Partial<ArchField> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("goName" in $$source)) {
            this["goName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchField instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchField {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchField($$parsedSource as Partial<ArchField>);
    }
}

export class ArchFunction {
    "id": string;
    "name": string;
    "package": string;
    "abstract"?: boolean;

    /**
     * riceve un context.Context
     */
    "context"?: boolean;
    "site": ArchSite;

    /** Creates a new ArchFunction instance. */
    constructor($$source: Partial<ArchFunction> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchFunction instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchFunction {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField5_0($$parsedSource["site"]);
        }
        return new ArchFunction($$parsedSource as Partial<ArchFunction>);
    }
}

export class ArchHint {
    "kind": string;
    "message": string;

    /** Creates a new ArchHint instance. */
    constructor($$source: Partial<ArchHint> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchHint instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchHint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchHint($$parsedSource as Partial<ArchHint>);
    }
}

export class ArchImplementation {
    "type": string;
    "package": string;
    "pointer": boolean;
    "test"?: boolean;
    "site": ArchSite;

    /** Creates a new ArchImplementation instance. */
    constructor($$source: Partial<ArchImplementation> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("pointer" in $$source)) {
            this["pointer"] = false;
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchImplementation instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchImplementation {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField4_0($$parsedSource["site"]);
        }
        return new ArchImplementation($$parsedSource as Partial<ArchImplementation>);
    }
}

export class ArchInterface {
    "name": string;
    "package": string;
    "site": ArchSite;
    "methods": string[];
    "embeds": string[];
    "implementations": ArchImplementation[];
    "users": ArchRef[];
    "userCount": number;
    "methodUses": ArchMethodUse[];
    "nearMisses": ArchNearMiss[];
    "hints": ArchHint[];

    /** Creates a new ArchInterface instance. */
    constructor($$source: Partial<ArchInterface> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }
        if (!("methods" in $$source)) {
            this["methods"] = [];
        }
        if (!("embeds" in $$source)) {
            this["embeds"] = [];
        }
        if (!("implementations" in $$source)) {
            this["implementations"] = [];
        }
        if (!("users" in $$source)) {
            this["users"] = [];
        }
        if (!("userCount" in $$source)) {
            this["userCount"] = 0;
        }
        if (!("methodUses" in $$source)) {
            this["methodUses"] = [];
        }
        if (!("nearMisses" in $$source)) {
            this["nearMisses"] = [];
        }
        if (!("hints" in $$source)) {
            this["hints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchInterface instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchInterface {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType7;
        const $$createField6_0 = $$createType9;
        const $$createField8_0 = $$createType11;
        const $$createField9_0 = $$createType13;
        const $$createField10_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField2_0($$parsedSource["site"]);
        }
        if ("methods" in $$parsedSource) {
            $$parsedSource["methods"] = $$createField3_0($$parsedSource["methods"]);
        }
        if ("embeds" in $$parsedSource) {
            $$parsedSource["embeds"] = $$createField4_0($$parsedSource["embeds"]);
        }
        if ("implementations" in $$parsedSource) {
            $$parsedSource["implementations"] = $$createField5_0($$parsedSource["implementations"]);
        }
        if ("users" in $$parsedSource) {
            $$parsedSource["users"] = $$createField6_0($$parsedSource["users"]);
        }
        if ("methodUses" in $$parsedSource) {
            $$parsedSource["methodUses"] = $$createField8_0($$parsedSource["methodUses"]);
        }
        if ("nearMisses" in $$parsedSource) {
            $$parsedSource["nearMisses"] = $$createField9_0($$parsedSource["nearMisses"]);
        }
        if ("hints" in $$parsedSource) {
            $$parsedSource["hints"] = $$createField10_0($$parsedSource["hints"]);
        }
        return new ArchInterface($$parsedSource as Partial<ArchInterface>);
    }
}

export class ArchMethodUse {
    "name": string;
    "calls": number;

    /** Creates a new ArchMethodUse instance. */
    constructor($$source: Partial<ArchMethodUse> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("calls" in $$source)) {
            this["calls"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchMethodUse instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchMethodUse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchMethodUse($$parsedSource as Partial<ArchMethodUse>);
    }
}

export class ArchModule {
    "path": string;
    "requires": string[];
    "external": string[];
    "site": ArchSite;

    /** Creates a new ArchModule instance. */
    constructor($$source: Partial<ArchModule> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("requires" in $$source)) {
            this["requires"] = [];
        }
        if (!("external" in $$source)) {
            this["external"] = [];
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchModule instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchModule {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("requires" in $$parsedSource) {
            $$parsedSource["requires"] = $$createField1_0($$parsedSource["requires"]);
        }
        if ("external" in $$parsedSource) {
            $$parsedSource["external"] = $$createField2_0($$parsedSource["external"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        return new ArchModule($$parsedSource as Partial<ArchModule>);
    }
}

/**
 * ArchNearMiss è un tipo a cui mancano pochi metodi per implementare l'interfaccia.
 */
export class ArchNearMiss {
    "type": string;
    "package": string;
    "missing": string[];
    "site": ArchSite;

    /** Creates a new ArchNearMiss instance. */
    constructor($$source: Partial<ArchNearMiss> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("missing" in $$source)) {
            this["missing"] = [];
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchNearMiss instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchNearMiss {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("missing" in $$parsedSource) {
            $$parsedSource["missing"] = $$createField2_0($$parsedSource["missing"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        return new ArchNearMiss($$parsedSource as Partial<ArchNearMiss>);
    }
}

export class ArchPackage {
    "path": string;
    "name": string;
    "module"?: string;
    "files": number;
    "site": ArchSite;
    "external": string[];
    "std": number;

    /** Creates a new ArchPackage instance. */
    constructor($$source: Partial<ArchPackage> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }
        if (!("external" in $$source)) {
            this["external"] = [];
        }
        if (!("std" in $$source)) {
            this["std"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchPackage instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchPackage {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField4_0($$parsedSource["site"]);
        }
        if ("external" in $$parsedSource) {
            $$parsedSource["external"] = $$createField5_0($$parsedSource["external"]);
        }
        return new ArchPackage($$parsedSource as Partial<ArchPackage>);
    }
}

/**
 * ArchQuery è un accesso al database trovato nel codice.
 */
export class ArchQuery {
    "library": string;

    /**
     * query, exec, prepare, begin, orm
     */
    "operation": string;
    "method": string;
    "sql"?: string;

    /**
     * SQL costruito a runtime (Sprintf, concatenazioni)
     */
    "dynamic"?: boolean;
    "tables": string[];

    /**
     * GORM: tipo del modello
     */
    "model"?: string;

    /**
     * tabella dedotta dalla convenzione di GORM
     */
    "tableGuess"?: boolean;
    "function": string;
    "package": string;
    "transaction"?: boolean;
    "prepared"?: boolean;
    "site": ArchSite;

    /** Creates a new ArchQuery instance. */
    constructor($$source: Partial<ArchQuery> = {}) {
        if (!("library" in $$source)) {
            this["library"] = "";
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("function" in $$source)) {
            this["function"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchQuery {
        const $$createField5_0 = $$createType1;
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField5_0($$parsedSource["tables"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField12_0($$parsedSource["site"]);
        }
        return new ArchQuery($$parsedSource as Partial<ArchQuery>);
    }
}

export class ArchRef {
    "kind": string;
    "function"?: string;
    "package": string;
    "site": ArchSite;

    /** Creates a new ArchRef instance. */
    constructor($$source: Partial<ArchRef> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchRef {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        return new ArchRef($$parsedSource as Partial<ArchRef>);
    }
}

/**
 * ArchSchema è uno struct usato come DTO, con i campi come li vede JSON.
 */
export class ArchSchema {
    "name": string;
    "package": string;
    "fields": ArchField[];
    "site": ArchSite;

    /** Creates a new ArchSchema instance. */
    constructor($$source: Partial<ArchSchema> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchSchema {
        const $$createField2_0 = $$createType17;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        return new ArchSchema($$parsedSource as Partial<ArchSchema>);
    }
}

/**
 * ArchSite è una posizione nel sorgente: Path e Offset dall'analisi, poi Resolve la traduce in
 * percorso relativo al progetto, riga e colonna dell'editor.
 */
export class ArchSite {
    "relativePath": string;
    "line": number;
    "column": number;

    /** Creates a new ArchSite instance. */
    constructor($$source: Partial<ArchSite> = {}) {
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchSite instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchSite {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchSite($$parsedSource as Partial<ArchSite>);
    }
}

export class ArchitectureReport {
    "packages": ArchPackage[];
    "imports": ArchEdge[];
    "packageCalls": ArchEdge[];
    "functions": ArchFunction[];
    "calls": ArchEdge[];
    "modules": ArchModule[];
    "interfaces": ArchInterface[];
    "entries": ArchEntry[];
    "schemas": ArchSchema[];
    "queries": ArchQuery[];
    "contextCalls": ArchContextCall[];
    "truncated"?: boolean;

    /** Creates a new ArchitectureReport instance. */
    constructor($$source: Partial<ArchitectureReport> = {}) {
        if (!("packages" in $$source)) {
            this["packages"] = [];
        }
        if (!("imports" in $$source)) {
            this["imports"] = [];
        }
        if (!("packageCalls" in $$source)) {
            this["packageCalls"] = [];
        }
        if (!("functions" in $$source)) {
            this["functions"] = [];
        }
        if (!("calls" in $$source)) {
            this["calls"] = [];
        }
        if (!("modules" in $$source)) {
            this["modules"] = [];
        }
        if (!("interfaces" in $$source)) {
            this["interfaces"] = [];
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("schemas" in $$source)) {
            this["schemas"] = [];
        }
        if (!("queries" in $$source)) {
            this["queries"] = [];
        }
        if (!("contextCalls" in $$source)) {
            this["contextCalls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchitectureReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchitectureReport {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType21;
        const $$createField2_0 = $$createType21;
        const $$createField3_0 = $$createType23;
        const $$createField4_0 = $$createType21;
        const $$createField5_0 = $$createType25;
        const $$createField6_0 = $$createType27;
        const $$createField7_0 = $$createType29;
        const $$createField8_0 = $$createType31;
        const $$createField9_0 = $$createType33;
        const $$createField10_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("packages" in $$parsedSource) {
            $$parsedSource["packages"] = $$createField0_0($$parsedSource["packages"]);
        }
        if ("imports" in $$parsedSource) {
            $$parsedSource["imports"] = $$createField1_0($$parsedSource["imports"]);
        }
        if ("packageCalls" in $$parsedSource) {
            $$parsedSource["packageCalls"] = $$createField2_0($$parsedSource["packageCalls"]);
        }
        if ("functions" in $$parsedSource) {
            $$parsedSource["functions"] = $$createField3_0($$parsedSource["functions"]);
        }
        if ("calls" in $$parsedSource) {
            $$parsedSource["calls"] = $$createField4_0($$parsedSource["calls"]);
        }
        if ("modules" in $$parsedSource) {
            $$parsedSource["modules"] = $$createField5_0($$parsedSource["modules"]);
        }
        if ("interfaces" in $$parsedSource) {
            $$parsedSource["interfaces"] = $$createField6_0($$parsedSource["interfaces"]);
        }
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField7_0($$parsedSource["entries"]);
        }
        if ("schemas" in $$parsedSource) {
            $$parsedSource["schemas"] = $$createField8_0($$parsedSource["schemas"]);
        }
        if ("queries" in $$parsedSource) {
            $$parsedSource["queries"] = $$createField9_0($$parsedSource["queries"]);
        }
        if ("contextCalls" in $$parsedSource) {
            $$parsedSource["contextCalls"] = $$createField10_0($$parsedSource["contextCalls"]);
        }
        return new ArchitectureReport($$parsedSource as Partial<ArchitectureReport>);
    }
}

export const DebugFrame = dap$0.DebugFrame;
export type DebugFrame = dap$0.DebugFrame;

/**
 * DebugMemory è un blocco di memoria del processo in pausa.
 */
export class DebugMemory {
    "address": string;
    "bytes": number[];

    /**
     * Error spiega perché la lettura si è fermata prima di length byte (memoria non leggibile).
     */
    "error"?: string;

    /** Creates a new DebugMemory instance. */
    constructor($$source: Partial<DebugMemory> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugMemory instance from a string or object.
     */
    static createFrom($$source: any = {}): DebugMemory {
        const $$createField1_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bytes" in $$parsedSource) {
            $$parsedSource["bytes"] = $$createField1_0($$parsedSource["bytes"]);
        }
        return new DebugMemory($$parsedSource as Partial<DebugMemory>);
    }
}

export class DebugRequest {
    "sessionId": dap$0.SessionID;

    /**
     * Mode è "debug" (programma), "test", "attach" (processo locale) o "remote" (dlv --headless già avviato).
     */
    "mode": string;

    /**
     * ProcessID è il processo a cui agganciarsi in modalità attach.
     */
    "processId"?: number;

    /**
     * Address è host:porta del server Delve in modalità remote.
     */
    "address"?: string;

    /**
     * WorkingDirectory è la cartella del modulo relativa al progetto.
     */
    "workingDirectory": string;

    /**
     * Target è il package relativo al modulo, es. "." o "./cmd/api".
     */
    "target": string;
    "testName"?: string;
    "programArguments"?: string[];
    "buildTags"?: string[];
    "environment"?: { [_ in string]?: string };

    /**
     * EnvFile e BuildFlags arrivano dalla configurazione Run attiva.
     */
    "envFile"?: string;
    "buildFlags"?: string[];

    /** Creates a new DebugRequest instance. */
    constructor($$source: Partial<DebugRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DebugRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DebugRequest {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType2;
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("programArguments" in $$parsedSource) {
            $$parsedSource["programArguments"] = $$createField7_0($$parsedSource["programArguments"]);
        }
        if ("buildTags" in $$parsedSource) {
            $$parsedSource["buildTags"] = $$createField8_0($$parsedSource["buildTags"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField9_0($$parsedSource["environment"]);
        }
        if ("buildFlags" in $$parsedSource) {
            $$parsedSource["buildFlags"] = $$createField11_0($$parsedSource["buildFlags"]);
        }
        return new DebugRequest($$parsedSource as Partial<DebugRequest>);
    }
}

/**
 * DelveInfo descrive il binario dlv trovato per la sessione.
 */
export class DelveInfo {
    "available": boolean;
    "binary"?: string;
    "version"?: string;
    "source"?: string;
    "error"?: string;

    /** Creates a new DelveInfo instance. */
    constructor($$source: Partial<DelveInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DelveInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DelveInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DelveInfo($$parsedSource as Partial<DelveInfo>);
    }
}

export class DocFunc {
    "name": string;
    "recv"?: string;
    "doc": string;
    "decl": string;
    "site": ArchSite;

    /** Creates a new DocFunc instance. */
    constructor($$source: Partial<DocFunc> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("doc" in $$source)) {
            this["doc"] = "";
        }
        if (!("decl" in $$source)) {
            this["decl"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocFunc instance from a string or object.
     */
    static createFrom($$source: any = {}): DocFunc {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField4_0($$parsedSource["site"]);
        }
        return new DocFunc($$parsedSource as Partial<DocFunc>);
    }
}

/**
 * DocProblem è un simbolo esportato senza documentazione o con un commento che non inizia col nome.
 */
export class DocProblem {
    "kind": string;
    "name": string;
    "problem": string;
    "site": ArchSite;
    "fix"?: ErrorFix | null;

    /** Creates a new DocProblem instance. */
    constructor($$source: Partial<DocProblem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("problem" in $$source)) {
            this["problem"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocProblem instance from a string or object.
     */
    static createFrom($$source: any = {}): DocProblem {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        if ("fix" in $$parsedSource) {
            $$parsedSource["fix"] = $$createField4_0($$parsedSource["fix"]);
        }
        return new DocProblem($$parsedSource as Partial<DocProblem>);
    }
}

export class DocType {
    "name": string;
    "doc": string;
    "decl": string;
    "site": ArchSite;
    "consts": DocValue[];
    "vars": DocValue[];
    "funcs": DocFunc[];
    "methods": DocFunc[];

    /** Creates a new DocType instance. */
    constructor($$source: Partial<DocType> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("doc" in $$source)) {
            this["doc"] = "";
        }
        if (!("decl" in $$source)) {
            this["decl"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }
        if (!("consts" in $$source)) {
            this["consts"] = [];
        }
        if (!("vars" in $$source)) {
            this["vars"] = [];
        }
        if (!("funcs" in $$source)) {
            this["funcs"] = [];
        }
        if (!("methods" in $$source)) {
            this["methods"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocType instance from a string or object.
     */
    static createFrom($$source: any = {}): DocType {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType40;
        const $$createField5_0 = $$createType40;
        const $$createField6_0 = $$createType42;
        const $$createField7_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        if ("consts" in $$parsedSource) {
            $$parsedSource["consts"] = $$createField4_0($$parsedSource["consts"]);
        }
        if ("vars" in $$parsedSource) {
            $$parsedSource["vars"] = $$createField5_0($$parsedSource["vars"]);
        }
        if ("funcs" in $$parsedSource) {
            $$parsedSource["funcs"] = $$createField6_0($$parsedSource["funcs"]);
        }
        if ("methods" in $$parsedSource) {
            $$parsedSource["methods"] = $$createField7_0($$parsedSource["methods"]);
        }
        return new DocType($$parsedSource as Partial<DocType>);
    }
}

export class DocValue {
    "names": string[];
    "doc": string;
    "decl": string;
    "site": ArchSite;

    /** Creates a new DocValue instance. */
    constructor($$source: Partial<DocValue> = {}) {
        if (!("names" in $$source)) {
            this["names"] = [];
        }
        if (!("doc" in $$source)) {
            this["doc"] = "";
        }
        if (!("decl" in $$source)) {
            this["decl"] = "";
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocValue instance from a string or object.
     */
    static createFrom($$source: any = {}): DocValue {
        const $$createField0_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField0_0($$parsedSource["names"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        return new DocValue($$parsedSource as Partial<DocValue>);
    }
}

/**
 * ErrorEdit sostituisce [Offset, End) con Text; Original è il testo atteso, per non applicare fix obsoleti.
 */
export class ErrorEdit {
    "offset": number;
    "end": number;
    "original": string;
    "text": string;

    /** Creates a new ErrorEdit instance. */
    constructor($$source: Partial<ErrorEdit> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("original" in $$source)) {
            this["original"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): ErrorEdit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ErrorEdit($$parsedSource as Partial<ErrorEdit>);
    }
}

/**
 * ErrorFix è una correzione applicabile con un clic (tutti gli edit sullo stesso file).
 */
export class ErrorFix {
    "label": string;
    "edits": ErrorEdit[];

    /** Creates a new ErrorFix instance. */
    constructor($$source: Partial<ErrorFix> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("edits" in $$source)) {
            this["edits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorFix instance from a string or object.
     */
    static createFrom($$source: any = {}): ErrorFix {
        const $$createField1_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edits" in $$parsedSource) {
            $$parsedSource["edits"] = $$createField1_0($$parsedSource["edits"]);
        }
        return new ErrorFix($$parsedSource as Partial<ErrorFix>);
    }
}

/**
 * FuzzValue è un argomento di un input del corpus: il tipo e il letterale Go così come scritti da go test.
 */
export class FuzzValue {
    "type": string;
    "literal": string;

    /**
     * Expression è la riga originale, già un'espressione Go valida da usare in f.Add(...).
     */
    "expression": string;

    /** Creates a new FuzzValue instance. */
    constructor($$source: Partial<FuzzValue> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("literal" in $$source)) {
            this["literal"] = "";
        }
        if (!("expression" in $$source)) {
            this["expression"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FuzzValue instance from a string or object.
     */
    static createFrom($$source: any = {}): FuzzValue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FuzzValue($$parsedSource as Partial<FuzzValue>);
    }
}

/**
 * GoplsInfo descrive il gopls trovato per una sessione.
 */
export class GoplsInfo {
    "available": boolean;
    "binary"?: string;
    "version"?: string;
    "source"?: string;
    "managedDir"?: string;
    "error"?: string;

    /** Creates a new GoplsInfo instance. */
    constructor($$source: Partial<GoplsInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoplsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GoplsInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoplsInfo($$parsedSource as Partial<GoplsInfo>);
    }
}

/**
 * GoplsSettings sono le preferenze dell'utente tradotte nella configurazione di gopls.
 */
export class GoplsSettings {
    "gofumpt": boolean;
    "staticcheck": boolean;
    "placeholders": boolean;
    "semanticLinks": boolean;

    /**
     * Vulncheck attiva la diagnostica delle vulnerabilità note sulle dipendenze (govulncheck
     * dentro gopls). Scarica il database da vuln.go.dev: per questo è opt-in.
     */
    "vulncheck": boolean;

    /** Creates a new GoplsSettings instance. */
    constructor($$source: Partial<GoplsSettings> = {}) {
        if (!("gofumpt" in $$source)) {
            this["gofumpt"] = false;
        }
        if (!("staticcheck" in $$source)) {
            this["staticcheck"] = false;
        }
        if (!("placeholders" in $$source)) {
            this["placeholders"] = false;
        }
        if (!("semanticLinks" in $$source)) {
            this["semanticLinks"] = false;
        }
        if (!("vulncheck" in $$source)) {
            this["vulncheck"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoplsSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GoplsSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoplsSettings($$parsedSource as Partial<GoplsSettings>);
    }
}

/**
 * GoroutineCreation è l'istruzione `go` che ha creato una goroutine e la goroutine che l'ha eseguita.
 */
export class GoroutineCreation {
    /**
     * Location è la riga dell'istruzione go; nil per le goroutine create dal runtime (es. main).
     */
    "location"?: DebugFrame | null;

    /**
     * SourceLine è il testo di Location.
     */
    "sourceLine"?: string;

    /**
     * ParentID è la goroutine che ha eseguito l'istruzione go (Go 1.21+); 0 se non nota.
     */
    "parentId"?: number;

    /** Creates a new GoroutineCreation instance. */
    constructor($$source: Partial<GoroutineCreation> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoroutineCreation instance from a string or object.
     */
    static createFrom($$source: any = {}): GoroutineCreation {
        const $$createField0_0 = $$createType46;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("location" in $$parsedSource) {
            $$parsedSource["location"] = $$createField0_0($$parsedSource["location"]);
        }
        return new GoroutineCreation($$parsedSource as Partial<GoroutineCreation>);
    }
}

/**
 * GoroutineOverview è l'istantanea di tutte le goroutine alla pausa corrente.
 */
export class GoroutineOverview {
    "goroutines": GoroutineSummary[];

    /**
     * Truncated indica che le goroutine erano più di maxGoroutineOverview.
     */
    "truncated"?: boolean;

    /** Creates a new GoroutineOverview instance. */
    constructor($$source: Partial<GoroutineOverview> = {}) {
        if (!("goroutines" in $$source)) {
            this["goroutines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoroutineOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): GoroutineOverview {
        const $$createField0_0 = $$createType48;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("goroutines" in $$parsedSource) {
            $$parsedSource["goroutines"] = $$createField0_0($$parsedSource["goroutines"]);
        }
        return new GoroutineOverview($$parsedSource as Partial<GoroutineOverview>);
    }
}

/**
 * GoroutineSummary è una goroutine vista dall'IDE: stato, causa del blocco, dove si trova e dove è partita.
 */
export class GoroutineSummary {
    "id": number;
    "name": string;
    "current": boolean;
    "state": string;

    /**
     * BlockedOn è l'espressione su cui la goroutine aspetta (es. "s.orderChannel"), letta dalla riga di codice.
     */
    "blockedOn"?: string;

    /**
     * Location è il frame di progetto più in alto: la riga che l'utente riconosce.
     */
    "location"?: DebugFrame | null;

    /**
     * SourceLine è il testo di Location, per mostrare "84 │ order := <-s.orderChannel".
     */
    "sourceLine"?: string;

    /**
     * Origin è il frame di progetto più in basso: la funzione avviata dall'istruzione go.
     */
    "origin"?: DebugFrame | null;
    "frames": DebugFrame[];

    /** Creates a new GoroutineSummary instance. */
    constructor($$source: Partial<GoroutineSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("frames" in $$source)) {
            this["frames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoroutineSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): GoroutineSummary {
        const $$createField5_0 = $$createType46;
        const $$createField7_0 = $$createType46;
        const $$createField8_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("location" in $$parsedSource) {
            $$parsedSource["location"] = $$createField5_0($$parsedSource["location"]);
        }
        if ("origin" in $$parsedSource) {
            $$parsedSource["origin"] = $$createField7_0($$parsedSource["origin"]);
        }
        if ("frames" in $$parsedSource) {
            $$parsedSource["frames"] = $$createField8_0($$parsedSource["frames"]);
        }
        return new GoroutineSummary($$parsedSource as Partial<GoroutineSummary>);
    }
}

export class InstallToolchainRequest {
    "sessionId": string;
    "version": string;
    "confirmed": boolean;
    "activate": boolean;

    /** Creates a new InstallToolchainRequest instance. */
    constructor($$source: Partial<InstallToolchainRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("confirmed" in $$source)) {
            this["confirmed"] = false;
        }
        if (!("activate" in $$source)) {
            this["activate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallToolchainRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallToolchainRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallToolchainRequest($$parsedSource as Partial<InstallToolchainRequest>);
    }
}

export class InstalledToolchain {
    "version": string;
    "goBinary": string;

    /** Creates a new InstalledToolchain instance. */
    constructor($$source: Partial<InstalledToolchain> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("goBinary" in $$source)) {
            this["goBinary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledToolchain instance from a string or object.
     */
    static createFrom($$source: any = {}): InstalledToolchain {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstalledToolchain($$parsedSource as Partial<InstalledToolchain>);
    }
}

export class PackageDoc {
    "importPath": string;
    "name": string;
    "dir": string;
    "synopsis": string;
    "doc": string;
    "consts": DocValue[];
    "vars": DocValue[];
    "funcs": DocFunc[];
    "types": DocType[];
    "notes": { [_ in string]?: string[] };
    "problems": DocProblem[];
    "site": ArchSite;

    /** Creates a new PackageDoc instance. */
    constructor($$source: Partial<PackageDoc> = {}) {
        if (!("importPath" in $$source)) {
            this["importPath"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("synopsis" in $$source)) {
            this["synopsis"] = "";
        }
        if (!("doc" in $$source)) {
            this["doc"] = "";
        }
        if (!("consts" in $$source)) {
            this["consts"] = [];
        }
        if (!("vars" in $$source)) {
            this["vars"] = [];
        }
        if (!("funcs" in $$source)) {
            this["funcs"] = [];
        }
        if (!("types" in $$source)) {
            this["types"] = [];
        }
        if (!("notes" in $$source)) {
            this["notes"] = {};
        }
        if (!("problems" in $$source)) {
            this["problems"] = [];
        }
        if (!("site" in $$source)) {
            this["site"] = (new ArchSite());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageDoc instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageDoc {
        const $$createField5_0 = $$createType40;
        const $$createField6_0 = $$createType40;
        const $$createField7_0 = $$createType42;
        const $$createField8_0 = $$createType51;
        const $$createField9_0 = $$createType52;
        const $$createField10_0 = $$createType54;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("consts" in $$parsedSource) {
            $$parsedSource["consts"] = $$createField5_0($$parsedSource["consts"]);
        }
        if ("vars" in $$parsedSource) {
            $$parsedSource["vars"] = $$createField6_0($$parsedSource["vars"]);
        }
        if ("funcs" in $$parsedSource) {
            $$parsedSource["funcs"] = $$createField7_0($$parsedSource["funcs"]);
        }
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField8_0($$parsedSource["types"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField9_0($$parsedSource["notes"]);
        }
        if ("problems" in $$parsedSource) {
            $$parsedSource["problems"] = $$createField10_0($$parsedSource["problems"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField11_0($$parsedSource["site"]);
        }
        return new PackageDoc($$parsedSource as Partial<PackageDoc>);
    }
}

/**
 * PendingDefer è un defer registrato a runtime e non ancora eseguito.
 */
export class PendingDefer {
    /**
     * Order è la posizione di esecuzione: 1 parte per primo al ritorno o durante un panic.
     */
    "order": number;

    /**
     * Location è la riga dell'istruzione defer; Location.Name è la funzione che l'ha registrato.
     */
    "location"?: DebugFrame | null;
    "sourceLine"?: string;

    /**
     * Wrapper è la funzione che il runtime chiamerà (per Go ≥ 1.18 un wrapper come main.f.deferwrap1).
     */
    "wrapper"?: string;

    /** Creates a new PendingDefer instance. */
    constructor($$source: Partial<PendingDefer> = {}) {
        if (!("order" in $$source)) {
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingDefer instance from a string or object.
     */
    static createFrom($$source: any = {}): PendingDefer {
        const $$createField1_0 = $$createType46;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("location" in $$parsedSource) {
            $$parsedSource["location"] = $$createField1_0($$parsedSource["location"]);
        }
        return new PendingDefer($$parsedSource as Partial<PendingDefer>);
    }
}

export class TestOptions {
    "language"?: string;
    "languageOptions"?: json$0.RawMessage;
    "sessionId": run$0.SessionID;

    /**
     * WorkingDirectory è la cartella del modulo, relativa al progetto ('' per la radice).
     */
    "workingDirectory": string;

    /**
     * Packages sono pattern relativi al modulo, es. "./..." o "./internal/api".
     */
    "packages": string[];

    /**
     * Run è l'espressione regolare di -run; vuota esegue tutti i test.
     */
    "run"?: string;

    /**
     * Bench abilita i benchmark con l'espressione indicata (i test vengono esclusi con -run ^$ se Run è vuoto).
     */
    "bench"?: string;
    "coverage"?: boolean;

    /**
     * Race attiva il race detector (-race): i report finiscono in TestRunSnapshot.RaceReports.
     */
    "race"?: boolean;
    "buildTags"?: string[];
    "environment"?: { [_ in string]?: string };

    /**
     * Repeat esegue ogni test N volte (-count=N) per misurarne la flakiness; 0 o 1 = una volta.
     */
    "repeat"?: number;

    /**
     * Shuffle è "on" per un ordine casuale o un seed numerico per riprodurlo (-shuffle).
     */
    "shuffle"?: string;

    /**
     * CPU esegue i test con questi valori di GOMAXPROCS (-cpu): per ogni valore, Repeat ripetizioni.
     */
    "cpu"?: number[];

    /** Creates a new TestOptions instance. */
    constructor($$source: Partial<TestOptions> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }
        if (!("packages" in $$source)) {
            this["packages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): TestOptions {
        const $$createField4_0 = $$createType1;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType2;
        const $$createField13_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("packages" in $$parsedSource) {
            $$parsedSource["packages"] = $$createField4_0($$parsedSource["packages"]);
        }
        if ("buildTags" in $$parsedSource) {
            $$parsedSource["buildTags"] = $$createField9_0($$parsedSource["buildTags"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField10_0($$parsedSource["environment"]);
        }
        if ("cpu" in $$parsedSource) {
            $$parsedSource["cpu"] = $$createField13_0($$parsedSource["cpu"]);
        }
        return new TestOptions($$parsedSource as Partial<TestOptions>);
    }
}

export class ToolchainConfiguration {
    "goBinary": string;
    "environment"?: { [_ in string]?: string };

    /** Creates a new ToolchainConfiguration instance. */
    constructor($$source: Partial<ToolchainConfiguration> = {}) {
        if (!("goBinary" in $$source)) {
            this["goBinary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainConfiguration instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainConfiguration {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField1_0($$parsedSource["environment"]);
        }
        return new ToolchainConfiguration($$parsedSource as Partial<ToolchainConfiguration>);
    }
}

export class ToolchainInfo {
    "available": boolean;
    "goBinary"?: string;
    "version"?: string;
    "goroot"?: string;
    "gopath"?: string;
    "goproxy"?: string;
    "goprivate"?: string;
    "gomodcache"?: string;
    "gonosumdb"?: string;
    "gonoproxy"?: string;
    "cgoEnabled"?: string;
    "goos"?: string;
    "goarch"?: string;
    "goflags"?: string;
    "gotoolchain"?: string;

    /**
     * GoDirective e ToolchainDirective vengono dal go.mod alla radice del progetto.
     */
    "goDirective"?: string;
    "toolchainDirective"?: string;

    /**
     * Scope vale "project" se la sessione ha una configurazione propria, altrimenti "global".
     */
    "scope"?: string;
    "warning"?: string;
    "error"?: string;

    /**
     * EnvPending: le variabili di go env sono in lettura in background; EnvError non invalida l'SDK.
     */
    "envPending"?: boolean;
    "envError"?: string;

    /**
     * Cached: valori di go env presi dall'ultimo rilevamento salvato (stesso binario, stessa data).
     */
    "cached"?: boolean;
    "timings"?: ToolchainTiming[];

    /**
     * BinaryStamp (dimensione e data del binario) valida la cache senza eseguire go.
     */
    "binaryStamp"?: string;

    /**
     * SDKVersion è la versione locale dell'SDK (es. go1.26.3), letta senza avviare go quando possibile.
     */
    "sdkVersion"?: string;

    /** Creates a new ToolchainInfo instance. */
    constructor($$source: Partial<ToolchainInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainInfo {
        const $$createField23_0 = $$createType56;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("timings" in $$parsedSource) {
            $$parsedSource["timings"] = $$createField23_0($$parsedSource["timings"]);
        }
        return new ToolchainInfo($$parsedSource as Partial<ToolchainInfo>);
    }
}

export class ToolchainInstallation {
    "id": string;
    "sessionId": string;
    "version": string;
    "status": string;
    "downloadedBytes": number;
    "totalBytes": number;
    "message"?: string;
    "goBinary"?: string;
    "log": string[];

    /** Creates a new ToolchainInstallation instance. */
    constructor($$source: Partial<ToolchainInstallation> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("downloadedBytes" in $$source)) {
            this["downloadedBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("log" in $$source)) {
            this["log"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainInstallation instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainInstallation {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField8_0($$parsedSource["log"]);
        }
        return new ToolchainInstallation($$parsedSource as Partial<ToolchainInstallation>);
    }
}

export class ToolchainRelease {
    "version": string;
    "filename": string;
    "sha256": string;
    "size": number;
    "stable": boolean;
    "os": string;
    "arch": string;

    /** Creates a new ToolchainRelease instance. */
    constructor($$source: Partial<ToolchainRelease> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("stable" in $$source)) {
            this["stable"] = false;
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainRelease instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainRelease {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolchainRelease($$parsedSource as Partial<ToolchainRelease>);
    }
}

/**
 * ToolchainSettings espone la configurazione del progetto (se presente) e quella globale.
 */
export class ToolchainSettings {
    "project"?: ToolchainConfiguration | null;
    "global": ToolchainConfiguration;

    /** Creates a new ToolchainSettings instance. */
    constructor($$source: Partial<ToolchainSettings> = {}) {
        if (!("global" in $$source)) {
            this["global"] = (new ToolchainConfiguration());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainSettings {
        const $$createField0_0 = $$createType58;
        const $$createField1_0 = $$createType57;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField0_0($$parsedSource["project"]);
        }
        if ("global" in $$parsedSource) {
            $$parsedSource["global"] = $$createField1_0($$parsedSource["global"]);
        }
        return new ToolchainSettings($$parsedSource as Partial<ToolchainSettings>);
    }
}

/**
 * ToolchainTiming è la durata di una fase del rilevamento, per capire cosa rallenta.
 */
export class ToolchainTiming {
    "phase": string;
    "ms": number;
    "note"?: string;

    /** Creates a new ToolchainTiming instance. */
    constructor($$source: Partial<ToolchainTiming> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("ms" in $$source)) {
            this["ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainTiming instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainTiming {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolchainTiming($$parsedSource as Partial<ToolchainTiming>);
    }
}

// Private type creation functions
const $$createType0 = ArchSite.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Nullable($$createType0);
const $$createType4 = ArchBody.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = ArchImplementation.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ArchRef.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = ArchMethodUse.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ArchNearMiss.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ArchHint.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ArchField.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = ArchPackage.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ArchEdge.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ArchFunction.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = ArchModule.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = ArchInterface.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = ArchEntry.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = ArchSchema.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = ArchQuery.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = ArchContextCall.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = $Create.Array($Create.Any);
const $$createType37 = ErrorFix.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = DocValue.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = DocFunc.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = ErrorEdit.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = dap$0.DebugFrame.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = GoroutineSummary.createFrom;
const $$createType48 = $Create.Array($$createType47);
const $$createType49 = $Create.Array($$createType45);
const $$createType50 = DocType.createFrom;
const $$createType51 = $Create.Array($$createType50);
const $$createType52 = $Create.Map($Create.Any, $$createType1);
const $$createType53 = DocProblem.createFrom;
const $$createType54 = $Create.Array($$createType53);
const $$createType55 = ToolchainTiming.createFrom;
const $$createType56 = $Create.Array($$createType55);
const $$createType57 = ToolchainConfiguration.createFrom;
const $$createType58 = $Create.Nullable($$createType57);
