// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Template represents a reusable template for requests, collections, flows, etc.
 */
export class Template {
    "id": string;
    "name": string;
    "description": string;
    "author": string;
    "version": string;
    "category": string;
    "tags": string[];
    "content": string;
    "icon": string;
    "downloads": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Template instance. */
    constructor($$source: Partial<Template> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("downloads" in $$source)) {
            this["downloads"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Template instance from a string or object.
     */
    static createFrom($$source: any = {}): Template {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        return new Template($$parsedSource as Partial<Template>);
    }
}

/**
 * TemplateCategory represents a template category with its count.
 */
export class TemplateCategory {
    "id": string;
    "name": string;
    "icon": string;
    "count": number;

    /** Creates a new TemplateCategory instance. */
    constructor($$source: Partial<TemplateCategory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateCategory instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateCategory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateCategory($$parsedSource as Partial<TemplateCategory>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
