import type { GoIDEArchEntry, GoIDEArchitecture, GoIDEPackageDoc, GoIDEProtoFile } from '@/lib/goide-api'
import { packageGraph, shortPackage } from './goStudioArchitecture'

type Site = { relativePath: string; line: number }

/** Link a una riga del progetto: l'anteprima Markdown di Go Studio lo apre nell'editor. */
export function sourceLink(site: Site | undefined, label: string): string {
  // "/" = radice del progetto: funziona anche su GitHub, che riconosce pure #L12.
  return site?.relativePath ? `[${label}](/${site.relativePath}#L${site.line})` : label
}

/** "pkg/file.go#L12" → { path, line }: i link generati da sourceLink. */
export function parseSourceLink(href: string): { path: string; line: number } | null {
  const match = /^([^#?]+)#L(\d+)$/.exec(href.replace(/^\.?\//, ''))
  return match ? { path: decodeURIComponent(match[1]), line: Number(match[2]) } : null
}

function fence(code: string, lang = 'go'): string {
  return code ? `\`\`\`${lang}\n${code.trim()}\n\`\`\`\n` : ''
}

/** Documentazione API di un package, nello stile di go doc / pkg.go.dev. */
export function packageDocMarkdown(pkg: GoIDEPackageDoc): string {
  const out: string[] = [`# package ${pkg.name}`, '', `\`import "${pkg.importPath}"\``, '']
  if (pkg.doc) out.push(pkg.doc.trim(), '')
  const index: string[] = []
  for (const fn of pkg.funcs) index.push(`- func ${fn.name}`)
  for (const type of pkg.types) {
    index.push(`- type ${type.name}`)
    for (const fn of type.funcs) index.push(`  - func ${fn.name}`)
    for (const method of type.methods) index.push(`  - func (${method.recv}) ${method.name}`)
  }
  if (index.length) out.push('## Index', '', ...index, '')
  const values = (title: string, items: GoIDEPackageDoc['consts']) => {
    if (!items.length) return
    out.push(`## ${title}`, '')
    for (const item of items) out.push(fence(item.decl), item.doc ? `${item.doc.trim()}\n` : '', `${sourceLink(item.site, 'source')}\n`)
  }
  const func = (fn: GoIDEPackageDoc['funcs'][number], heading: string) => {
    out.push(`### ${heading}`, '', fence(fn.decl), fn.doc ? `${fn.doc.trim()}\n` : '_Undocumented._\n', `${sourceLink(fn.site, 'source')}\n`)
  }
  values('Constants', pkg.consts)
  values('Variables', pkg.vars)
  if (pkg.funcs.length) out.push('## Functions', '')
  for (const fn of pkg.funcs) func(fn, `func ${fn.name}`)
  if (pkg.types.length) out.push('## Types', '')
  for (const type of pkg.types) {
    out.push(`### type ${type.name}`, '', fence(type.decl), type.doc ? `${type.doc.trim()}\n` : '_Undocumented._\n', `${sourceLink(type.site, 'source')}\n`)
    for (const fn of type.funcs) func(fn, `func ${fn.name}`)
    for (const method of type.methods) func(method, `func (${method.recv}) ${method.name}`)
  }
  for (const [marker, notes] of Object.entries(pkg.notes ?? {})) {
    if (!notes?.length) continue
    out.push(`## ${marker}s`, '', ...notes.map((note) => `- ${note}`), '')
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n')
}

/** Tutti i package in un solo documento, con un indice iniziale. */
export function apiDocsMarkdown(packages: readonly GoIDEPackageDoc[], project: string): string {
  const intro = [`# ${project} — API reference`, '', '_Generated by adOmnia Go Studio from the doc comments of the code._', '', '| Package | Synopsis |', '| --- | --- |',
    ...packages.map((pkg) => `| ${pkg.importPath} | ${pkg.synopsis.replace(/\|/g, '\\|') || '—'} |`), '']
  // Un livello di titolo in meno per ogni package: # package → ##, ## Functions → ###, ### func → ####.
  const body = packages.map((pkg) => packageDocMarkdown(pkg).replace(/^(#+) /gm, '#$1 '))
  return [...intro, ...body].join('\n')
}

function mermaidId(value: string): string {
  return `n_${value.replace(/[^A-Za-z0-9]/g, '_')}`
}

/** Diagramma Mermaid degli import tra package (i più collegati), da incorporare nei documenti. */
export function packageMermaid(report: GoIDEArchitecture, limit = 30): string {
  const graph = packageGraph(report, 'imports', null, limit)
  const lines = ['flowchart TD', ...graph.nodes.map((node) => `  ${mermaidId(node.id)}["${node.data.title.replace(/"/g, "'")}"]`), ...graph.links.map((link) => `  ${mermaidId(link.from)} --> ${mermaidId(link.to)}`)]
  return lines.join('\n')
}

const ENTRY_TITLES: Record<string, string> = {
  main: 'Entry points', http: 'HTTP routes', grpc: 'gRPC services', 'kafka-producer': 'Kafka producers', 'kafka-consumer': 'Kafka consumers',
  repository: 'DB repositories', job: 'Scheduled jobs', cli: 'CLI commands',
}

function entryRow(entry: GoIDEArchEntry): string {
  const where = sourceLink(entry.site, `${entry.site.relativePath}:${entry.site.line}`)
  const extra = [entry.detail, entry.topics?.length ? `topics: ${entry.topics.join(', ')}` : ''].filter(Boolean).join(' · ')
  return `| ${entry.kind === 'main' ? shortPackage(entry.name) : entry.name} | ${extra || '—'} | ${where} |`
}

/** Documento di architettura: diagrammi Mermaid, moduli, servizi, entry point e interfacce. */
export function architectureMarkdown(report: GoIDEArchitecture, project: string): string {
  const out = [`# ${project} — Architecture`, '', '_Generated by adOmnia Go Studio from the code (types, imports and calls); regenerate it after structural changes._', '']
  out.push('## Packages', '', `${report.packages.length} packages, ${report.imports.length} internal imports.`, '', '```mermaid', packageMermaid(report), '```', '')
  if (report.modules.length > 1) {
    out.push('## Modules', '', '```mermaid', 'flowchart LR', ...report.modules.map((module) => `  ${mermaidId(module.path)}["${module.path}"]`), ...report.modules.flatMap((module) => module.requires.map((path) => `  ${mermaidId(module.path)} --> ${mermaidId(path)}`)), '```', '')
  }
  for (const [kind, title] of Object.entries(ENTRY_TITLES)) {
    const entries = report.entries.filter((entry) => entry.kind === kind)
    if (!entries.length) continue
    out.push(`## ${title}`, '', '| Name | Details | Source |', '| --- | --- | --- |', ...entries.map(entryRow), '')
  }
  const interfaces = report.interfaces.filter((item) => item.implementations.length > 0)
  if (interfaces.length) {
    out.push('## Interfaces', '', '| Interface | Implementations | Uses |', '| --- | --- | --- |',
      ...interfaces.map((item) => `| ${sourceLink(item.site, `${shortPackage(item.package)}.${item.name}`)} | ${item.implementations.map((impl) => `${impl.pointer ? '*' : ''}${impl.type}`).join(', ')} | ${item.userCount} |`), '')
  }
  return out.join('\n')
}

/** Documentazione dei file .proto: servizi e RPC, messaggi con i campi, enum. */
export function protoMarkdown(files: readonly GoIDEProtoFile[], project: string): string {
  const out = [`# ${project} — Protocol Buffers`, '', '_Generated by adOmnia Go Studio from the .proto files and their comments._', '']
  for (const file of files) {
    out.push(`## ${file.path}`, '')
    if (file.error) {
      out.push(`> Could not read this file: ${file.error}`, '')
      continue
    }
    if (file.package) out.push(`\`package ${file.package}\` · ${file.syntax}`, '')
    if (file.doc) out.push(file.doc, '')
    for (const service of file.services) {
      out.push(`### service ${service.name}`, '', service.doc ? `${service.doc}\n` : '', '| RPC | Request | Response | Description |', '| --- | --- | --- | --- |',
        ...service.methods.map((method) => `| ${method.name} | ${method.clientStreaming ? 'stream ' : ''}${method.input} | ${method.serverStreaming ? 'stream ' : ''}${method.output} | ${(method.doc ?? '').replace(/\n/g, ' ').replace(/\|/g, '\\|')} |`), '')
    }
    for (const message of file.messages) {
      out.push(`### message ${message.name}`, '', message.doc ? `${message.doc}\n` : '')
      if (message.fields.length) out.push('| Field | Number | Type | Description |', '| --- | --- | --- | --- |', ...message.fields.map((field) => `| ${field.name} | ${field.number} | ${[field.label, field.type].filter(Boolean).join(' ')} | ${(field.doc ?? '').replace(/\n/g, ' ').replace(/\|/g, '\\|')} |`), '')
    }
    for (const item of file.enums) {
      out.push(`### enum ${item.name}`, '', item.doc ? `${item.doc}\n` : '', '| Value | Number | Description |', '| --- | --- | --- |', ...item.values.map((value) => `| ${value.name} | ${value.number} | ${(value.doc ?? '').replace(/\n/g, ' ')} |`), '')
    }
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n')
}

const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete', 'head', 'options'])

/** "/orders/:id" e "/files/{path...}" → "/orders/{id}", "/files/{path}". */
export function openApiPath(path: string): { path: string; parameters: string[] } {
  const parameters: string[] = []
  const normalized = path
    .replace(/:([A-Za-z_]\w*)/g, (_m, name: string) => `{${name}}`)
    .replace(/\*([A-Za-z_]\w*)/g, (_m, name: string) => `{${name}}`)
    .replace(/\{([A-Za-z_]\w*)(?:\.\.\.)?(?::[^}]*)?\}/g, (_m, name: string) => {
      parameters.push(name)
      return `{${name}}`
    })
  return { path: normalized || '/', parameters }
}

/**
 * OpenAPI 3.0 dalle route HTTP trovate nel codice: percorsi, metodi, parametri di path, operationId
 * dalla funzione e tag dal package. Le risposte non sono inventate: restano "default".
 */
export function openApiFromRoutes(entries: readonly GoIDEArchEntry[], title: string): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {}
  const usedIds = new Set<string>()
  for (const entry of entries.filter((item) => item.kind === 'http')) {
    const [first, second] = entry.name.split(' ')
    const method = second ? first.toLowerCase() : 'get'
    const route = openApiPath(second ?? first)
    const methods = method === 'any' ? ['get', 'post', 'put', 'patch', 'delete'] : HTTP_METHODS.has(method) ? [method] : ['get']
    for (const verb of methods) {
      let operationId = `${verb}${(entry.function ?? '').replace(/[^A-Za-z0-9]/g, '') || route.path.replace(/[^A-Za-z0-9]/g, '')}`
      for (let suffix = 2; usedIds.has(operationId); suffix++) operationId = `${operationId.replace(/\d+$/, '')}${suffix}`
      usedIds.add(operationId)
      paths[route.path] = {
        ...paths[route.path],
        [verb]: {
          operationId,
          tags: [shortPackage(entry.package)],
          summary: `${verb.toUpperCase()} ${route.path}`,
          description: `Handled in ${entry.function ?? 'unknown'} (${entry.site.relativePath}:${entry.site.line}).`,
          ...(route.parameters.length ? { parameters: route.parameters.map((name) => ({ name, in: 'path', required: true, schema: { type: 'string' } })) } : {}),
          responses: { default: { description: 'Response (not described in the code yet)' } },
        },
      }
    }
  }
  return { openapi: '3.0.3', info: { title, version: '0.0.0', description: 'Generated by adOmnia Go Studio from the HTTP routes found in the code.' }, paths }
}
