// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Collab espone il Collaboration Engine (internal/collab) al frontend.
 * Gli eventi arrivano come "collab:event".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as collab$0 from "./internal/collab/models.js";

export function CreateInvite(role: string, ttlMinutes: number): $CancellablePromise<collab$0.Invite> {
    return $Call.ByID(1607036302, role, ttlMinutes).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Host(ip: string, port: number, name: string): $CancellablePromise<collab$0.Status> {
    return $Call.ByID(3595113677, ip, port, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Join(code: string, name: string): $CancellablePromise<collab$0.Status> {
    return $Call.ByID(531703907, code, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LocalAddresses(): $CancellablePromise<string[]> {
    return $Call.ByID(1409115962).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * PreviewShare restituisce esattamente ciò che lascerebbe la macchina (segreti già rimossi).
 */
export function PreviewShare(kind: string, title: string, dataJSON: string): $CancellablePromise<collab$0.Share> {
    return $Call.ByID(1625525704, kind, title, dataJSON).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Revoke(participantID: string): $CancellablePromise<void> {
    return $Call.ByID(3200509673, participantID);
}

export function SetRole(participantID: string, role: string): $CancellablePromise<void> {
    return $Call.ByID(3855119565, participantID, role);
}

export function Share(kind: string, title: string, dataJSON: string): $CancellablePromise<collab$0.Share> {
    return $Call.ByID(1756118426, kind, title, dataJSON).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Status(): $CancellablePromise<collab$0.Status> {
    return $Call.ByID(3338828213).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(140458795);
}

// Private type creation functions
const $$createType0 = collab$0.Invite.createFrom;
const $$createType1 = collab$0.Status.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = collab$0.Share.createFrom;
