// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "./internal/git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as goide$0 from "./internal/goide/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dap$0 from "./internal/ide/dap/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as remote$0 from "./internal/ide/remote/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as run$0 from "./internal/ide/run/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as security$0 from "./internal/ide/security/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as golang$0 from "./internal/languages/golang/models.js";

/**
 * AIExcludedPaths restituisce, tra i percorsi indicati, quelli che non devono mai lasciare la
 * macchina verso un provider AI: segreti noti (.env, chiavi, certificati) e .adomnia/aiignore del progetto.
 * localProvider indica un modello su questa macchina: conta per la politica "local-only" del progetto.
 */
export function AIExcludedPaths(sessionID: string, relativePaths: string[], localProvider: boolean): $CancellablePromise<string[]> {
    return $Call.ByID(3723098158, sessionID, relativePaths, localProvider).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AIProjectPolicy restituisce la politica AI del progetto: "allowed", "local-only" o "off".
 */
export function AIProjectPolicy(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(703384639, sessionID);
}

/**
 * AcknowledgeCrash chiude la proposta di ripristino dopo la scelta dell'utente.
 */
export function AcknowledgeCrash(): $CancellablePromise<void> {
    return $Call.ByID(1137746749);
}

/**
 * AffectedTestPackages aggiunge ai package indicati quelli del modulo che li importano (anche nei test).
 */
export function AffectedTestPackages(sessionID: string, moduleDirectory: string, packages: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(1503044963, sessionID, moduleDirectory, packages).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AnalyzeArchitecture costruisce package graph, call graph, moduli, interfacce ed entry point (progetto autorizzato).
 */
export function AnalyzeArchitecture(sessionID: string): $CancellablePromise<goide$0.ArchitectureResult> {
    return $Call.ByID(696266605, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AnalyzeErrorHandling analizza la gestione degli errori del progetto (richiede un progetto autorizzato).
 */
export function AnalyzeErrorHandling(sessionID: string): $CancellablePromise<goide$0.ErrorHandlingReport> {
    return $Call.ByID(2448475757, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BaseBranchCoverage misura la coverage degli stessi package sul merge-base con base, in un worktree temporaneo.
 */
export function BaseBranchCoverage(sessionID: string, base: string, packageDirs: string[], buildTags: string[]): $CancellablePromise<goide$0.BaseCoverage> {
    return $Call.ByID(3667514937, sessionID, base, packageDirs, buildTags).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CancelToolchainInstall annulla l'installazione indicata.
 */
export function CancelToolchainInstall(installID: string): $CancellablePromise<void> {
    return $Call.ByID(4098997870, installID);
}

/**
 * CaptureLiveProfile salva nel progetto un profilo scaricato da /debug/pprof di un servizio locale.
 */
export function CaptureLiveProfile(request: goide$0.LiveProfileRequest): $CancellablePromise<goide$0.ProfileFile> {
    return $Call.ByID(1797654015, request).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ResolveCodeAction calcola l'anteprima delle modifiche dell'azione.
 * ChangeSignature riordina o rimuove parametri e risultati della funzione al cursore (anteprima).
 */
export function ChangeSignature(sessionID: string, documentID: string, caret: goide$0.EditorRange, params: number[], results: number[]): $CancellablePromise<goide$0.WorkspaceChange> {
    return $Call.ByID(421509260, sessionID, documentID, caret, params, results).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * CheckDocument rileva cambiamenti su disco senza sovrascrivere il buffer.
 */
export function CheckDocument(sessionID: string, documentID: string, diskToken: string): $CancellablePromise<goide$0.DocumentDiskState> {
    return $Call.ByID(1396526895, sessionID, documentID, diskToken).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ClaimSessionWindow verifica o assegna la proprietà del progetto a una finestra.
 */
export function ClaimSessionWindow(sessionID: string, windowID: string, force: boolean): $CancellablePromise<goide$0.SessionWindow> {
    return $Call.ByID(2048064798, sessionID, windowID, force).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ClearLintBaseline rimuove la baseline del linter.
 */
export function ClearLintBaseline(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3066515929, sessionID);
}

/**
 * ClearSecurityBaseline rimuove la baseline di sicurezza.
 */
export function ClearSecurityBaseline(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2670668266, sessionID);
}

/**
 * ClearSonarBaseline rimuove la baseline SonarQube.
 */
export function ClearSonarBaseline(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1429963985, sessionID);
}

/**
 * CloneRepository clona un repository Git in parent/<nome> e restituisce la cartella, da aprire come progetto.
 */
export function CloneRepository(remoteURL: string, parent: string): $CancellablePromise<string> {
    return $Call.ByID(2395814331, remoteURL, parent);
}

/**
 * CloseDocument rilascia la risorsa documento indicata.
 */
export function CloseDocument(sessionID: string, documentID: string): $CancellablePromise<void> {
    return $Call.ByID(2307973843, sessionID, documentID);
}

/**
 * CloseSession chiude una sessione senza modificare la cartella del progetto.
 */
export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1493129442, id);
}

/**
 * CloseSessionWindow chiude la finestra separata, con conferma se ha buffer
 * non salvati; il progetto torna alla finestra principale.
 */
export function CloseSessionWindow(windowID: string): $CancellablePromise<void> {
    return $Call.ByID(3880902958, windowID);
}

/**
 * CloseTerminal termina shell e albero di processi del terminale.
 */
export function CloseTerminal(terminalID: string): $CancellablePromise<void> {
    return $Call.ByID(2540088910, terminalID);
}

/**
 * CodeActions elenca le azioni disponibili per la selezione.
 */
export function CodeActions(sessionID: string, documentID: string, selection: goide$0.EditorRange, only: string[]): $CancellablePromise<goide$0.CodeActionEntry[]> {
    return $Call.ByID(1196038274, sessionID, documentID, selection, only).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Completion restituisce i suggerimenti gopls; la richiesta si annulla con la promise frontend.
 */
export function Completion(sessionID: string, documentID: string, line: number, column: number): $CancellablePromise<goide$0.CompletionResult> {
    return $Call.ByID(2006528040, sessionID, documentID, line, column).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ConfigureDelve imposta un binario dlv personalizzato; vuoto ripristina la ricerca automatica.
 */
export function ConfigureDelve(sessionID: string, binary: string): $CancellablePromise<void> {
    return $Call.ByID(2721921006, sessionID, binary);
}

/**
 * ConfigureGlobalToolchain imposta la toolchain predefinita dei progetti.
 */
export function ConfigureGlobalToolchain(config: goide$0.ToolchainConfiguration): $CancellablePromise<void> {
    return $Call.ByID(3099500636, config);
}

/**
 * ConfigureGopls imposta un binario gopls personalizzato; vuoto ripristina la ricerca automatica.
 */
export function ConfigureGopls(sessionID: string, binary: string): $CancellablePromise<void> {
    return $Call.ByID(1165998077, sessionID, binary);
}

/**
 * ConfigureLinter imposta un binario linter personalizzato; vuoto ripristina la ricerca automatica.
 */
export function ConfigureLinter(sessionID: string, binary: string): $CancellablePromise<void> {
    return $Call.ByID(1613739800, sessionID, binary);
}

/**
 * ConfigureMake imposta un binario make personalizzato; vuoto ripristina la ricerca automatica.
 */
export function ConfigureMake(sessionID: string, binary: string): $CancellablePromise<void> {
    return $Call.ByID(1128436880, sessionID, binary);
}

/**
 * ConfigureSonarScanner imposta un binario sonar-scanner personalizzato; vuoto ripristina la ricerca automatica.
 */
export function ConfigureSonarScanner(sessionID: string, binary: string): $CancellablePromise<void> {
    return $Call.ByID(2705179157, sessionID, binary);
}

/**
 * ConfigureToolchain imposta binario e variabili della sessione dopo validazione.
 */
export function ConfigureToolchain(sessionID: string, config: goide$0.ToolchainConfiguration): $CancellablePromise<void> {
    return $Call.ByID(3312133885, sessionID, config);
}

/**
 * ConfirmAppClose conferma la chiusura dopo che il frontend ha salvato o scartato i buffer.
 */
export function ConfirmAppClose(): $CancellablePromise<void> {
    return $Call.ByID(437767495);
}

/**
 * ConfirmSessionWindowClose chiude la finestra dopo che ha salvato o scartato i buffer.
 */
export function ConfirmSessionWindowClose(windowID: string): $CancellablePromise<void> {
    return $Call.ByID(916683998, windowID);
}

/**
 * CrashRecoveryStatus dice se l'avvio precedente si è chiuso in modo anomalo (heartbeat fermo).
 */
export function CrashRecoveryStatus(): $CancellablePromise<goide$0.CrashStatus> {
    return $Call.ByID(4294909416).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * CreateDirectory crea una cartella nel progetto.
 */
export function CreateDirectory(sessionID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(1554719629, sessionID, relativePath);
}

/**
 * CreateFiles crea file nuovi nel progetto, tutti o nessuno.
 */
export function CreateFiles(sessionID: string, files: goide$0.NewFile[]): $CancellablePromise<void> {
    return $Call.ByID(3570834985, sessionID, files);
}

/**
 * CreateProject crea un modulo Go (opzionalmente da template) soltanto dopo la conferma esplicita inclusa nella richiesta.
 */
export function CreateProject(request: goide$0.CreateProjectRequest): $CancellablePromise<goide$0.CreateProjectResult> {
    return $Call.ByID(2720329719, request).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * CreateStudioWorkspace crea un workspace Go Studio vuoto e lo rende attivo.
 */
export function CreateStudioWorkspace(name: string): $CancellablePromise<goide$0.StudioWorkspaces> {
    return $Call.ByID(314582753, name).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * DebugDisassemble restituisce il codice macchina attorno all'istruzione corrente di un frame.
 */
export function DebugDisassemble(debugID: string, address: string, before: number, after: number): $CancellablePromise<goide$0.DebugInstruction[]> {
    return $Call.ByID(3808282143, debugID, address, before, after).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * DebugEvaluate valuta un'espressione nel frame indicato.
 */
export function DebugEvaluate(debugID: string, expression: string, frameID: number, context: string): $CancellablePromise<goide$0.EvaluateResult> {
    return $Call.ByID(197128762, debugID, expression, frameID, context).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * DebugGoroutineCreation restituisce l'istruzione go che ha creato la goroutine del thread indicato.
 */
export function DebugGoroutineCreation(debugID: string, threadID: number): $CancellablePromise<goide$0.GoroutineCreation> {
    return $Call.ByID(3205591816, debugID, threadID).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * DebugGoroutines restituisce le goroutine della pausa corrente per la vista Concurrency.
 */
export function DebugGoroutines(debugID: string): $CancellablePromise<goide$0.GoroutineOverview> {
    return $Call.ByID(3386466830, debugID).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * DebugPendingDefers restituisce i defer registrati a runtime dalla goroutine, in ordine di esecuzione.
 */
export function DebugPendingDefers(debugID: string, threadID: number): $CancellablePromise<goide$0.PendingDefer[]> {
    return $Call.ByID(1098904889, debugID, threadID).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * DebugReadMemory legge la memoria da un indirizzo o dall'indirizzo di un'espressione nel frame.
 */
export function DebugReadMemory(debugID: string, location: string, length: number, frameID: number): $CancellablePromise<goide$0.DebugMemory> {
    return $Call.ByID(205932350, debugID, location, length, frameID).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * DebugRunToCursor riprende il programma in pausa fino alla riga indicata.
 */
export function DebugRunToCursor(debugID: string, relativePath: string, line: number, threadID: number): $CancellablePromise<void> {
    return $Call.ByID(2527891005, debugID, relativePath, line, threadID);
}

/**
 * DebugScopes restituisce gli scope di un frame.
 */
export function DebugScopes(debugID: string, frameID: number): $CancellablePromise<goide$0.DebugScope[]> {
    return $Call.ByID(158838328, debugID, frameID).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * DebugShowRegisters mostra o nasconde lo scope Registers nelle variabili dei frame.
 */
export function DebugShowRegisters(debugID: string, show: boolean): $CancellablePromise<void> {
    return $Call.ByID(153264034, debugID, show);
}

/**
 * DebugStackTrace restituisce i frame di una goroutine.
 */
export function DebugStackTrace(debugID: string, threadID: number): $CancellablePromise<goide$0.DebugFrame[]> {
    return $Call.ByID(783686220, debugID, threadID).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * DebugStep esegue continue, pause, next, stepIn o stepOut.
 */
export function DebugStep(debugID: string, action: string, threadID: number): $CancellablePromise<void> {
    return $Call.ByID(2352848127, debugID, action, threadID);
}

/**
 * DebugThreads elenca le goroutine della sessione di debug.
 */
export function DebugThreads(debugID: string): $CancellablePromise<goide$0.DebugThread[]> {
    return $Call.ByID(3763986678, debugID).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * DebugVariables espande un riferimento a variabili.
 */
export function DebugVariables(debugID: string, reference: number): $CancellablePromise<goide$0.DebugVariable[]> {
    return $Call.ByID(3256341458, debugID, reference).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * DeleteFuzzInput cancella un input dal corpus del progetto o dalla cache di Go.
 */
export function DeleteFuzzInput(sessionID: string, packageDir: string, target: string, source: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3932774716, sessionID, packageDir, target, source, name);
}

/**
 * DeletePath elimina un file o una cartella del progetto dopo la conferma nella UI.
 */
export function DeletePath(sessionID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(3684770734, sessionID, relativePath);
}

/**
 * DeleteRunConfiguration elimina una configurazione salvata.
 */
export function DeleteRunConfiguration(sessionID: string, configID: string): $CancellablePromise<void> {
    return $Call.ByID(3107389040, sessionID, configID);
}

/**
 * DeleteStudioWorkspace elimina un workspace Go Studio senza progetti aperti.
 */
export function DeleteStudioWorkspace(id: string): $CancellablePromise<goide$0.StudioWorkspaces> {
    return $Call.ByID(2569365760, id).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * DependencyGraph costruisce il grafo delle dipendenze del modulo senza rete (albero, duplicati, licenze, peso).
 */
export function DependencyGraph(sessionID: string, moduleDirectory: string): $CancellablePromise<goide$0.DependencyGraphReport> {
    return $Call.ByID(3514952437, sessionID, moduleDirectory).then(($result: any) => {
        return $$createType30($result);
    });
}

/**
 * DependencyUpdates elenca le versioni più recenti disponibili per i moduli (richiede rete).
 */
export function DependencyUpdates(sessionID: string, moduleDirectory: string): $CancellablePromise<goide$0.DependencyUpdate[]> {
    return $Call.ByID(2706812095, sessionID, moduleDirectory).then(($result: any) => {
        return $$createType32($result);
    });
}

/**
 * DependencyVulnerabilities esegue govulncheck sul modulo (richiede rete e govulncheck installato).
 */
export function DependencyVulnerabilities(sessionID: string, moduleDirectory: string): $CancellablePromise<goide$0.DependencyVulnerability[]> {
    return $Call.ByID(704365663, sessionID, moduleDirectory).then(($result: any) => {
        return $$createType34($result);
    });
}

/**
 * DetectDelve individua dlv e ne legge la versione.
 */
export function DetectDelve(sessionID: string): $CancellablePromise<goide$0.DelveInfo> {
    return $Call.ByID(1393069235, sessionID).then(($result: any) => {
        return $$createType35($result);
    });
}

/**
 * DetectGoTool cerca un tool Go (govulncheck, goimports, mockgen, stringer o personalizzato).
 */
export function DetectGoTool(sessionID: string, binary: string): $CancellablePromise<goide$0.GoToolInfo> {
    return $Call.ByID(1968356021, sessionID, binary).then(($result: any) => {
        return $$createType36($result);
    });
}

/**
 * DetectGopls individua gopls e ne legge la versione.
 */
export function DetectGopls(sessionID: string): $CancellablePromise<goide$0.GoplsInfo> {
    return $Call.ByID(3730884956, sessionID).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * DetectLinter individua golangci-lint o staticcheck e la configurazione di progetto.
 */
export function DetectLinter(sessionID: string): $CancellablePromise<goide$0.LinterInfo> {
    return $Call.ByID(766054627, sessionID).then(($result: any) => {
        return $$createType38($result);
    });
}

/**
 * DetectMake indica quale make userebbe la sessione per i Makefile del progetto.
 */
export function DetectMake(sessionID: string): $CancellablePromise<goide$0.MakeInfo> {
    return $Call.ByID(1963785503, sessionID).then(($result: any) => {
        return $$createType39($result);
    });
}

/**
 * DetectSonarScanner cerca sonar-scanner per la sessione.
 */
export function DetectSonarScanner(sessionID: string): $CancellablePromise<goide$0.SonarScannerInfo> {
    return $Call.ByID(3563278938, sessionID).then(($result: any) => {
        return $$createType40($result);
    });
}

/**
 * DetectToolchain rileva la toolchain Go su richiesta dell'utente.
 */
export function DetectToolchain(sessionID: string): $CancellablePromise<goide$0.ToolchainInfo> {
    return $Call.ByID(4216240268, sessionID).then(($result: any) => {
        return $$createType41($result);
    });
}

/**
 * DismissInterruptedProcess chiude la proposta di rilancio di un'esecuzione interrotta.
 */
export function DismissInterruptedProcess(runID: string): $CancellablePromise<void> {
    return $Call.ByID(535000237, runID);
}

/**
 * DocumentHighlights evidenzia occorrenze e punti di uscita al cursore.
 */
export function DocumentHighlights(sessionID: string, documentID: string, line: number, column: number): $CancellablePromise<goide$0.HighlightsResult> {
    return $Call.ByID(3761108026, sessionID, documentID, line, column).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * DocumentSymbols restituisce la struttura del file.
 */
export function DocumentSymbols(sessionID: string, documentID: string): $CancellablePromise<goide$0.DocumentSymbolsResult> {
    return $Call.ByID(2127272604, sessionID, documentID).then(($result: any) => {
        return $$createType43($result);
    });
}

/**
 * Documentation legge la documentazione dei package Go e dei file .proto del progetto (solo parsing).
 */
export function Documentation(sessionID: string): $CancellablePromise<goide$0.DocumentationReport> {
    return $Call.ByID(3196489204, sessionID).then(($result: any) => {
        return $$createType44($result);
    });
}

/**
 * DuplicatePath copia un file o una cartella del progetto in un nuovo percorso.
 */
export function DuplicatePath(sessionID: string, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(1717599684, sessionID, $from, to);
}

/**
 * DuplicateRunConfiguration copia una configurazione esistente.
 */
export function DuplicateRunConfiguration(sessionID: string, configID: string): $CancellablePromise<goide$0.RunConfiguration> {
    return $Call.ByID(2204031694, sessionID, configID).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * ExpandHierarchy carica i figli di un nodo della gerarchia.
 */
export function ExpandHierarchy(sessionID: string, direction: string, token: string): $CancellablePromise<goide$0.HierarchyItem[]> {
    return $Call.ByID(2428419337, sessionID, direction, token).then(($result: any) => {
        return $$createType47($result);
    });
}

/**
 * FetchSonarIssues importa gli issue già presenti sul server, senza rieseguire la scansione.
 */
export function FetchSonarIssues(sessionID: string, token: string): $CancellablePromise<goide$0.SonarScanResult> {
    return $Call.ByID(3046232717, sessionID, token).then(($result: any) => {
        return $$createType48($result);
    });
}

/**
 * FindSessionsForPath elenca le altre sessioni che contengono lo stesso file.
 */
export function FindSessionsForPath(sessionID: string, relativePath: string): $CancellablePromise<goide$0.Session[]> {
    return $Call.ByID(2186358452, sessionID, relativePath).then(($result: any) => {
        return $$createType50($result);
    });
}

/**
 * FocusSessionWindow porta in primo piano la finestra separata indicata.
 */
export function FocusSessionWindow(windowID: string): $CancellablePromise<void> {
    return $Call.ByID(2299026646, windowID);
}

/**
 * ForgetBuffer scarta un buffer dallo store di recupero.
 */
export function ForgetBuffer(sessionID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(342971689, sessionID, relativePath);
}

/**
 * FormatDocument restituisce gli edit di formattazione del buffer.
 */
export function FormatDocument(sessionID: string, documentID: string): $CancellablePromise<goide$0.FormatResult> {
    return $Call.ByID(3626188168, sessionID, documentID).then(($result: any) => {
        return $$createType51($result);
    });
}

/**
 * GenerateGoCode genera costruttore, getter/setter, interfaccia, benchmark o fuzz test sul testo indicato.
 */
export function GenerateGoCode(request: goide$0.CodeGenRequest): $CancellablePromise<goide$0.CodeGenResult> {
    return $Call.ByID(3959093954, request).then(($result: any) => {
        return $$createType52($result);
    });
}

/**
 * GetCapabilities restituisce soltanto le capacità Go Studio realmente disponibili.
 */
export function GetCapabilities(): $CancellablePromise<goide$0.Capabilities> {
    return $Call.ByID(1829330672).then(($result: any) => {
        return $$createType53($result);
    });
}

/**
 * GetLanguageServerLog restituisce le ultime righe di log gopls.
 */
export function GetLanguageServerLog(sessionID: string): $CancellablePromise<string[]> {
    return $Call.ByID(2835951279, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetLanguageServerStatus restituisce lo stato di gopls per la sessione.
 */
export function GetLanguageServerStatus(sessionID: string): $CancellablePromise<goide$0.LanguageServerStatus> {
    return $Call.ByID(2789580425, sessionID).then(($result: any) => {
        return $$createType54($result);
    });
}

/**
 * GetSessionView restituisce layout e tab ripristinabili della sessione.
 */
export function GetSessionView(sessionID: string): $CancellablePromise<goide$0.SessionView> {
    return $Call.ByID(487629595, sessionID).then(($result: any) => {
        return $$createType55($result);
    });
}

/**
 * GetTestOutput restituisce l'output di un solo test.
 */
export function GetTestOutput(runID: string, nodeID: string): $CancellablePromise<string> {
    return $Call.ByID(1880778095, runID, nodeID);
}

/**
 * GetTestRun restituisce un'esecuzione di test con l'output di ogni nodo.
 */
export function GetTestRun(runID: string): $CancellablePromise<goide$0.TestRunSnapshot> {
    return $Call.ByID(1756958655, runID).then(($result: any) => {
        return $$createType56($result);
    });
}

/**
 * GoAuthWithGitCredentials è il valore GOAUTH che fa usare a go le credenziali di Git.
 */
export function GoAuthWithGitCredentials(): $CancellablePromise<string> {
    return $Call.ByID(2724165580);
}

/**
 * GoWorkState legge go.work e i moduli rilevati del progetto.
 */
export function GoWorkState(sessionID: string): $CancellablePromise<goide$0.GoWorkState> {
    return $Call.ByID(89591822, sessionID).then(($result: any) => {
        return $$createType57($result);
    });
}

/**
 * HasActiveRuns indica se la sessione possiede processi attivi.
 */
export function HasActiveRuns(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(683137982, sessionID);
}

/**
 * HasActiveTerminals indica se la sessione possiede shell ancora vive.
 */
export function HasActiveTerminals(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1359697245, sessionID);
}

/**
 * Hover restituisce la documentazione del simbolo sotto il cursore.
 */
export function Hover(sessionID: string, documentID: string, line: number, column: number): $CancellablePromise<goide$0.HoverResult> {
    return $Call.ByID(3429230612, sessionID, documentID, line, column).then(($result: any) => {
        return $$createType58($result);
    });
}

/**
 * ImplementationMarkers restituisce i marcatori del gutter per implementazioni e interfacce implementate.
 */
export function ImplementationMarkers(sessionID: string, documentID: string): $CancellablePromise<goide$0.ImplementationMarker[]> {
    return $Call.ByID(3534814275, sessionID, documentID).then(($result: any) => {
        return $$createType60($result);
    });
}

/**
 * InlayHints restituisce i suggerimenti in linea per l'intervallo visibile.
 */
export function InlayHints(sessionID: string, documentID: string, visible: goide$0.EditorRange): $CancellablePromise<goide$0.InlayHintsResult> {
    return $Call.ByID(75205433, sessionID, documentID, visible).then(($result: any) => {
        return $$createType61($result);
    });
}

/**
 * InstallDelve installa dlv nella cartella strumenti di adOmnia dopo conferma esplicita.
 */
export function InstallDelve(sessionID: string, confirmed: boolean): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(3713187823, sessionID, confirmed).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * InstallGoModule esegue go install di un modulo@versione nella cartella strumenti, dopo conferma.
 */
export function InstallGoModule(sessionID: string, $module: string, confirmed: boolean): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(136977155, sessionID, $module, confirmed).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * InstallGopls installa gopls nella cartella strumenti di adOmnia dopo conferma esplicita.
 */
export function InstallGopls(sessionID: string, confirmed: boolean): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(950784120, sessionID, confirmed).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * InstallLinter installa golangci-lint o staticcheck nella cartella strumenti dopo conferma esplicita.
 */
export function InstallLinter(sessionID: string, kind: string, confirmed: boolean): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(576546735, sessionID, kind, confirmed).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * InstallToolchain avvia download, checksum ed estrazione della versione scelta.
 */
export function InstallToolchain(request: goide$0.InstallToolchainRequest): $CancellablePromise<goide$0.ToolchainInstallation> {
    return $Call.ByID(1084560520, request).then(($result: any) => {
        return $$createType63($result);
    });
}

/**
 * InterruptedProcesses elenca le esecuzioni interrotte dal crash dell'avvio precedente.
 */
export function InterruptedProcesses(): $CancellablePromise<goide$0.ProcessDescriptor[]> {
    return $Call.ByID(2959813917).then(($result: any) => {
        return $$createType65($result);
    });
}

/**
 * LinterConfigFile restituisce (o, con create, crea) il file di configurazione del linter del progetto.
 */
export function LinterConfigFile(sessionID: string, create: boolean): $CancellablePromise<string> {
    return $Call.ByID(3265313512, sessionID, create);
}

/**
 * ListBreakpoints restituisce i breakpoint salvati della sessione.
 */
export function ListBreakpoints(sessionID: string): $CancellablePromise<goide$0.FileBreakpoints[]> {
    return $Call.ByID(31206758, sessionID).then(($result: any) => {
        return $$createType67($result);
    });
}

/**
 * ListDebugSessions elenca le sessioni di debug del progetto.
 */
export function ListDebugSessions(sessionID: string): $CancellablePromise<goide$0.DebugSessionInfo[]> {
    return $Call.ByID(21898424, sessionID).then(($result: any) => {
        return $$createType69($result);
    });
}

/**
 * ListDependencies legge le dipendenze del modulo senza eseguire comandi.
 */
export function ListDependencies(sessionID: string, moduleDirectory: string): $CancellablePromise<goide$0.DependencyState> {
    return $Call.ByID(2974208523, sessionID, moduleDirectory).then(($result: any) => {
        return $$createType70($result);
    });
}

/**
 * ListDirectory carica un singolo livello dell'albero file.
 */
export function ListDirectory(sessionID: string, relativePath: string, includeIgnored: boolean): $CancellablePromise<goide$0.FileEntry[]> {
    return $Call.ByID(837250229, sessionID, relativePath, includeIgnored).then(($result: any) => {
        return $$createType72($result);
    });
}

/**
 * ListFunctionBreakpoints restituisce i breakpoint di funzione e il panic breakpoint del progetto.
 */
export function ListFunctionBreakpoints(sessionID: string): $CancellablePromise<goide$0.FunctionBreakpointsView> {
    return $Call.ByID(1495099682, sessionID).then(($result: any) => {
        return $$createType73($result);
    });
}

/**
 * ListFuzzTargets elenca le funzioni Fuzz* con il corpus in testdata/fuzz e nella cache di Go.
 */
export function ListFuzzTargets(sessionID: string): $CancellablePromise<goide$0.FuzzTarget[]> {
    return $Call.ByID(3704774411, sessionID).then(($result: any) => {
        return $$createType75($result);
    });
}

/**
 * ListInstalledToolchains restituisce le versioni Go isolate disponibili localmente.
 */
export function ListInstalledToolchains(sessionID: string): $CancellablePromise<goide$0.InstalledToolchain[]> {
    return $Call.ByID(2475261184, sessionID).then(($result: any) => {
        return $$createType77($result);
    });
}

/**
 * ListLocalHistory elenca le versioni salvate di un file.
 */
export function ListLocalHistory(sessionID: string, relativePath: string): $CancellablePromise<goide$0.HistoryRevision[]> {
    return $Call.ByID(2316806831, sessionID, relativePath).then(($result: any) => {
        return $$createType79($result);
    });
}

/**
 * ListModuleVersions elenca le versioni pubblicate di una dipendenza, dalla più recente.
 */
export function ListModuleVersions(sessionID: string, moduleDirectory: string, modulePath: string): $CancellablePromise<string[]> {
    return $Call.ByID(706135679, sessionID, moduleDirectory, modulePath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListProcesses elenca i processi locali per Attach to Process.
 */
export function ListProcesses(): $CancellablePromise<goide$0.ProcessInfo[]> {
    return $Call.ByID(1033358035).then(($result: any) => {
        return $$createType81($result);
    });
}

/**
 * ListProfileFiles elenca i profili pprof (*.pprof) trovati nel progetto, per il Performance Studio.
 */
export function ListProfileFiles(sessionID: string): $CancellablePromise<goide$0.ProfileFile[]> {
    return $Call.ByID(3062046298, sessionID).then(($result: any) => {
        return $$createType82($result);
    });
}

/**
 * ListProjectTemplates restituisce i template di progetto integrati e quelli dell'utente.
 */
export function ListProjectTemplates(): $CancellablePromise<goide$0.ProjectTemplateList> {
    return $Call.ByID(2915770842).then(($result: any) => {
        return $$createType83($result);
    });
}

/**
 * ListRecentProjects restituisce i progetti locali aperti di recente.
 */
export function ListRecentProjects(): $CancellablePromise<goide$0.RecentProject[]> {
    return $Call.ByID(20282631).then(($result: any) => {
        return $$createType85($result);
    });
}

/**
 * ListRecoveredBuffers elenca i buffer non salvati ritrovati dopo un riavvio.
 */
export function ListRecoveredBuffers(sessionID: string): $CancellablePromise<goide$0.RecoveredBuffer[]> {
    return $Call.ByID(1873457286, sessionID).then(($result: any) => {
        return $$createType87($result);
    });
}

/**
 * ListRemoteTargets elenca gli ambienti in cui eseguire run e test: distro WSL, host SSH, container.
 */
export function ListRemoteTargets(): $CancellablePromise<goide$0.RemoteTarget[]> {
    return $Call.ByID(3383312002).then(($result: any) => {
        return $$createType89($result);
    });
}

/**
 * ListRunConfigurations elenca le configurazioni Run salvate della sessione.
 */
export function ListRunConfigurations(sessionID: string): $CancellablePromise<goide$0.RunConfiguration[]> {
    return $Call.ByID(2220453324, sessionID).then(($result: any) => {
        return $$createType90($result);
    });
}

/**
 * ListRuns restituisce le esecuzioni note per una sessione.
 */
export function ListRuns(sessionID: string): $CancellablePromise<goide$0.Execution[]> {
    return $Call.ByID(1260420124, sessionID).then(($result: any) => {
        return $$createType91($result);
    });
}

/**
 * ListSessionWindows elenca i progetti aperti in finestre separate.
 */
export function ListSessionWindows(): $CancellablePromise<goide$0.SessionWindow[]> {
    return $Call.ByID(1623214695).then(($result: any) => {
        return $$createType92($result);
    });
}

/**
 * ListSessions restituisce le sessioni Go Studio correnti e ripristinate.
 */
export function ListSessions(): $CancellablePromise<goide$0.Session[]> {
    return $Call.ByID(1758091587).then(($result: any) => {
        return $$createType50($result);
    });
}

/**
 * ListStudioWorkspaces elenca i workspace Go Studio, separati dai workspace API di adOmnia.
 */
export function ListStudioWorkspaces(): $CancellablePromise<goide$0.StudioWorkspaces> {
    return $Call.ByID(3174743582).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ListTerminalProfiles rileva le shell disponibili (PowerShell, cmd, Git Bash, distro WSL, zsh…).
 */
export function ListTerminalProfiles(): $CancellablePromise<goide$0.TerminalProfile[]> {
    return $Call.ByID(456418912).then(($result: any) => {
        return $$createType94($result);
    });
}

/**
 * ListTerminals elenca i terminali della sola sessione indicata.
 */
export function ListTerminals(sessionID: string): $CancellablePromise<goide$0.TerminalSession[]> {
    return $Call.ByID(1696358663, sessionID).then(($result: any) => {
        return $$createType96($result);
    });
}

/**
 * ListTestRuns restituisce le esecuzioni di test della sessione, dalla più recente.
 */
export function ListTestRuns(sessionID: string): $CancellablePromise<goide$0.TestRunSnapshot[]> {
    return $Call.ByID(2118292916, sessionID).then(($result: any) => {
        return $$createType97($result);
    });
}

/**
 * ListToolchainReleases restituisce il catalogo ufficiale compatibile su richiesta esplicita.
 */
export function ListToolchainReleases(sessionID: string): $CancellablePromise<goide$0.ToolchainRelease[]> {
    return $Call.ByID(2275849171, sessionID).then(($result: any) => {
        return $$createType99($result);
    });
}

/**
 * ListTraceFiles elenca i file di esecuzione trace (`trace.out`, `*.trace`) del progetto.
 */
export function ListTraceFiles(sessionID: string): $CancellablePromise<goide$0.ProfileFile[]> {
    return $Call.ByID(2286675290, sessionID).then(($result: any) => {
        return $$createType82($result);
    });
}

/**
 * LoadProfile interpreta un profilo pprof del progetto in un report per il Performance Studio.
 */
export function LoadProfile(sessionID: string, relativePath: string): $CancellablePromise<goide$0.ProfileReport> {
    return $Call.ByID(2225739751, sessionID, relativePath).then(($result: any) => {
        return $$createType100($result);
    });
}

/**
 * LoadTrace interpreta un file trace del progetto in una timeline per il viewer.
 */
export function LoadTrace(sessionID: string, relativePath: string): $CancellablePromise<goide$0.TraceReport> {
    return $Call.ByID(1813296855, sessionID, relativePath).then(($result: any) => {
        return $$createType101($result);
    });
}

/**
 * LocalHistoryContent restituisce il testo di una versione della local history.
 */
export function LocalHistoryContent(sessionID: string, relativePath: string, revisionID: string): $CancellablePromise<string> {
    return $Call.ByID(1353648188, sessionID, relativePath, revisionID);
}

/**
 * Locations esegue definition, typeDefinition, implementation o references.
 */
export function Locations(sessionID: string, documentID: string, kind: string, line: number, column: number): $CancellablePromise<goide$0.EditorLocation[]> {
    return $Call.ByID(326701862, sessionID, documentID, kind, line, column).then(($result: any) => {
        return $$createType103($result);
    });
}

/**
 * MovePath rinomina o sposta un file o una cartella del progetto, senza sovrascrivere.
 */
export function MovePath(sessionID: string, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(1453875656, sessionID, $from, to);
}

/**
 * MoveSymbol sposta una dichiarazione in un altro package del modulo; restituisce l'anteprima delle modifiche.
 */
export function MoveSymbol(sessionID: string, request: goide$0.MoveSymbolRequest): $CancellablePromise<goide$0.WorkspaceChange> {
    return $Call.ByID(2769978375, sessionID, request).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OpenDocument apre un documento testuale o un'immagine confinato al progetto.
 */
export function OpenDocument(sessionID: string, relativePath: string): $CancellablePromise<goide$0.OpenDocument> {
    return $Call.ByID(3794134535, sessionID, relativePath).then(($result: any) => {
        return $$createType104($result);
    });
}

/**
 * OpenExternalDocument apre in sola lettura un sorgente dell'SDK Go o della module cache.
 */
export function OpenExternalDocument(sessionID: string, path: string): $CancellablePromise<goide$0.OpenDocument> {
    return $Call.ByID(3817412392, sessionID, path).then(($result: any) => {
        return $$createType104($result);
    });
}

/**
 * OpenProject registra una cartella locale senza avviarne codice o strumenti.
 */
export function OpenProject(path: string): $CancellablePromise<goide$0.Session> {
    return $Call.ByID(1300673995, path).then(($result: any) => {
        return $$createType49($result);
    });
}

/**
 * OpenSessionWindow sposta il progetto in una finestra Go Studio separata, o
 * mette a fuoco quella già aperta. Il frontend chiamante deve aver salvato i
 * buffer del progetto: restano nella finestra che li possiede.
 */
export function OpenSessionWindow(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(4188900226, sessionID);
}

/**
 * OpenTerminal apre una shell interattiva reale nella working directory del progetto.
 */
export function OpenTerminal(request: goide$0.TerminalRequest): $CancellablePromise<goide$0.TerminalSession> {
    return $Call.ByID(4136168338, request).then(($result: any) => {
        return $$createType95($result);
    });
}

/**
 * OrganizeImports calcola la pulizia degli import del file.
 */
export function OrganizeImports(sessionID: string, documentID: string): $CancellablePromise<goide$0.WorkspaceChange> {
    return $Call.ByID(1128610991, sessionID, documentID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * PrepareHierarchy apre Call Hierarchy o Type Hierarchy sul simbolo al cursore.
 */
export function PrepareHierarchy(sessionID: string, documentID: string, kind: string, line: number, column: number): $CancellablePromise<goide$0.HierarchyItem[]> {
    return $Call.ByID(4123984876, sessionID, documentID, kind, line, column).then(($result: any) => {
        return $$createType47($result);
    });
}

/**
 * PrepareRename verifica il simbolo da rinominare.
 */
export function PrepareRename(sessionID: string, documentID: string, line: number, column: number): $CancellablePromise<goide$0.RenameTarget> {
    return $Call.ByID(2777806199, sessionID, documentID, line, column).then(($result: any) => {
        return $$createType105($result);
    });
}

/**
 * PreviewGoTool mostra il comando Go Tools esatto prima dell'esecuzione.
 */
export function PreviewGoTool(request: goide$0.GoToolRequest): $CancellablePromise<goide$0.GoToolPreview> {
    return $Call.ByID(1722645302, request).then(($result: any) => {
        return $$createType106($result);
    });
}

/**
 * PrivateRepoCredentialStatus dice se il gestore credenziali di Git conosce l'host (mai il token).
 */
export function PrivateRepoCredentialStatus(host: string): $CancellablePromise<goide$0.PrivateRepoCredential> {
    return $Call.ByID(2894914022, host).then(($result: any) => {
        return $$createType107($result);
    });
}

/**
 * ProjectServices elenca i servizi esterni (database, broker, osservabilità) usati dal progetto.
 */
export function ProjectServices(sessionID: string): $CancellablePromise<goide$0.ProjectService[]> {
    return $Call.ByID(297239615, sessionID).then(($result: any) => {
        return $$createType109($result);
    });
}

/**
 * PromoteFuzzInput copia un input generato in testdata/fuzz, dove ogni go test lo riesegue.
 */
export function PromoteFuzzInput(sessionID: string, packageDir: string, target: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3962585773, sessionID, packageDir, target, name);
}

/**
 * PruneMissingSessions rimuove le sessioni la cui cartella non esiste più.
 */
export function PruneMissingSessions(): $CancellablePromise<goide$0.Session[]> {
    return $Call.ByID(1286303007).then(($result: any) => {
        return $$createType50($result);
    });
}

/**
 * QuickDefinition restituisce il sorgente della dichiarazione al cursore per il popup Quick Definition.
 */
export function QuickDefinition(sessionID: string, documentID: string, line: number, column: number): $CancellablePromise<goide$0.QuickDefinitionResult> {
    return $Call.ByID(3849385104, sessionID, documentID, line, column).then(($result: any) => {
        return $$createType110($result);
    });
}

/**
 * QuickOpen cerca file del progetto con limite dei risultati.
 */
export function QuickOpen(sessionID: string, query: string, limit: number): $CancellablePromise<goide$0.QuickOpenResult[]> {
    return $Call.ByID(2164854073, sessionID, query, limit).then(($result: any) => {
        return $$createType112($result);
    });
}

/**
 * ReadFileDataURL legge un'immagine del progetto come data URL, per gli asset del Markdown.
 */
export function ReadFileDataURL(sessionID: string, relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(2287309373, sessionID, relativePath);
}

/**
 * ReadFuzzInput interpreta un input del corpus fuzz.
 */
export function ReadFuzzInput(sessionID: string, packageDir: string, target: string, source: string, name: string): $CancellablePromise<goide$0.FuzzInputContent> {
    return $Call.ByID(2681117665, sessionID, packageDir, target, source, name).then(($result: any) => {
        return $$createType113($result);
    });
}

/**
 * RecursiveCalls restituisce le chiamate ricorsive dirette del file.
 */
export function RecursiveCalls(sessionID: string, documentID: string): $CancellablePromise<goide$0.RecursiveCallsResult> {
    return $Call.ByID(2923315195, sessionID, documentID).then(($result: any) => {
        return $$createType114($result);
    });
}

/**
 * RememberBuffer conserva un buffer non salvato nello store di recupero locale.
 */
export function RememberBuffer(sessionID: string, relativePath: string, content: string, diskToken: string): $CancellablePromise<void> {
    return $Call.ByID(549670995, sessionID, relativePath, content, diskToken);
}

/**
 * RemoveInstalledToolchain elimina una versione gestita non in uso.
 */
export function RemoveInstalledToolchain(version: string, confirmed: boolean): $CancellablePromise<void> {
    return $Call.ByID(2289775931, version, confirmed);
}

/**
 * RemovePrivateRepoCredential toglie le credenziali di un host dal gestore credenziali di Git.
 */
export function RemovePrivateRepoCredential(host: string): $CancellablePromise<void> {
    return $Call.ByID(325263024, host);
}

/**
 * RemoveRecentProject rimuove una voce recente senza modificare il filesystem.
 */
export function RemoveRecentProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(74402166, path);
}

/**
 * Rename calcola l'anteprima del rename semantico.
 */
export function Rename(sessionID: string, documentID: string, line: number, column: number, newName: string): $CancellablePromise<goide$0.WorkspaceChange> {
    return $Call.ByID(2412201980, sessionID, documentID, line, column, newName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RenameRunConfiguration rinomina una configurazione esistente.
 */
export function RenameRunConfiguration(sessionID: string, configID: string, name: string): $CancellablePromise<goide$0.RunConfiguration> {
    return $Call.ByID(2219541861, sessionID, configID, name).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * RenameStudioWorkspace rinomina un workspace Go Studio.
 */
export function RenameStudioWorkspace(id: string, name: string): $CancellablePromise<goide$0.StudioWorkspaces> {
    return $Call.ByID(2788191155, id, name).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * RenameTerminal cambia il nome mostrato nel tab del terminale.
 */
export function RenameTerminal(terminalID: string, name: string): $CancellablePromise<goide$0.TerminalSession> {
    return $Call.ByID(3169343836, terminalID, name).then(($result: any) => {
        return $$createType95($result);
    });
}

/**
 * ReorderRunConfigurations applica l'ordine scelto dall'utente.
 */
export function ReorderRunConfigurations(sessionID: string, configIDs: string[]): $CancellablePromise<goide$0.RunConfiguration[]> {
    return $Call.ByID(2094160389, sessionID, configIDs).then(($result: any) => {
        return $$createType90($result);
    });
}

/**
 * ResizeTerminal adegua il PTY alle dimensioni correnti del pannello.
 */
export function ResizeTerminal(terminalID: string, columns: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3179382934, terminalID, columns, rows);
}

export function ResolveCodeAction(sessionID: string, actionID: string): $CancellablePromise<goide$0.WorkspaceChange> {
    return $Call.ByID(478250469, sessionID, actionID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RestartLanguageServer riavvia gopls azzerando il contatore dei crash.
 */
export function RestartLanguageServer(sessionID: string, settings: goide$0.LanguageServerSettings): $CancellablePromise<goide$0.LanguageServerStatus> {
    return $Call.ByID(1171223752, sessionID, settings).then(($result: any) => {
        return $$createType54($result);
    });
}

/**
 * RestartRun riavvia la configurazione associata a un'esecuzione.
 */
export function RestartRun(runID: string): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(41995706, runID).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * RevealPath mostra un elemento del progetto nel file manager del sistema.
 */
export function RevealPath(sessionID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(354632432, sessionID, relativePath);
}

/**
 * RunGoTool esegue un tool Go rilevato con argomenti strutturati nella cartella indicata.
 */
export function RunGoTool(sessionID: string, binary: string, $arguments: string[], workingDirectory: string): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(727920603, sessionID, binary, $arguments, workingDirectory).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * RunLint esegue il linter sul progetto; si annulla con la promise frontend.
 */
export function RunLint(sessionID: string): $CancellablePromise<goide$0.LintResult> {
    return $Call.ByID(1402341846, sessionID).then(($result: any) => {
        return $$createType115($result);
    });
}

/**
 * RunLintChanged esegue il linter solo sui file Go modificati; si annulla con la promise frontend.
 */
export function RunLintChanged(sessionID: string): $CancellablePromise<goide$0.LintResult> {
    return $Call.ByID(3396593074, sessionID).then(($result: any) => {
        return $$createType115($result);
    });
}

/**
 * RunSonarScan esegue sonar-scanner e importa gli issue dalla Web API.
 */
export function RunSonarScan(sessionID: string, token: string): $CancellablePromise<goide$0.SonarScanResult> {
    return $Call.ByID(2848034091, sessionID, token).then(($result: any) => {
        return $$createType48($result);
    });
}

/**
 * SaveDocument salva atomicamente il buffer con protezione dalle modifiche esterne.
 */
export function SaveDocument(sessionID: string, documentID: string, content: string, diskToken: string, force: boolean): $CancellablePromise<goide$0.OpenDocument> {
    return $Call.ByID(3463741930, sessionID, documentID, content, diskToken, force).then(($result: any) => {
        return $$createType104($result);
    });
}

/**
 * SaveLintBaseline registra i problemi attuali del linter in .adomnia/lint-baseline.json.
 */
export function SaveLintBaseline(sessionID: string): $CancellablePromise<number> {
    return $Call.ByID(2148470405, sessionID);
}

/**
 * SavePrivateRepoCredential affida username e token di un host privato al gestore credenziali di Git.
 */
export function SavePrivateRepoCredential(host: string, username: string, token: string): $CancellablePromise<goide$0.PrivateRepoCredential> {
    return $Call.ByID(1996559851, host, username, token).then(($result: any) => {
        return $$createType107($result);
    });
}

/**
 * SaveRunConfiguration crea o aggiorna una configurazione Run validata.
 */
export function SaveRunConfiguration(sessionID: string, config: goide$0.RunConfiguration): $CancellablePromise<goide$0.RunConfiguration> {
    return $Call.ByID(2344626746, sessionID, config).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * SaveSecurityBaseline accetta i finding attuali: le scansioni successive mostrano solo i nuovi.
 */
export function SaveSecurityBaseline(sessionID: string): $CancellablePromise<number> {
    return $Call.ByID(3698748742, sessionID);
}

/**
 * SaveSessionView registra layout e tab della sessione, senza contenuti dei file.
 */
export function SaveSessionView(sessionID: string, view: goide$0.SessionView): $CancellablePromise<void> {
    return $Call.ByID(4208673812, sessionID, view);
}

/**
 * SaveSonarBaseline registra gli issue attuali come accettati.
 */
export function SaveSonarBaseline(sessionID: string, token: string): $CancellablePromise<number> {
    return $Call.ByID(1351289117, sessionID, token);
}

/**
 * SaveSonarConfig salva server, chiave e percorsi; il token è separato e resta in memoria.
 */
export function SaveSonarConfig(sessionID: string, config: goide$0.SonarConfig): $CancellablePromise<goide$0.SonarConfig> {
    return $Call.ByID(2689463436, sessionID, config).then(($result: any) => {
        return $$createType116($result);
    });
}

/**
 * SearchProject cerca testo nel progetto; si annulla con la promise frontend.
 */
export function SearchProject(query: goide$0.SearchQuery): $CancellablePromise<goide$0.SearchResult> {
    return $Call.ByID(1135993643, query).then(($result: any) => {
        return $$createType117($result);
    });
}

/**
 * SecurityScan analizza offline i file del progetto: segreti e regole statiche di sicurezza.
 */
export function SecurityScan(sessionID: string): $CancellablePromise<goide$0.SecurityReport> {
    return $Call.ByID(1068563901, sessionID).then(($result: any) => {
        return $$createType118($result);
    });
}

/**
 * SelectFolder apre il selettore nativo di cartelle con il titolo indicato, senza leggerne il contenuto.
 */
export function SelectFolder(title: string): $CancellablePromise<string> {
    return $Call.ByID(1993964242, title);
}

/**
 * SelectInstalledToolchain seleziona la versione Go attiva per una sessione.
 */
export function SelectInstalledToolchain(sessionID: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(3427206935, sessionID, version);
}

/**
 * SelectProjectFolder apre il selettore nativo senza leggere o eseguire il progetto scelto.
 */
export function SelectProjectFolder(): $CancellablePromise<string> {
    return $Call.ByID(3601889087);
}

/**
 * SelectProjectParent apre il selettore nativo per la cartella che conterrà un nuovo progetto.
 */
export function SelectProjectParent(): $CancellablePromise<string> {
    return $Call.ByID(1230841363);
}

/**
 * SemanticTokens restituisce i token semantici del buffer, da decodificare con la legenda di gopls.
 */
export function SemanticTokens(sessionID: string, documentID: string): $CancellablePromise<goide$0.SemanticTokensResult> {
    return $Call.ByID(330697916, sessionID, documentID).then(($result: any) => {
        return $$createType119($result);
    });
}

/**
 * SetAIProjectPolicy scrive .adomnia/ai-policy.json (o lo rimuove per "allowed").
 */
export function SetAIProjectPolicy(sessionID: string, policy: string): $CancellablePromise<void> {
    return $Call.ByID(517329711, sessionID, policy);
}

/**
 * SetActiveStudioWorkspace cambia il workspace Go Studio mostrato.
 */
export function SetActiveStudioWorkspace(id: string): $CancellablePromise<goide$0.StudioWorkspaces> {
    return $Call.ByID(2133194987, id).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SetBreakpoints sostituisce i breakpoint di un file (con condizione, hit count o logpoint) e li applica alle sessioni attive.
 */
export function SetBreakpoints(sessionID: string, relativePath: string, breakpoints: goide$0.Breakpoint[]): $CancellablePromise<goide$0.BreakpointState[]> {
    return $Call.ByID(914916034, sessionID, relativePath, breakpoints).then(($result: any) => {
        return $$createType121($result);
    });
}

/**
 * SetDirtyDocumentCount sincronizza il solo conteggio dei buffer dirty per la chiusura sicura.
 */
export function SetDirtyDocumentCount(count: number): $CancellablePromise<void> {
    return $Call.ByID(1440994110, count);
}

/**
 * SetFunctionBreakpoints sostituisce i breakpoint di funzione e il panic breakpoint del progetto.
 */
export function SetFunctionBreakpoints(sessionID: string, settings: goide$0.FunctionBreakpointSettings): $CancellablePromise<goide$0.FunctionBreakpointsView> {
    return $Call.ByID(2389738046, sessionID, settings).then(($result: any) => {
        return $$createType73($result);
    });
}

/**
 * SetSonarToken memorizza il token SonarQube in memoria per la sessione (mai persistito).
 */
export function SetSonarToken(sessionID: string, token: string): $CancellablePromise<void> {
    return $Call.ByID(92166362, sessionID, token);
}

/**
 * SetToolAuthorization registra il consenso esplicito all'uso degli strumenti.
 */
export function SetToolAuthorization(id: string, allowed: boolean): $CancellablePromise<goide$0.Session> {
    return $Call.ByID(2669830333, id, allowed).then(($result: any) => {
        return $$createType49($result);
    });
}

/**
 * SetWindowDirtyDocumentCount sincronizza i buffer non salvati di una finestra separata.
 */
export function SetWindowDirtyDocumentCount(windowID: string, count: number): $CancellablePromise<void> {
    return $Call.ByID(3144847090, windowID, count);
}

/**
 * SignatureHelp restituisce la firma della chiamata in corso.
 */
export function SignatureHelp(sessionID: string, documentID: string, line: number, column: number): $CancellablePromise<goide$0.SignatureResult> {
    return $Call.ByID(4264674347, sessionID, documentID, line, column).then(($result: any) => {
        return $$createType122($result);
    });
}

/**
 * SonarConfigFor restituisce la configurazione SonarQube (senza token) della sessione.
 */
export function SonarConfigFor(sessionID: string): $CancellablePromise<goide$0.SonarConfig> {
    return $Call.ByID(4113315866, sessionID).then(($result: any) => {
        return $$createType116($result);
    });
}

/**
 * StartConfiguredBuild compila una configurazione con tutti i suoi parametri.
 */
export function StartConfiguredBuild(sessionID: string, configID: string): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(1484067834, sessionID, configID).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * StartConfiguredRun avvia una configurazione salvata con i soli segreti forniti a runtime.
 */
export function StartConfiguredRun(sessionID: string, configID: string, secrets: { [_ in string]?: string }): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(3106256291, sessionID, configID, secrets).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * StartDebug avvia una sessione Delve per un programma o un singolo test.
 */
export function StartDebug(request: goide$0.DebugRequest): $CancellablePromise<goide$0.DebugSessionInfo> {
    return $Call.ByID(1614658301, request).then(($result: any) => {
        return $$createType68($result);
    });
}

/**
 * StartDependencyAction applica un go get strutturato dopo conferma esplicita.
 */
export function StartDependencyAction(request: goide$0.DependencyActionRequest): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(967215541, request).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * StartGoTool esegue un comando Go Tools nella Run console.
 */
export function StartGoTool(request: goide$0.GoToolRequest): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(2792217714, request).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * StartLanguageServer avvia gopls per un progetto autorizzato.
 */
export function StartLanguageServer(sessionID: string, settings: goide$0.LanguageServerSettings): $CancellablePromise<goide$0.LanguageServerStatus> {
    return $Call.ByID(4117124675, sessionID, settings).then(($result: any) => {
        return $$createType54($result);
    });
}

/**
 * StartRun avvia una build, run o tidy con argomenti strutturati.
 */
export function StartRun(request: goide$0.RunRequest): $CancellablePromise<goide$0.Execution> {
    return $Call.ByID(39043755, request).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * StartTests avvia go test -json; l'albero dei risultati arriva con gli eventi tests.updated.
 */
export function StartTests(request: goide$0.TestRunRequest): $CancellablePromise<goide$0.TestRunSnapshot> {
    return $Call.ByID(224644795, request).then(($result: any) => {
        return $$createType56($result);
    });
}

/**
 * StopDebug termina la sessione di debug e il processo debuggato.
 */
export function StopDebug(debugID: string): $CancellablePromise<void> {
    return $Call.ByID(3344693341, debugID);
}

/**
 * StopLanguageServer arresta gopls della sessione.
 */
export function StopLanguageServer(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1458921699, sessionID);
}

/**
 * StopRun arresta in modo idempotente l'esecuzione indicata.
 */
export function StopRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(51057931, runID);
}

/**
 * SuppressSecurityFinding sopprime un finding con motivazione (salvata in .adomnia/security.json).
 */
export function SuppressSecurityFinding(sessionID: string, finding: goide$0.SecurityFinding, reason: string): $CancellablePromise<void> {
    return $Call.ByID(648830544, sessionID, finding, reason);
}

/**
 * TestModuleRegistry prova il primo GOPROXY della sessione (registry interno) con proxy, CA e credenziali.
 */
export function TestModuleRegistry(sessionID: string): $CancellablePromise<goide$0.ModuleRegistryCheck> {
    return $Call.ByID(2927291149, sessionID).then(($result: any) => {
        return $$createType123($result);
    });
}

/**
 * ToolchainSettings restituisce la toolchain del progetto e quella globale.
 */
export function ToolchainSettings(sessionID: string): $CancellablePromise<goide$0.ToolchainSettings> {
    return $Call.ByID(1885808392, sessionID).then(($result: any) => {
        return $$createType124($result);
    });
}

/**
 * UnsuppressSecurityFinding toglie una soppressione registrata dal pannello.
 */
export function UnsuppressSecurityFinding(sessionID: string, fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(2361477017, sessionID, fingerprint);
}

/**
 * UpdateDocumentBuffer sincronizza il buffer non salvato con gopls.
 */
export function UpdateDocumentBuffer(sessionID: string, documentID: string, version: number, text: string): $CancellablePromise<void> {
    return $Call.ByID(2805297400, sessionID, documentID, version, text);
}

/**
 * UpdateGoWork porta go.work all'insieme di moduli indicato con i comandi go work ufficiali.
 */
export function UpdateGoWork(sessionID: string, directories: string[]): $CancellablePromise<goide$0.GoWorkState> {
    return $Call.ByID(4284869580, sessionID, directories).then(($result: any) => {
        return $$createType57($result);
    });
}

/**
 * UseGlobalToolchain riporta il progetto alla toolchain globale.
 */
export function UseGlobalToolchain(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(163372401, sessionID);
}

/**
 * VCSBlame restituisce autore e commit di ogni riga del file.
 */
export function VCSBlame(sessionID: string, relativePath: string): $CancellablePromise<goide$0.VCSBlameLine[]> {
    return $Call.ByID(3401291297, sessionID, relativePath).then(($result: any) => {
        return $$createType126($result);
    });
}

/**
 * VCSChangedSymbols elenca le dichiarazioni Go aggiunte, modificate o rimosse rispetto a HEAD.
 */
export function VCSChangedSymbols(sessionID: string): $CancellablePromise<goide$0.VCSChangedSymbol[]> {
    return $Call.ByID(2852524783, sessionID).then(($result: any) => {
        return $$createType128($result);
    });
}

/**
 * VCSCheckout passa a un branch locale esistente.
 */
export function VCSCheckout(sessionID: string, branch: string): $CancellablePromise<void> {
    return $Call.ByID(2273218222, sessionID, branch);
}

/**
 * VCSCommitFiles registra solo i file indicati.
 */
export function VCSCommitFiles(sessionID: string, message: string, relativePaths: string[]): $CancellablePromise<git$0.CommitResult> {
    return $Call.ByID(2017164414, sessionID, message, relativePaths).then(($result: any) => {
        return $$createType129($result);
    });
}

/**
 * VCSFileAtRevision restituisce il file a una revisione (HEAD per il gutter diff).
 */
export function VCSFileAtRevision(sessionID: string, relativePath: string, revision: string): $CancellablePromise<string> {
    return $Call.ByID(963280428, sessionID, relativePath, revision);
}

/**
 * VCSFileHistory elenca i commit che hanno toccato il file.
 */
export function VCSFileHistory(sessionID: string, relativePath: string): $CancellablePromise<goide$0.VCSCommit[]> {
    return $Call.ByID(4154237980, sessionID, relativePath).then(($result: any) => {
        return $$createType131($result);
    });
}

/**
 * VCSLineHistory elenca i commit che hanno modificato le righe start..end del file.
 */
export function VCSLineHistory(sessionID: string, relativePath: string, start: number, end: number): $CancellablePromise<goide$0.VCSCommit[]> {
    return $Call.ByID(3679175152, sessionID, relativePath, start, end).then(($result: any) => {
        return $$createType131($result);
    });
}

/**
 * VCSPatchLines restituisce le righe Go aggiunte o modificate dal merge-base con base.
 */
export function VCSPatchLines(sessionID: string, base: string): $CancellablePromise<{ [_ in string]?: git$0.LineRange[] }> {
    return $Call.ByID(447699899, sessionID, base).then(($result: any) => {
        return $$createType134($result);
    });
}

/**
 * VCSStatus legge branch e modifiche del repository Git del progetto, senza operazioni di rete.
 */
export function VCSStatus(sessionID: string): $CancellablePromise<goide$0.VCSStatus> {
    return $Call.ByID(2262380148, sessionID).then(($result: any) => {
        return $$createType135($result);
    });
}

/**
 * VCSWorkingDiff restituisce un file in HEAD e su disco, per il diff nel dialog di commit.
 */
export function VCSWorkingDiff(sessionID: string, relativePath: string): $CancellablePromise<goide$0.VCSWorkingDiff> {
    return $Call.ByID(4260236086, sessionID, relativePath).then(($result: any) => {
        return $$createType136($result);
    });
}

/**
 * VulnerabilityScan esegue govulncheck con percorsi di chiamata, versione corretta e catena di dipendenze.
 */
export function VulnerabilityScan(sessionID: string, moduleDirectory: string): $CancellablePromise<goide$0.VulnReport> {
    return $Call.ByID(416955177, sessionID, moduleDirectory).then(($result: any) => {
        return $$createType137($result);
    });
}

/**
 * WatcherStatus indica se il progetto è osservato per intero o solo in parte.
 */
export function WatcherStatus(sessionID: string): $CancellablePromise<goide$0.WatcherStatus> {
    return $Call.ByID(999645628, sessionID).then(($result: any) => {
        return $$createType138($result);
    });
}

/**
 * WorkspaceModuleGraph restituisce le dipendenze tra i moduli del progetto, lette dai go.mod.
 */
export function WorkspaceModuleGraph(sessionID: string): $CancellablePromise<goide$0.WorkspaceModule[]> {
    return $Call.ByID(368877389, sessionID).then(($result: any) => {
        return $$createType140($result);
    });
}

/**
 * WorkspaceSymbols cerca simboli nel workspace.
 */
export function WorkspaceSymbols(sessionID: string, query: string): $CancellablePromise<goide$0.WorkspaceSymbol[]> {
    return $Call.ByID(3951183568, sessionID, query).then(($result: any) => {
        return $$createType142($result);
    });
}

/**
 * WriteRunInput invia input alla console dell'esecuzione indicata.
 */
export function WriteRunInput(runID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(3248513382, runID, text);
}

/**
 * WriteTerminal inoltra l'input dell'utente alla shell indicata.
 */
export function WriteTerminal(terminalID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3103928745, terminalID, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = goide$0.ArchitectureResult.createFrom;
const $$createType2 = goide$0.ErrorHandlingReport.createFrom;
const $$createType3 = goide$0.BaseCoverage.createFrom;
const $$createType4 = goide$0.ProfileFile.createFrom;
const $$createType5 = goide$0.WorkspaceChange.createFrom;
const $$createType6 = goide$0.DocumentDiskState.createFrom;
const $$createType7 = goide$0.SessionWindow.createFrom;
const $$createType8 = goide$0.CodeActionEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = goide$0.CompletionResult.createFrom;
const $$createType11 = goide$0.CrashStatus.createFrom;
const $$createType12 = goide$0.CreateProjectResult.createFrom;
const $$createType13 = goide$0.StudioWorkspaces.createFrom;
const $$createType14 = dap$0.DebugInstruction.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = dap$0.EvaluateResult.createFrom;
const $$createType17 = golang$0.GoroutineCreation.createFrom;
const $$createType18 = golang$0.GoroutineOverview.createFrom;
const $$createType19 = golang$0.PendingDefer.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = golang$0.DebugMemory.createFrom;
const $$createType22 = dap$0.DebugScope.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = dap$0.DebugFrame.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = dap$0.DebugThread.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = dap$0.DebugVariable.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = goide$0.DependencyGraphReport.createFrom;
const $$createType31 = goide$0.DependencyUpdate.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = goide$0.DependencyVulnerability.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = golang$0.DelveInfo.createFrom;
const $$createType36 = goide$0.GoToolInfo.createFrom;
const $$createType37 = golang$0.GoplsInfo.createFrom;
const $$createType38 = goide$0.LinterInfo.createFrom;
const $$createType39 = goide$0.MakeInfo.createFrom;
const $$createType40 = goide$0.SonarScannerInfo.createFrom;
const $$createType41 = golang$0.ToolchainInfo.createFrom;
const $$createType42 = goide$0.HighlightsResult.createFrom;
const $$createType43 = goide$0.DocumentSymbolsResult.createFrom;
const $$createType44 = goide$0.DocumentationReport.createFrom;
const $$createType45 = goide$0.RunConfiguration.createFrom;
const $$createType46 = goide$0.HierarchyItem.createFrom;
const $$createType47 = $Create.Array($$createType46);
const $$createType48 = goide$0.SonarScanResult.createFrom;
const $$createType49 = goide$0.Session.createFrom;
const $$createType50 = $Create.Array($$createType49);
const $$createType51 = goide$0.FormatResult.createFrom;
const $$createType52 = goide$0.CodeGenResult.createFrom;
const $$createType53 = goide$0.Capabilities.createFrom;
const $$createType54 = goide$0.LanguageServerStatus.createFrom;
const $$createType55 = goide$0.SessionView.createFrom;
const $$createType56 = goide$0.TestRunSnapshot.createFrom;
const $$createType57 = goide$0.GoWorkState.createFrom;
const $$createType58 = goide$0.HoverResult.createFrom;
const $$createType59 = goide$0.ImplementationMarker.createFrom;
const $$createType60 = $Create.Array($$createType59);
const $$createType61 = goide$0.InlayHintsResult.createFrom;
const $$createType62 = run$0.Execution.createFrom;
const $$createType63 = golang$0.ToolchainInstallation.createFrom;
const $$createType64 = goide$0.ProcessDescriptor.createFrom;
const $$createType65 = $Create.Array($$createType64);
const $$createType66 = dap$0.FileBreakpoints.createFrom;
const $$createType67 = $Create.Array($$createType66);
const $$createType68 = dap$0.DebugSessionInfo.createFrom;
const $$createType69 = $Create.Array($$createType68);
const $$createType70 = goide$0.DependencyState.createFrom;
const $$createType71 = goide$0.FileEntry.createFrom;
const $$createType72 = $Create.Array($$createType71);
const $$createType73 = dap$0.FunctionBreakpointsView.createFrom;
const $$createType74 = goide$0.FuzzTarget.createFrom;
const $$createType75 = $Create.Array($$createType74);
const $$createType76 = golang$0.InstalledToolchain.createFrom;
const $$createType77 = $Create.Array($$createType76);
const $$createType78 = goide$0.HistoryRevision.createFrom;
const $$createType79 = $Create.Array($$createType78);
const $$createType80 = goide$0.ProcessInfo.createFrom;
const $$createType81 = $Create.Array($$createType80);
const $$createType82 = $Create.Array($$createType4);
const $$createType83 = goide$0.ProjectTemplateList.createFrom;
const $$createType84 = goide$0.RecentProject.createFrom;
const $$createType85 = $Create.Array($$createType84);
const $$createType86 = goide$0.RecoveredBuffer.createFrom;
const $$createType87 = $Create.Array($$createType86);
const $$createType88 = remote$0.Target.createFrom;
const $$createType89 = $Create.Array($$createType88);
const $$createType90 = $Create.Array($$createType45);
const $$createType91 = $Create.Array($$createType62);
const $$createType92 = $Create.Array($$createType7);
const $$createType93 = goide$0.TerminalProfile.createFrom;
const $$createType94 = $Create.Array($$createType93);
const $$createType95 = goide$0.TerminalSession.createFrom;
const $$createType96 = $Create.Array($$createType95);
const $$createType97 = $Create.Array($$createType56);
const $$createType98 = golang$0.ToolchainRelease.createFrom;
const $$createType99 = $Create.Array($$createType98);
const $$createType100 = goide$0.ProfileReport.createFrom;
const $$createType101 = goide$0.TraceReport.createFrom;
const $$createType102 = goide$0.EditorLocation.createFrom;
const $$createType103 = $Create.Array($$createType102);
const $$createType104 = goide$0.OpenDocument.createFrom;
const $$createType105 = goide$0.RenameTarget.createFrom;
const $$createType106 = goide$0.GoToolPreview.createFrom;
const $$createType107 = goide$0.PrivateRepoCredential.createFrom;
const $$createType108 = goide$0.ProjectService.createFrom;
const $$createType109 = $Create.Array($$createType108);
const $$createType110 = goide$0.QuickDefinitionResult.createFrom;
const $$createType111 = goide$0.QuickOpenResult.createFrom;
const $$createType112 = $Create.Array($$createType111);
const $$createType113 = goide$0.FuzzInputContent.createFrom;
const $$createType114 = goide$0.RecursiveCallsResult.createFrom;
const $$createType115 = goide$0.LintResult.createFrom;
const $$createType116 = goide$0.SonarConfig.createFrom;
const $$createType117 = goide$0.SearchResult.createFrom;
const $$createType118 = security$0.Report.createFrom;
const $$createType119 = goide$0.SemanticTokensResult.createFrom;
const $$createType120 = dap$0.BreakpointState.createFrom;
const $$createType121 = $Create.Array($$createType120);
const $$createType122 = goide$0.SignatureResult.createFrom;
const $$createType123 = goide$0.ModuleRegistryCheck.createFrom;
const $$createType124 = golang$0.ToolchainSettings.createFrom;
const $$createType125 = goide$0.VCSBlameLine.createFrom;
const $$createType126 = $Create.Array($$createType125);
const $$createType127 = goide$0.VCSChangedSymbol.createFrom;
const $$createType128 = $Create.Array($$createType127);
const $$createType129 = git$0.CommitResult.createFrom;
const $$createType130 = goide$0.VCSCommit.createFrom;
const $$createType131 = $Create.Array($$createType130);
const $$createType132 = git$0.LineRange.createFrom;
const $$createType133 = $Create.Array($$createType132);
const $$createType134 = $Create.Map($Create.Any, $$createType133);
const $$createType135 = goide$0.VCSStatus.createFrom;
const $$createType136 = goide$0.VCSWorkingDiff.createFrom;
const $$createType137 = goide$0.VulnReport.createFrom;
const $$createType138 = goide$0.WatcherStatus.createFrom;
const $$createType139 = goide$0.WorkspaceModule.createFrom;
const $$createType140 = $Create.Array($$createType139);
const $$createType141 = goide$0.WorkspaceSymbol.createFrom;
const $$createType142 = $Create.Array($$createType141);
