// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as goide$0 from "./internal/goide/models.js";

/**
 * CloseSession chiude una sessione senza modificare la cartella del progetto.
 */
export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1493129442, id);
}

/**
 * GetCapabilities restituisce soltanto le capacità Go Studio realmente disponibili.
 */
export function GetCapabilities(): $CancellablePromise<goide$0.Capabilities> {
    return $Call.ByID(1829330672).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListSessions restituisce le sessioni Go Studio correnti e ripristinate.
 */
export function ListSessions(): $CancellablePromise<goide$0.Session[]> {
    return $Call.ByID(1758091587).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenProject registra una cartella locale senza avviarne codice o strumenti.
 */
export function OpenProject(path: string): $CancellablePromise<goide$0.Session> {
    return $Call.ByID(1300673995, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SelectProjectFolder apre il selettore nativo senza leggere o eseguire il progetto scelto.
 */
export function SelectProjectFolder(): $CancellablePromise<string> {
    return $Call.ByID(3601889087);
}

/**
 * SetToolAuthorization registra il consenso esplicito all'uso degli strumenti.
 */
export function SetToolAuthorization(id: string, allowed: boolean): $CancellablePromise<goide$0.Session> {
    return $Call.ByID(2669830333, id, allowed).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = goide$0.Capabilities.createFrom;
const $$createType1 = goide$0.Session.createFrom;
const $$createType2 = $Create.Array($$createType1);
