// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function CallTool(name: string, argsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(1351223311, name, argsJSON);
}

export function CallToolSession(sessionID: string, name: string, argsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(1201945753, sessionID, name, argsJSON);
}

export function Connect(cfgJSON: string): $CancellablePromise<string> {
    return $Call.ByID(2140199021, cfgJSON);
}

export function ConnectSession(sessionID: string, cfgJSON: string): $CancellablePromise<string> {
    return $Call.ByID(4159324383, sessionID, cfgJSON);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(1123379695);
}

export function DisconnectSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(1289300665, sessionID);
}

export function GetPrompt(name: string, argsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(172204409, name, argsJSON);
}

export function GetPromptSession(sessionID: string, name: string, argsJSON: string): $CancellablePromise<string> {
    return $Call.ByID(266248091, sessionID, name, argsJSON);
}

export function GetSessionStatus(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(743273615, sessionID);
}

export function ListPrompts(): $CancellablePromise<string> {
    return $Call.ByID(603720152);
}

export function ListPromptsSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2486993412, sessionID);
}

export function ListResources(): $CancellablePromise<string> {
    return $Call.ByID(2402412914);
}

export function ListResourcesSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(125983766, sessionID);
}

export function ListSessions(): $CancellablePromise<string> {
    return $Call.ByID(3117978700);
}

export function ListTools(): $CancellablePromise<string> {
    return $Call.ByID(2810885852);
}

export function ListToolsSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(1024255160, sessionID);
}

export function RestartSession(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(2989468636, sessionID);
}
