// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Milk espone a React l'integrazione milk di Go Studio. La logica vive in internal/milk.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as milk$0 from "./internal/milk/models.js";

/**
 * CancelPrompt interrompe il turno individuando la sessione dal token.
 */
export function CancelPrompt(token: string): $CancellablePromise<void> {
    return $Call.ByID(2755088225, token);
}

/**
 * CancelSession interrompe il turno in corso su una sessione.
 */
export function CancelSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3277396013, sessionID);
}

/**
 * Log restituisce le ultime righe di log del processo.
 */
export function Log(): $CancellablePromise<string[]> {
    return $Call.ByID(657099561).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Prompt invia un turno di chat. I delta arrivano come evento milk.chat.
 */
export function Prompt(request: milk$0.PromptRequest): $CancellablePromise<milk$0.PromptResponse> {
    return $Call.ByID(1998047459, request).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResetSession fa ripartire da zero la conversazione milk di un progetto.
 */
export function ResetSession(root: string): $CancellablePromise<void> {
    return $Call.ByID(556429796, root);
}

/**
 * RespondPermission risponde a una richiesta di autorizzazione tool.
 */
export function RespondPermission(requestID: string, allow: boolean): $CancellablePromise<void> {
    return $Call.ByID(3348645969, requestID, allow);
}

/**
 * Restart riavvia il processo azzerando il contatore dei crash.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2435796996);
}

/**
 * SaveSettings valida, salva e applica la configurazione.
 */
export function SaveSettings(settings: milk$0.Settings): $CancellablePromise<milk$0.Settings> {
    return $Call.ByID(4063823965, settings).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetActiveWorkspace comunica il progetto attivo in Go Studio.
 */
export function SetActiveWorkspace(root: string): $CancellablePromise<void> {
    return $Call.ByID(1269283718, root);
}

/**
 * Settings restituisce la configurazione. Mai credenziali.
 */
export function Settings(): $CancellablePromise<milk$0.Settings> {
    return $Call.ByID(3002270608).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Status restituisce lo stato corrente dell'integrazione.
 */
export function Status(): $CancellablePromise<milk$0.Status> {
    return $Call.ByID(3201629911).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = milk$0.PromptResponse.createFrom;
const $$createType2 = milk$0.Settings.createFrom;
const $$createType3 = milk$0.Status.createFrom;
