// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LogFileEntry represents a log file in the logs directory.
 */
export class LogFileEntry {
    "name": string;
    "size": number;
    "modTime": string;

    /** Creates a new LogFileEntry instance. */
    constructor($$source: Partial<LogFileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFileEntry($$parsedSource as Partial<LogFileEntry>);
    }
}

export class StorageEntry {
    "bucket": string;
    "key": string;
    "value": string;

    /** Creates a new StorageEntry instance. */
    constructor($$source: Partial<StorageEntry> = {}) {
        if (!("bucket" in $$source)) {
            this["bucket"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): StorageEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageEntry($$parsedSource as Partial<StorageEntry>);
    }
}

/**
 * UpdateInfo is the trimmed shape the UI needs.
 */
export class UpdateInfo {
    "currentVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "releaseUrl": string;
    "releaseNotes": string;
    "publishedAt": string;

    /**
     * running unversioned dev build; check skipped
     */
    "isDev": boolean;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            this["updateAvailable"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("isDev" in $$source)) {
            this["isDev"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
