// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * GitHubProfile è un account GitHub configurato. Non contiene mai token: le credenziali restano
 * nell'archivio del Copilot Language Server, adOmnia salva solo host e nome.
 */
export class GitHubProfile {
    "id": string;
    "name": string;
    "type": ProfileType;
    "host": string;

    /** Creates a new GitHubProfile instance. */
    constructor($$source: Partial<GitHubProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ProfileType.$zero;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitHubProfile($$parsedSource as Partial<GitHubProfile>);
    }
}

/**
 * InlineCompletionItem è un suggerimento in coordinate Monaco. Raw va restituito così com'è per
 * la telemetria di visualizzazione e accettazione richiesta dal server.
 */
export class InlineCompletionItem {
    "insertText": string;
    "startLine": number;
    "startColumn": number;
    "endLine": number;
    "endColumn": number;
    "raw": json$0.RawMessage;

    /** Creates a new InlineCompletionItem instance. */
    constructor($$source: Partial<InlineCompletionItem> = {}) {
        if (!("insertText" in $$source)) {
            this["insertText"] = "";
        }
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("startColumn" in $$source)) {
            this["startColumn"] = 0;
        }
        if (!("endLine" in $$source)) {
            this["endLine"] = 0;
        }
        if (!("endColumn" in $$source)) {
            this["endColumn"] = 0;
        }
        if (!("raw" in $$source)) {
            this["raw"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InlineCompletionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): InlineCompletionItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InlineCompletionItem($$parsedSource as Partial<InlineCompletionItem>);
    }
}

/**
 * InlineCompletionRequest usa posizioni Monaco (1-based, UTF-16), come il resto di gO Studio.
 */
export class InlineCompletionRequest {
    "documentId": string;
    "version": number;
    "line": number;
    "column": number;
    "tabSize": number;
    "insertSpaces": boolean;

    /**
     * Automatic distingue la digitazione (Automatic) dalla richiesta esplicita (Alt+\).
     */
    "automatic": boolean;

    /** Creates a new InlineCompletionRequest instance. */
    constructor($$source: Partial<InlineCompletionRequest> = {}) {
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("tabSize" in $$source)) {
            this["tabSize"] = 0;
        }
        if (!("insertSpaces" in $$source)) {
            this["insertSpaces"] = false;
        }
        if (!("automatic" in $$source)) {
            this["automatic"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InlineCompletionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InlineCompletionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InlineCompletionRequest($$parsedSource as Partial<InlineCompletionRequest>);
    }
}

/**
 * ProfileType distingue le tre famiglie di GitHub, che hanno capability diverse.
 */
export enum ProfileType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ProfileDotCom è github.com.
     */
    ProfileDotCom = "github.com",

    /**
     * ProfileEnterpriseCloud è GitHub Enterprise Cloud con residenza dati (*.ghe.com).
     */
    ProfileEnterpriseCloud = "ghe.com",

    /**
     * ProfileEnterpriseServer è GitHub Enterprise Server on-premise (qualsiasi altro host).
     */
    ProfileEnterpriseServer = "ghes",
};

/**
 * ProxySettings è il proxy HTTP aziendale passato al Language Server; vuoto = proxy di sistema.
 */
export class ProxySettings {
    "url": string;
    "strictSSL": boolean;

    /** Creates a new ProxySettings instance. */
    constructor($$source: Partial<ProxySettings> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("strictSSL" in $$source)) {
            this["strictSSL"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxySettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxySettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxySettings($$parsedSource as Partial<ProxySettings>);
    }
}

/**
 * ServerBinary descrive il Language Server che verrà avviato.
 */
export class ServerBinary {
    "path": string;
    "version": string;

    /**
     * Source: "custom" (impostazioni), "managed" (installato da adOmnia) o "path" (PATH di sistema).
     */
    "source": string;

    /** Creates a new ServerBinary instance. */
    constructor($$source: Partial<ServerBinary> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerBinary instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerBinary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerBinary($$parsedSource as Partial<ServerBinary>);
    }
}

/**
 * Settings è la configurazione Copilot di adOmnia. Non contiene segreti: il token resta nell'archivio
 * del Copilot Language Server.
 */
export class Settings {
    "enabled": boolean;
    "inlineCompletion": boolean;
    "activeProfileId": string;
    "profiles": GitHubProfile[];

    /**
     * WorkspaceProfiles associa la radice di un progetto al profilo da usare, per non usare per
     * sbaglio l'account personale su codice aziendale.
     */
    "workspaceProfiles": { [_ in string]?: string };
    "proxy": ProxySettings;

    /**
     * CABundlePath aggiunge un bundle PEM di CA aziendali (TLS inspection) ai certificati di sistema.
     */
    "caBundlePath": string;

    /**
     * BinaryPath usa un Language Server installato a mano invece di quello gestito da adOmnia.
     */
    "binaryPath": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("inlineCompletion" in $$source)) {
            this["inlineCompletion"] = false;
        }
        if (!("activeProfileId" in $$source)) {
            this["activeProfileId"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }
        if (!("workspaceProfiles" in $$source)) {
            this["workspaceProfiles"] = {};
        }
        if (!("proxy" in $$source)) {
            this["proxy"] = (new ProxySettings());
        }
        if (!("caBundlePath" in $$source)) {
            this["caBundlePath"] = "";
        }
        if (!("binaryPath" in $$source)) {
            this["binaryPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField3_0($$parsedSource["profiles"]);
        }
        if ("workspaceProfiles" in $$parsedSource) {
            $$parsedSource["workspaceProfiles"] = $$createField4_0($$parsedSource["workspaceProfiles"]);
        }
        if ("proxy" in $$parsedSource) {
            $$parsedSource["proxy"] = $$createField5_0($$parsedSource["proxy"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * SignInPrompt è il codice del device flow da mostrare all'utente.
 */
export class SignInPrompt {
    "status": string;
    "userCode"?: string;
    "verificationUri"?: string;
    "user"?: string;
    "host": string;

    /** Creates a new SignInPrompt instance. */
    constructor($$source: Partial<SignInPrompt> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignInPrompt instance from a string or object.
     */
    static createFrom($$source: any = {}): SignInPrompt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SignInPrompt($$parsedSource as Partial<SignInPrompt>);
    }
}

/**
 * State è lo stato dell'integrazione mostrato nella status bar.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateDisabled = "disabled",
    StateNotInstalled = "not-installed",
    StateInstalling = "installing",
    StateStarting = "starting",
    StateSignedOut = "signed-out",
    StateReady = "ready",
    StateWarning = "warning",
    StateUnauthorized = "unauthorized",
    StateError = "error",
};

/**
 * Status è lo stato pubblicato al frontend. Contiene sempre il profilo, così l'host è visibile.
 */
export class Status {
    "state": State;
    "message"?: string;
    "busy": boolean;
    "user"?: string;
    "profile": GitHubProfile;
    "binary": ServerBinary;
    "serverVersion"?: string;
    "inlineCompletion": boolean;
    "restarts": number;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("busy" in $$source)) {
            this["busy"] = false;
        }
        if (!("profile" in $$source)) {
            this["profile"] = (new GitHubProfile());
        }
        if (!("binary" in $$source)) {
            this["binary"] = (new ServerBinary());
        }
        if (!("inlineCompletion" in $$source)) {
            this["inlineCompletion"] = false;
        }
        if (!("restarts" in $$source)) {
            this["restarts"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField4_0($$parsedSource["profile"]);
        }
        if ("binary" in $$parsedSource) {
            $$parsedSource["binary"] = $$createField5_0($$parsedSource["binary"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = GitHubProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = ProxySettings.createFrom;
const $$createType4 = ServerBinary.createFrom;
