// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Enum {
    "name": string;
    "doc"?: string;
    "line": number;
    "values": EnumValue[];

    /** Creates a new Enum instance. */
    constructor($$source: Partial<Enum> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Enum instance from a string or object.
     */
    static createFrom($$source: any = {}): Enum {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField3_0($$parsedSource["values"]);
        }
        return new Enum($$parsedSource as Partial<Enum>);
    }
}

export class EnumValue {
    "name": string;
    "number": number;
    "doc"?: string;

    /** Creates a new EnumValue instance. */
    constructor($$source: Partial<EnumValue> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnumValue instance from a string or object.
     */
    static createFrom($$source: any = {}): EnumValue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnumValue($$parsedSource as Partial<EnumValue>);
    }
}

export class Field {
    "name": string;
    "number": number;
    "type": string;
    "label"?: string;
    "doc"?: string;

    /** Creates a new Field instance. */
    constructor($$source: Partial<Field> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Field instance from a string or object.
     */
    static createFrom($$source: any = {}): Field {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Field($$parsedSource as Partial<Field>);
    }
}

/**
 * File è la documentazione di un file .proto (Error se non è stato possibile leggerlo).
 */
export class File {
    "path": string;
    "package"?: string;
    "syntax"?: string;
    "doc"?: string;
    "services": Service[];
    "messages": Message[];
    "enums": Enum[];
    "error"?: string;

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("services" in $$source)) {
            this["services"] = [];
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("enums" in $$source)) {
            this["enums"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType5;
        const $$createField6_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField4_0($$parsedSource["services"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField5_0($$parsedSource["messages"]);
        }
        if ("enums" in $$parsedSource) {
            $$parsedSource["enums"] = $$createField6_0($$parsedSource["enums"]);
        }
        return new File($$parsedSource as Partial<File>);
    }
}

export class Message {
    "name": string;
    "doc"?: string;
    "line": number;
    "fields": Field[];

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField3_0($$parsedSource["fields"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class Method {
    "name": string;
    "doc"?: string;
    "line": number;
    "input": string;
    "output": string;
    "clientStreaming"?: boolean;
    "serverStreaming"?: boolean;

    /** Creates a new Method instance. */
    constructor($$source: Partial<Method> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Method instance from a string or object.
     */
    static createFrom($$source: any = {}): Method {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Method($$parsedSource as Partial<Method>);
    }
}

export class Service {
    "name": string;
    "doc"?: string;
    "line": number;
    "methods": Method[];

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("methods" in $$source)) {
            this["methods"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("methods" in $$parsedSource) {
            $$parsedSource["methods"] = $$createField3_0($$parsedSource["methods"]);
        }
        return new Service($$parsedSource as Partial<Service>);
    }
}

// Private type creation functions
const $$createType0 = EnumValue.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Service.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Message.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = Enum.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Field.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Method.createFrom;
const $$createType11 = $Create.Array($$createType10);
