// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ContainerStatus {
    "id": string;
    "name": string;
    "image": string;
    "state": string;
    "status": string;
    "ports": string;
    "running": boolean;

    /** Creates a new ContainerStatus instance. */
    constructor($$source: Partial<ContainerStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ContainerStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContainerStatus($$parsedSource as Partial<ContainerStatus>);
    }
}

export class DockerService {
    "image": string;
    "ports": string[];
    "environment"?: { [_ in string]?: string };
    "volumes"?: string[];
    "command"?: string;
    "dependsOn"?: string[];
    "restart"?: string;
    "healthCheck"?: HealthCheck | null;
    "networks"?: string[];

    /** Creates a new DockerService instance. */
    constructor($$source: Partial<DockerService> = {}) {
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerService instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerService {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField1_0($$parsedSource["ports"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField2_0($$parsedSource["environment"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField3_0($$parsedSource["volumes"]);
        }
        if ("dependsOn" in $$parsedSource) {
            $$parsedSource["dependsOn"] = $$createField5_0($$parsedSource["dependsOn"]);
        }
        if ("healthCheck" in $$parsedSource) {
            $$parsedSource["healthCheck"] = $$createField7_0($$parsedSource["healthCheck"]);
        }
        if ("networks" in $$parsedSource) {
            $$parsedSource["networks"] = $$createField8_0($$parsedSource["networks"]);
        }
        return new DockerService($$parsedSource as Partial<DockerService>);
    }
}

export class HealthCheck {
    "test": string[];
    "interval": string;
    "timeout": string;
    "retries": number;

    /** Creates a new HealthCheck instance. */
    constructor($$source: Partial<HealthCheck> = {}) {
        if (!("test" in $$source)) {
            this["test"] = [];
        }
        if (!("interval" in $$source)) {
            this["interval"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = "";
        }
        if (!("retries" in $$source)) {
            this["retries"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthCheck instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthCheck {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("test" in $$parsedSource) {
            $$parsedSource["test"] = $$createField0_0($$parsedSource["test"]);
        }
        return new HealthCheck($$parsedSource as Partial<HealthCheck>);
    }
}

export class LabInfo {
    "projectName": string;
    "status": string;
    "configFiles": string;

    /** Creates a new LabInfo instance. */
    constructor($$source: Partial<LabInfo> = {}) {
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("configFiles" in $$source)) {
            this["configFiles"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LabInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LabInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LabInfo($$parsedSource as Partial<LabInfo>);
    }
}

export class LabOutput {
    "composeContent": string;
    "envContent": string;
    "readmeContent": string;

    /** Creates a new LabOutput instance. */
    constructor($$source: Partial<LabOutput> = {}) {
        if (!("composeContent" in $$source)) {
            this["composeContent"] = "";
        }
        if (!("envContent" in $$source)) {
            this["envContent"] = "";
        }
        if (!("readmeContent" in $$source)) {
            this["readmeContent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LabOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LabOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LabOutput($$parsedSource as Partial<LabOutput>);
    }
}

export class LabRunResult {
    "projectName": string;
    "dir": string;
    "ids": string[];
    "output": string;

    /** Creates a new LabRunResult instance. */
    constructor($$source: Partial<LabRunResult> = {}) {
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("ids" in $$source)) {
            this["ids"] = [];
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LabRunResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LabRunResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ids" in $$parsedSource) {
            $$parsedSource["ids"] = $$createField2_0($$parsedSource["ids"]);
        }
        return new LabRunResult($$parsedSource as Partial<LabRunResult>);
    }
}

export class PresetDef {
    "id": string;
    "name": string;
    "description": string;
    "tag": string;
    "services": { [_ in string]?: DockerService };
    "volumes"?: string[];
    "networks"?: string[];
    "envVars": { [_ in string]?: string };
    "readmeIntro": string;
    "readmeSteps": string[];

    /** Creates a new PresetDef instance. */
    constructor($$source: Partial<PresetDef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("services" in $$source)) {
            this["services"] = {};
        }
        if (!("envVars" in $$source)) {
            this["envVars"] = {};
        }
        if (!("readmeIntro" in $$source)) {
            this["readmeIntro"] = "";
        }
        if (!("readmeSteps" in $$source)) {
            this["readmeSteps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetDef instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetDef {
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField4_0($$parsedSource["services"]);
        }
        if ("volumes" in $$parsedSource) {
            $$parsedSource["volumes"] = $$createField5_0($$parsedSource["volumes"]);
        }
        if ("networks" in $$parsedSource) {
            $$parsedSource["networks"] = $$createField6_0($$parsedSource["networks"]);
        }
        if ("envVars" in $$parsedSource) {
            $$parsedSource["envVars"] = $$createField7_0($$parsedSource["envVars"]);
        }
        if ("readmeSteps" in $$parsedSource) {
            $$parsedSource["readmeSteps"] = $$createField9_0($$parsedSource["readmeSteps"]);
        }
        return new PresetDef($$parsedSource as Partial<PresetDef>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = HealthCheck.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = DockerService.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
