// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ContrastResult holds WCAG contrast evaluation for a text/background pair.
 */
export class ContrastResult {
    "pair": string;
    "ratio": number;
    "aaNormal": boolean;
    "aaLarge": boolean;
    "aaaNormal": boolean;
    "level": string;

    /** Creates a new ContrastResult instance. */
    constructor($$source: Partial<ContrastResult> = {}) {
        if (!("pair" in $$source)) {
            this["pair"] = "";
        }
        if (!("ratio" in $$source)) {
            this["ratio"] = 0;
        }
        if (!("aaNormal" in $$source)) {
            this["aaNormal"] = false;
        }
        if (!("aaLarge" in $$source)) {
            this["aaLarge"] = false;
        }
        if (!("aaaNormal" in $$source)) {
            this["aaaNormal"] = false;
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContrastResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ContrastResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContrastResult($$parsedSource as Partial<ContrastResult>);
    }
}

/**
 * Theme represents a complete visual theme with CSS custom property overrides.
 */
export class Theme {
    "id": string;
    "name": string;
    "author": string;
    "version": string;
    "description": string;
    "colors": { [_ in string]?: string };
    "fonts": ThemeFonts;
    "spacing": { [_ in string]?: string };
    "radii": { [_ in string]?: string };
    "shadows": { [_ in string]?: string };
    "meta": { [_ in string]?: string };
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("colors" in $$source)) {
            this["colors"] = {};
        }
        if (!("fonts" in $$source)) {
            this["fonts"] = (new ThemeFonts());
        }
        if (!("spacing" in $$source)) {
            this["spacing"] = {};
        }
        if (!("radii" in $$source)) {
            this["radii"] = {};
        }
        if (!("shadows" in $$source)) {
            this["shadows"] = {};
        }
        if (!("meta" in $$source)) {
            this["meta"] = {};
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colors" in $$parsedSource) {
            $$parsedSource["colors"] = $$createField5_0($$parsedSource["colors"]);
        }
        if ("fonts" in $$parsedSource) {
            $$parsedSource["fonts"] = $$createField6_0($$parsedSource["fonts"]);
        }
        if ("spacing" in $$parsedSource) {
            $$parsedSource["spacing"] = $$createField7_0($$parsedSource["spacing"]);
        }
        if ("radii" in $$parsedSource) {
            $$parsedSource["radii"] = $$createField8_0($$parsedSource["radii"]);
        }
        if ("shadows" in $$parsedSource) {
            $$parsedSource["shadows"] = $$createField9_0($$parsedSource["shadows"]);
        }
        if ("meta" in $$parsedSource) {
            $$parsedSource["meta"] = $$createField10_0($$parsedSource["meta"]);
        }
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

/**
 * ThemeFonts holds font family definitions for a theme.
 */
export class ThemeFonts {
    "sans": string;
    "mono": string;
    "serif": string;

    /** Creates a new ThemeFonts instance. */
    constructor($$source: Partial<ThemeFonts> = {}) {
        if (!("sans" in $$source)) {
            this["sans"] = "";
        }
        if (!("mono" in $$source)) {
            this["mono"] = "";
        }
        if (!("serif" in $$source)) {
            this["serif"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeFonts instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeFonts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeFonts($$parsedSource as Partial<ThemeFonts>);
    }
}

/**
 * ThemeValidationResult holds the outcome of validating a theme against the schema.
 */
export class ThemeValidationResult {
    "valid": boolean;
    "errors": string[];
    "warnings": string[];

    /** Creates a new ThemeValidationResult instance. */
    constructor($$source: Partial<ThemeValidationResult> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeValidationResult {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new ThemeValidationResult($$parsedSource as Partial<ThemeValidationResult>);
    }
}

/**
 * TokenDefinition describes a single design token in the schema.
 */
export class TokenDefinition {
    "key": string;
    "description": string;
    "required": boolean;
    "category": string;
    "default": string;

    /** Creates a new TokenDefinition instance. */
    constructor($$source: Partial<TokenDefinition> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): TokenDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenDefinition($$parsedSource as Partial<TokenDefinition>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ThemeFonts.createFrom;
const $$createType2 = $Create.Array($Create.Any);
