// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExecRequest describes a function call to execute in a plugin sandbox.
 */
export class ExecRequest {
    "pluginId": string;
    "function": string;
    "args": { [_ in string]?: any };

    /** Creates a new ExecRequest instance. */
    constructor($$source: Partial<ExecRequest> = {}) {
        if (!("pluginId" in $$source)) {
            this["pluginId"] = "";
        }
        if (!("function" in $$source)) {
            this["function"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecRequest {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        return new ExecRequest($$parsedSource as Partial<ExecRequest>);
    }
}

/**
 * ExecResult is the outcome of a sandbox execution.
 */
export class ExecResult {
    "success": boolean;
    "data"?: any;
    "error"?: string;
    "memUsed": number;
    "timeMs": number;

    /** Creates a new ExecResult instance. */
    constructor($$source: Partial<ExecResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("memUsed" in $$source)) {
            this["memUsed"] = 0;
        }
        if (!("timeMs" in $$source)) {
            this["timeMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecResult($$parsedSource as Partial<ExecResult>);
    }
}

/**
 * HookResult is the outcome of a hook invocation.
 */
export class HookResult {
    "modified": boolean;
    "data"?: { [_ in string]?: any };
    "error"?: string;

    /** Creates a new HookResult instance. */
    constructor($$source: Partial<HookResult> = {}) {
        if (!("modified" in $$source)) {
            this["modified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HookResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HookResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new HookResult($$parsedSource as Partial<HookResult>);
    }
}

/**
 * PluginAction defines an executable action exposed in a plugin panel.
 */
export class PluginAction {
    "id": string;
    "name": string;
    "description": string;
    "streaming": boolean;

    /** Creates a new PluginAction instance. */
    constructor($$source: Partial<PluginAction> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("streaming" in $$source)) {
            this["streaming"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginAction instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginAction($$parsedSource as Partial<PluginAction>);
    }
}

/**
 * PluginEvent carries event data through the hook system.
 */
export class PluginEvent {
    "type": string;
    "payload": { [_ in string]?: any };

    /** Creates a new PluginEvent instance. */
    constructor($$source: Partial<PluginEvent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginEvent {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField1_0($$parsedSource["payload"]);
        }
        return new PluginEvent($$parsedSource as Partial<PluginEvent>);
    }
}

/**
 * PluginHook maps an event to a handler function name in the plugin entry point.
 */
export class PluginHook {
    "event": string;
    "handler": string;

    /** Creates a new PluginHook instance. */
    constructor($$source: Partial<PluginHook> = {}) {
        if (!("event" in $$source)) {
            this["event"] = "";
        }
        if (!("handler" in $$source)) {
            this["handler"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginHook instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginHook {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginHook($$parsedSource as Partial<PluginHook>);
    }
}

/**
 * PluginInstance represents an installed plugin with its runtime state.
 */
export class PluginInstance {
    "manifest": PluginManifest;
    "enabled": boolean;
    "settings": { [_ in string]?: string };
    "installDir": string;
    "installedAt": string;
    "error"?: string;

    /** Creates a new PluginInstance instance. */
    constructor($$source: Partial<PluginInstance> = {}) {
        if (!("manifest" in $$source)) {
            this["manifest"] = (new PluginManifest());
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("settings" in $$source)) {
            this["settings"] = {};
        }
        if (!("installDir" in $$source)) {
            this["installDir"] = "";
        }
        if (!("installedAt" in $$source)) {
            this["installedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInstance instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginInstance {
        const $$createField0_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField0_0($$parsedSource["manifest"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField2_0($$parsedSource["settings"]);
        }
        return new PluginInstance($$parsedSource as Partial<PluginInstance>);
    }
}

/**
 * PluginManifest describes a plugin's metadata and capabilities.
 */
export class PluginManifest {
    "id": string;
    "name": string;
    "version": string;
    "author": string;
    "description": string;
    "homepage": string;
    "license": string;
    "minAppVersion": string;
    "runtime": string;
    "permissions": string[];
    "hooks": PluginHook[];
    "settings": PluginSetting[];
    "entryPoint": string;
    "icon": string;
    "ui_slots"?: string[];
    "actions"?: PluginAction[];

    /** Creates a new PluginManifest instance. */
    constructor($$source: Partial<PluginManifest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("license" in $$source)) {
            this["license"] = "";
        }
        if (!("minAppVersion" in $$source)) {
            this["minAppVersion"] = "";
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = "";
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = [];
        }
        if (!("hooks" in $$source)) {
            this["hooks"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = [];
        }
        if (!("entryPoint" in $$source)) {
            this["entryPoint"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginManifest instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginManifest {
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType5;
        const $$createField11_0 = $$createType7;
        const $$createField14_0 = $$createType3;
        const $$createField15_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField9_0($$parsedSource["permissions"]);
        }
        if ("hooks" in $$parsedSource) {
            $$parsedSource["hooks"] = $$createField10_0($$parsedSource["hooks"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField11_0($$parsedSource["settings"]);
        }
        if ("ui_slots" in $$parsedSource) {
            $$parsedSource["ui_slots"] = $$createField14_0($$parsedSource["ui_slots"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField15_0($$parsedSource["actions"]);
        }
        return new PluginManifest($$parsedSource as Partial<PluginManifest>);
    }
}

/**
 * PluginSandbox is an isolated execution environment for a single plugin.
 */
export class PluginSandbox {
    "pluginId": string;
    "memory": number;
    "maxMemory": number;
    "running": boolean;

    /** Creates a new PluginSandbox instance. */
    constructor($$source: Partial<PluginSandbox> = {}) {
        if (!("pluginId" in $$source)) {
            this["pluginId"] = "";
        }
        if (!("memory" in $$source)) {
            this["memory"] = 0;
        }
        if (!("maxMemory" in $$source)) {
            this["maxMemory"] = 0;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginSandbox instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginSandbox {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginSandbox($$parsedSource as Partial<PluginSandbox>);
    }
}

/**
 * PluginSetting defines a configurable setting for a plugin.
 */
export class PluginSetting {
    "key": string;
    "label": string;
    "type": string;
    "default": string;
    "options"?: string[];
    "description": string;

    /** Creates a new PluginSetting instance. */
    constructor($$source: Partial<PluginSetting> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginSetting instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginSetting {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new PluginSetting($$parsedSource as Partial<PluginSetting>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = PluginManifest.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = PluginHook.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PluginSetting.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = PluginAction.createFrom;
const $$createType9 = $Create.Array($$createType8);
