export function WindowMinimise(): void;
export function WindowMaximise(): void;
export function WindowToggleMaximise(): void;
export function WindowUnmaximise(): void;
export function WindowFullscreen(): void;
export function WindowUnfullscreen(): void;
export function WindowSetSize(width: number, height: number): void;
export function WindowGetSize(): Promise<{ w: number; h: number }>;
export function WindowSetPosition(x: number, y: number): void;
export function WindowGetPosition(): Promise<{ x: number; y: number }>;
export function WindowHide(): void;
export function WindowShow(): void;
export function WindowCenter(): void;
export function WindowSetTitle(title: string): void;
export function Quit(): void;
export function Environment(): Promise<{ buildType: string; platform: string; arch: string }>;
export function EventsOn(eventName: string, callback: (...data: unknown[]) => void): () => void;
export function EventsOnce(eventName: string, callback: (...data: unknown[]) => void): () => void;
export function EventsOnMultiple(eventName: string, callback: (...data: unknown[]) => void, maxCallbacks: number): () => void;
export function EventsEmit(eventName: string, ...data: unknown[]): void;
export function EventsOff(eventName: string, ...additionalEventNames: string[]): void;
export function LogDebug(message: string): void;
export function LogInfo(message: string): void;
export function LogWarning(message: string): void;
export function LogError(message: string): void;
export function LogFatal(message: string): void;
export function BrowserOpenURL(url: string): void;
export function ClipboardGetText(): Promise<string>;
export function ClipboardSetText(text: string): Promise<boolean>;
