package docker

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// ─── types ───────────────────────────────────────────────────────────────────

type DockerService struct {
	Image       string            `json:"image"`
	Ports       []string          `json:"ports"`
	Environment map[string]string `json:"environment,omitempty"`
	Volumes     []string          `json:"volumes,omitempty"`
	Command     string            `json:"command,omitempty"`
	DependsOn   []string          `json:"dependsOn,omitempty"`
	Restart     string            `json:"restart,omitempty"`
	HealthCheck *HealthCheck      `json:"healthCheck,omitempty"`
	Networks    []string          `json:"networks,omitempty"`
}

type HealthCheck struct {
	Test     []string `json:"test"`
	Interval string   `json:"interval"`
	Timeout  string   `json:"timeout"`
	Retries  int      `json:"retries"`
}

type PresetDef struct {
	ID          string                   `json:"id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	Tag         string                   `json:"tag"`
	Services    map[string]DockerService `json:"services"`
	Volumes     []string                 `json:"volumes,omitempty"`
	Networks    []string                 `json:"networks,omitempty"`
	EnvVars     map[string]string        `json:"envVars"`
	ReadmeIntro string                   `json:"readmeIntro"`
	ReadmeSteps []string                 `json:"readmeSteps"`
}

type LabOutput struct {
	ComposeContent string `json:"composeContent"`
	EnvContent     string `json:"envContent"`
	ReadmeContent  string `json:"readmeContent"`
}

// ─── Runtime types ───────────────────────────────────────────────────────────

type ContainerStatus struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Image   string `json:"image"`
	State   string `json:"state"`
	Status  string `json:"status"`
	Ports   string `json:"ports"`
	Running bool   `json:"running"`
}

type LabRunResult struct {
	ProjectName string   `json:"projectName"`
	Dir         string   `json:"dir"`
	Ids         []string `json:"ids"`
	Output      string   `json:"output"`
}

type LabInfo struct {
	ProjectName string `json:"projectName"`
	Status      string `json:"status"`
	ConfigFiles string `json:"configFiles"`
}

type DockerLabError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	Details string `json:"details,omitempty"`
}

func (e DockerLabError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	return e.Code
}

// ─── DockerLab struct ────────────────────────────────────────────────────────

type DockerLab struct{}

func NewDockerLab() *DockerLab {
	return &DockerLab{}
}

func (d *DockerLab) GetPresets() []PresetDef {
	presets := getPresets()
	result := make([]PresetDef, 0, len(presets))
	for _, p := range presets {
		result = append(result, p)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].ID < result[j].ID })
	return result
}

func (d *DockerLab) GenerateLab(ids []string) *LabOutput {
	presets := getPresets()
	selected := make([]PresetDef, 0, len(ids))
	for _, id := range ids {
		if p, ok := presets[id]; ok {
			selected = append(selected, p)
		}
	}

	// Merge services
	mergedServices := map[string]DockerService{}
	for _, p := range selected {
		for name, svc := range p.Services {
			// Deduplicate service names by prefixing with preset id if conflict
			finalName := name
			if _, exists := mergedServices[name]; exists {
				finalName = p.ID + "_" + name
			}
			mergedServices[finalName] = svc
		}
	}

	// Merge volumes
	mergedVolumes := []string{}
	seenVolumes := map[string]bool{}
	for _, p := range selected {
		for _, v := range p.Volumes {
			if !seenVolumes[v] {
				seenVolumes[v] = true
				mergedVolumes = append(mergedVolumes, v)
			}
		}
	}

	// Merge networks
	mergedNetworks := []string{}
	seenNetworks := map[string]bool{}
	for _, p := range selected {
		for _, n := range p.Networks {
			if !seenNetworks[n] {
				seenNetworks[n] = true
				mergedNetworks = append(mergedNetworks, n)
			}
		}
	}

	// Merge env vars
	mergedEnv := map[string]string{}
	for _, p := range selected {
		for k, v := range p.EnvVars {
			if _, exists := mergedEnv[k]; !exists {
				mergedEnv[k] = v
			}
		}
	}

	// Build compose YAML
	var compose strings.Builder
	compose.WriteString("# Docker Compose Lab — generated by adOmnia\n")
	compose.WriteString("# Presets: ")
	compose.WriteString(strings.Join(ids, ", "))
	compose.WriteString("\n\n")
	compose.WriteString("services:\n")
	svcNames := make([]string, 0, len(mergedServices))
	for name := range mergedServices {
		svcNames = append(svcNames, name)
	}
	sort.Strings(svcNames)

	for _, name := range svcNames {
		svc := mergedServices[name]
		compose.WriteString(fmt.Sprintf("  %s:\n", name))
		compose.WriteString(fmt.Sprintf("    image: %s\n", svc.Image))
		if svc.Command != "" {
			compose.WriteString(fmt.Sprintf("    command: %s\n", svc.Command))
		}
		if len(svc.Ports) > 0 {
			compose.WriteString("    ports:\n")
			for _, port := range svc.Ports {
				compose.WriteString(fmt.Sprintf("      - \"%s\"\n", port))
			}
		}
		if len(svc.Environment) > 0 {
			compose.WriteString("    environment:\n")
			envKeys := make([]string, 0, len(svc.Environment))
			for k := range svc.Environment {
				envKeys = append(envKeys, k)
			}
			sort.Strings(envKeys)
			for _, k := range envKeys {
				compose.WriteString(fmt.Sprintf("      %s: %s\n", k, yamlString(svc.Environment[k])))
			}
		}
		if len(svc.Volumes) > 0 {
			compose.WriteString("    volumes:\n")
			for _, vol := range svc.Volumes {
				compose.WriteString(fmt.Sprintf("      - %s\n", vol))
			}
		}
		if len(svc.DependsOn) > 0 {
			compose.WriteString("    depends_on:\n")
			for _, dep := range svc.DependsOn {
				compose.WriteString(fmt.Sprintf("      %s:\n", dep))
				compose.WriteString("        condition: service_healthy\n")
			}
		}
		if len(svc.Networks) > 0 {
			compose.WriteString("    networks:\n")
			for _, net := range svc.Networks {
				compose.WriteString(fmt.Sprintf("      - %s\n", net))
			}
		}
		if svc.Restart != "" {
			compose.WriteString(fmt.Sprintf("    restart: %s\n", svc.Restart))
		}
		if svc.HealthCheck != nil {
			compose.WriteString("    healthcheck:\n")
			compose.WriteString(fmt.Sprintf("      test: [%s]\n", strings.Join(quoteAll(svc.HealthCheck.Test), ", ")))
			compose.WriteString(fmt.Sprintf("      interval: %s\n", svc.HealthCheck.Interval))
			compose.WriteString(fmt.Sprintf("      timeout: %s\n", svc.HealthCheck.Timeout))
			compose.WriteString(fmt.Sprintf("      retries: %d\n", svc.HealthCheck.Retries))
		}
		compose.WriteString("\n")
	}

	if len(mergedVolumes) > 0 {
		compose.WriteString("volumes:\n")
		for _, vol := range mergedVolumes {
			compose.WriteString(fmt.Sprintf("  %s:\n", vol))
		}
		compose.WriteString("\n")
	}

	if len(mergedNetworks) > 0 {
		compose.WriteString("networks:\n")
		for _, net := range mergedNetworks {
			compose.WriteString(fmt.Sprintf("  %s:\n", net))
			compose.WriteString("    driver: bridge\n")
		}
		compose.WriteString("\n")
	}

	// Build .env
	envKeys := make([]string, 0, len(mergedEnv))
	for k := range mergedEnv {
		envKeys = append(envKeys, k)
	}
	sort.Strings(envKeys)

	var env strings.Builder
	env.WriteString("# Environment variables — adOmnia Docker Lab\n")
	env.WriteString("# Presets: ")
	env.WriteString(strings.Join(ids, ", "))
	env.WriteString("\n\n")
	for _, k := range envKeys {
		env.WriteString(fmt.Sprintf("%s=%s\n", k, mergedEnv[k]))
	}
	env.WriteString("\n")

	// Build README
	var readme strings.Builder
	readme.WriteString("# Docker Compose Lab\n\n")
	readme.WriteString("Generated by **adOmnia** — Docker Lab Wizard.\n\n")
	readme.WriteString("## Presets Included\n\n")
	for _, p := range selected {
		readme.WriteString(fmt.Sprintf("- **%s** — %s\n", p.Name, p.Description))
	}
	readme.WriteString("\n## Quick Start\n\n")
	readme.WriteString("```bash\n")
	readme.WriteString("# Start all services\n")
	readme.WriteString("docker compose up -d\n\n")
	readme.WriteString("# Check status\n")
	readme.WriteString("docker compose ps\n\n")
	readme.WriteString("# View logs\n")
	readme.WriteString("docker compose logs -f\n\n")
	readme.WriteString("# Stop all services\n")
	readme.WriteString("docker compose down\n")
	readme.WriteString("```\n\n")

	for _, p := range selected {
		if p.ReadmeIntro != "" {
			readme.WriteString(fmt.Sprintf("### %s\n\n", p.Name))
			readme.WriteString(p.ReadmeIntro + "\n\n")
		}
	}

	readme.WriteString("## Connection Details\n\n")
	readme.WriteString("| Service | URL / Connection |\n")
	readme.WriteString("|---------|------------------|\n")
	for _, p := range selected {
		for svcName, svc := range p.Services {
			var conn string
			if len(svc.Ports) > 0 {
				parts := strings.Split(svc.Ports[0], ":")
				if len(parts) == 2 {
					envName := strings.TrimPrefix(parts[0], "${")
					envName = strings.Split(envName, ":")[0]
					envName = strings.TrimSuffix(envName, "}")
					conn = fmt.Sprintf("`localhost:%s`", strings.TrimPrefix(parts[1], "${"))
					if v, ok := p.EnvVars[envName]; ok && !strings.HasPrefix(v, "${") {
						conn = fmt.Sprintf("`localhost:%s`", v)
					} else {
						conn = fmt.Sprintf("`localhost:%s`", parts[1])
					}
				}
			}
			readme.WriteString(fmt.Sprintf("| %s | %s |\n", svcName, conn))
		}
	}
	readme.WriteString("\n---\n")
	readme.WriteString("*Generated with [adOmnia](https://adomnia.io)*\n")

	return &LabOutput{
		ComposeContent: compose.String(),
		EnvContent:     env.String(),
		ReadmeContent:  readme.String(),
	}
}

// ─── Runtime methods ─────────────────────────────────────────────────────────

func (d *DockerLab) LabUp(ids []string) (*LabRunResult, error) {
	lab := d.GenerateLab(ids)
	projectName := labProjectName(ids)

	dir, err := labDir(projectName)
	if err != nil {
		return nil, fmt.Errorf("failed to create lab directory: %w", err)
	}

	composePath := filepath.Join(dir, "docker-compose.yml")
	if err := os.WriteFile(composePath, []byte(lab.ComposeContent), 0644); err != nil {
		return nil, fmt.Errorf("failed to write compose file: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(lab.EnvContent), 0644); err != nil {
		return nil, fmt.Errorf("failed to write .env file: %w", err)
	}
	if err := writeLabSupportFiles(dir, ids); err != nil {
		return nil, fmt.Errorf("failed to prepare lab files: %w", err)
	}

	if err := ensureDockerReady(); err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	out, err := runDockerCommand(ctx, dir, "compose", "-f", composePath, "-p", projectName, "config", "--quiet")
	if err != nil {
		return nil, DockerLabError{
			Code:    "invalid_compose_file",
			Message: "Generated compose file is invalid. Review the preset configuration and retry.",
			Details: strings.TrimSpace(string(out)),
		}
	}

	out, err = runDockerCommand(ctx, dir, "compose", "-f", composePath, "-p", projectName, "pull")
	if err != nil {
		if isDockerDaemonUnavailable(string(out), err) {
			return nil, dockerDaemonError(string(out))
		}
		return nil, DockerLabError{
			Code:    "image_pull_failure",
			Message: "Docker could not pull one or more images. Check your connection or registry access and retry.",
			Details: strings.TrimSpace(string(out)),
		}
	}

	out, err = runDockerCommand(ctx, dir, "compose", "-f", composePath, "-p", projectName, "up", "-d", "--remove-orphans")
	if err != nil {
		if isDockerDaemonUnavailable(string(out), err) {
			return nil, dockerDaemonError(string(out))
		}
		return nil, DockerLabError{
			Code:    "compose_up_failure",
			Message: "Docker Compose could not launch the selected lab.",
			Details: strings.TrimSpace(string(out)),
		}
	}

	return &LabRunResult{
		ProjectName: projectName,
		Dir:         dir,
		Ids:         ids,
		Output:      string(out),
	}, nil
}

func (d *DockerLab) LabDown(projectName string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "docker", "compose", "-p", projectName, "down", "--remove-orphans")
	configureHiddenCommand(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return string(out), fmt.Errorf("docker compose down failed: %w\n%s", err, string(out))
	}
	return string(out), nil
}

func (d *DockerLab) LabStatus(projectName string) ([]ContainerStatus, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "docker", "ps", "-a",
		"--filter", "label=com.docker.compose.project="+projectName,
		"--format", "{{json .}}",
	)
	configureHiddenCommand(cmd)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("docker ps failed: %w", err)
	}

	var result []ContainerStatus
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line == "" {
			continue
		}
		var raw struct {
			ID     string `json:"ID"`
			Names  string `json:"Names"`
			Image  string `json:"Image"`
			State  string `json:"State"`
			Status string `json:"Status"`
			Ports  string `json:"Ports"`
		}
		if err := json.Unmarshal([]byte(line), &raw); err != nil {
			continue
		}
		id := raw.ID
		if len(id) > 12 {
			id = id[:12]
		}
		result = append(result, ContainerStatus{
			ID:      id,
			Name:    raw.Names,
			Image:   raw.Image,
			State:   raw.State,
			Status:  raw.Status,
			Ports:   raw.Ports,
			Running: raw.State == "running",
		})
	}
	return result, nil
}

func (d *DockerLab) LabLogs(projectName string, lines int) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "docker", "compose", "-p", projectName,
		"logs", "--no-color", "--tail", fmt.Sprintf("%d", lines),
	)
	configureHiddenCommand(cmd)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return string(out), fmt.Errorf("docker compose logs failed: %w", err)
	}
	return string(out), nil
}

func (d *DockerLab) LabList() ([]LabInfo, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "docker", "compose", "ls", "--all", "--format", "json")
	configureHiddenCommand(cmd)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("docker compose ls failed: %w", err)
	}

	var all []struct {
		Name        string `json:"Name"`
		Status      string `json:"Status"`
		ConfigFiles string `json:"ConfigFiles"`
	}
	if err := json.Unmarshal(out, &all); err != nil {
		return nil, fmt.Errorf("parse docker compose ls output: %w", err)
	}

	var result []LabInfo
	for _, l := range all {
		if strings.HasPrefix(l.Name, "adomnia-") {
			result = append(result, LabInfo{
				ProjectName: l.Name,
				Status:      l.Status,
				ConfigFiles: l.ConfigFiles,
			})
		}
	}
	return result, nil
}

// ─── helpers ─────────────────────────────────────────────────────────────────

func labProjectName(ids []string) string {
	safe := strings.Join(ids, "-")
	safe = strings.ReplaceAll(safe, "+", "-")
	safe = strings.ReplaceAll(safe, " ", "-")
	return "adomnia-" + safe
}

func labDir(projectName string) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(home, ".adomnia", "labs", projectName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", fmt.Errorf("mkdir %s: %w", dir, err)
	}
	return dir, nil
}

func quoteAll(s []string) []string {
	out := make([]string, len(s))
	for i, v := range s {
		out[i] = fmt.Sprintf("\"%s\"", v)
	}
	return out
}

// ─── presets ─────────────────────────────────────────────────────────────────

func yamlString(value string) string {
	escaped := strings.ReplaceAll(value, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
	return "\"" + escaped + "\""
}

func runDockerCommand(ctx context.Context, dir string, args ...string) ([]byte, error) {
	cmd := exec.CommandContext(ctx, "docker", args...)
	cmd.Dir = dir
	configureHiddenCommand(cmd)
	return cmd.CombinedOutput()
}

func ensureDockerReady() error {
	if _, err := exec.LookPath("docker"); err != nil {
		return DockerLabError{
			Code:    "docker_cli_missing",
			Message: "Docker CLI is not installed or is not available on PATH.",
			Details: err.Error(),
		}
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	if out, err := runDockerCommand(ctx, "", "compose", "version"); err != nil {
		return DockerLabError{
			Code:    "docker_compose_missing",
			Message: "Docker Compose is not available. Install Docker Compose v2 and retry.",
			Details: strings.TrimSpace(string(out)),
		}
	}

	if out, err := runDockerCommand(ctx, "", "info", "--format", "{{json .ServerVersion}}"); err != nil {
		if isDockerDaemonUnavailable(string(out), err) {
			return dockerDaemonError(string(out))
		}
		return DockerLabError{
			Code:    "docker_daemon_not_running",
			Message: "Docker daemon is not running. Start Docker Desktop and retry.",
			Details: strings.TrimSpace(string(out)),
		}
	}

	return nil
}

func dockerDaemonError(details string) DockerLabError {
	return DockerLabError{
		Code:    "docker_daemon_not_running",
		Message: "Docker Desktop is not running. Start Docker Desktop and retry.",
		Details: strings.TrimSpace(details),
	}
}

func isDockerDaemonUnavailable(output string, err error) bool {
	text := strings.ToLower(output)
	if err != nil {
		text += "\n" + strings.ToLower(err.Error())
	}
	return strings.Contains(text, "dockerdesktoplinuxengine") ||
		strings.Contains(text, "docker desktop is not running") ||
		strings.Contains(text, "daemon is not running") ||
		strings.Contains(text, "cannot connect to the docker daemon") ||
		strings.Contains(text, "error during connect") ||
		strings.Contains(text, "open //./pipe/docker")
}

func writeLabSupportFiles(dir string, ids []string) error {
	presets := getPresets()
	needsMockDB := false
	needsOtelConfig := false
	needsPrometheusConfig := false

	for _, id := range ids {
		preset, ok := presets[id]
		if !ok {
			continue
		}
		for _, svc := range preset.Services {
			for _, vol := range svc.Volumes {
				switch {
				case strings.HasPrefix(vol, "./mock-db.json:"):
					needsMockDB = true
				case strings.HasPrefix(vol, "./otel-config.yaml:"):
					needsOtelConfig = true
				case strings.HasPrefix(vol, "./prometheus.yml:"):
					needsPrometheusConfig = true
				}
			}
		}
	}

	files := map[string]string{}
	if needsMockDB {
		files["mock-db.json"] = "{\n  \"users\": [\n    { \"id\": 1, \"name\": \"Ada Lovelace\", \"role\": \"admin\" }\n  ],\n  \"health\": { \"ok\": true }\n}\n"
	}
	if needsOtelConfig {
		files["otel-config.yaml"] = "receivers:\n  otlp:\n    protocols:\n      grpc:\n        endpoint: 0.0.0.0:4317\n      http:\n        endpoint: 0.0.0.0:4318\nexporters:\n  debug:\n    verbosity: basic\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]\n      exporters: [debug]\n    metrics:\n      receivers: [otlp]\n      exporters: [debug]\n    logs:\n      receivers: [otlp]\n      exporters: [debug]\n"
	}
	if needsPrometheusConfig {
		files["prometheus.yml"] = "global:\n  scrape_interval: 15s\nscrape_configs:\n  - job_name: prometheus\n    static_configs:\n      - targets: ['localhost:9090']\n"
	}

	for name, content := range files {
		path := filepath.Join(dir, name)
		if _, err := os.Stat(path); err == nil {
			continue
		} else if err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func getPresets() map[string]PresetDef {
	return map[string]PresetDef{
		// ── 1. PostgreSQL ─────────────────────────────────────────────────
		"postgres": {
			ID:          "postgres",
			Name:        "PostgreSQL",
			Description: "Relational database, version 16 Alpine",
			Tag:         "database",
			Services: map[string]DockerService{
				"postgres": {
					Image: "postgres:16-alpine",
					Ports: []string{"${POSTGRES_PORT:-5432}:5432"},
					Environment: map[string]string{
						"POSTGRES_USER":     "${POSTGRES_USER:-postgres}",
						"POSTGRES_PASSWORD": "${POSTGRES_PASSWORD:-postgres}",
						"POSTGRES_DB":       "${POSTGRES_DB:-adomnia}",
					},
					Volumes: []string{"postgres_data:/var/lib/postgresql/data"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"},
						Interval: "10s",
						Timeout:  "5s",
						Retries:  5,
					},
				},
			},
			Volumes: []string{"postgres_data"},
			EnvVars: map[string]string{
				"POSTGRES_PORT":     "5432",
				"POSTGRES_USER":     "postgres",
				"POSTGRES_PASSWORD": "postgres",
				"POSTGRES_DB":       "adomnia",
			},
			ReadmeIntro: "Connect using `psql -h localhost -p ${POSTGRES_PORT:-5432} -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-adomnia}` or any PostgreSQL client.",
			ReadmeSteps: []string{"Start the container", "Connect with your preferred client"},
		},

		// ── 2. MySQL ──────────────────────────────────────────────────────
		"mysql": {
			ID:          "mysql",
			Name:        "MySQL",
			Description: "Relational database, version 8.4",
			Tag:         "database",
			Services: map[string]DockerService{
				"mysql": {
					Image: "mysql:8.4",
					Ports: []string{"${MYSQL_PORT:-3306}:3306"},
					Environment: map[string]string{
						"MYSQL_ROOT_PASSWORD": "${MYSQL_ROOT_PASSWORD:-root}",
						"MYSQL_DATABASE":      "${MYSQL_DATABASE:-adomnia}",
						"MYSQL_USER":          "${MYSQL_USER:-adomnia}",
						"MYSQL_PASSWORD":      "${MYSQL_PASSWORD:-adomnia}",
					},
					Volumes: []string{"mysql_data:/var/lib/mysql"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD", "mysqladmin", "ping", "-h", "localhost"},
						Interval: "10s",
						Timeout:  "5s",
						Retries:  5,
					},
				},
			},
			Volumes: []string{"mysql_data"},
			EnvVars: map[string]string{
				"MYSQL_PORT":          "3306",
				"MYSQL_ROOT_PASSWORD": "root",
				"MYSQL_DATABASE":      "adomnia",
				"MYSQL_USER":          "adomnia",
				"MYSQL_PASSWORD":      "adomnia",
			},
			ReadmeIntro: "Connect using `mysql -h 127.0.0.1 -P ${MYSQL_PORT:-3306} -u ${MYSQL_USER:-adomnia} -p` or any MySQL client.",
		},

		// ── 3. MongoDB ────────────────────────────────────────────────────
		"mongodb": {
			ID:          "mongodb",
			Name:        "MongoDB",
			Description: "Document database, version 7",
			Tag:         "database",
			Services: map[string]DockerService{
				"mongodb": {
					Image: "mongo:7",
					Ports: []string{"${MONGO_PORT:-27017}:27017"},
					Environment: map[string]string{
						"MONGO_INITDB_ROOT_USERNAME": "${MONGO_USER:-admin}",
						"MONGO_INITDB_ROOT_PASSWORD": "${MONGO_PASSWORD:-admin}",
					},
					Volumes: []string{"mongo_data:/data/db"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD", "mongosh", "--eval", "db.adminCommand('ping')"},
						Interval: "10s",
						Timeout:  "5s",
						Retries:  5,
					},
				},
			},
			Volumes: []string{"mongo_data"},
			EnvVars: map[string]string{
				"MONGO_PORT":     "27017",
				"MONGO_USER":     "admin",
				"MONGO_PASSWORD": "admin",
			},
			ReadmeIntro: "Connect using `mongosh mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-admin}@localhost:${MONGO_PORT:-27017}` or any MongoDB client.",
		},

		// ── 4. Redis ──────────────────────────────────────────────────────
		"redis": {
			ID:          "redis",
			Name:        "Redis",
			Description: "In-memory data store, version 7 Alpine",
			Tag:         "cache",
			Services: map[string]DockerService{
				"redis": {
					Image:   "redis:7-alpine",
					Ports:   []string{"${REDIS_PORT:-6379}:6379"},
					Command: "redis-server --requirepass ${REDIS_PASSWORD:-redis} --appendonly yes",
					Volumes: []string{"redis_data:/data"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD", "redis-cli", "ping"},
						Interval: "10s",
						Timeout:  "5s",
						Retries:  5,
					},
				},
			},
			Volumes: []string{"redis_data"},
			EnvVars: map[string]string{
				"REDIS_PORT":     "6379",
				"REDIS_PASSWORD": "redis",
			},
			ReadmeIntro: "Connect using `redis-cli -h localhost -p ${REDIS_PORT:-6379} -a ${REDIS_PASSWORD:-redis}` or any Redis client.",
		},

		// ── 5. RabbitMQ ───────────────────────────────────────────────────
		"rabbitmq": {
			ID:          "rabbitmq",
			Name:        "RabbitMQ",
			Description: "Message broker with management UI, version 4",
			Tag:         "messaging",
			Services: map[string]DockerService{
				"rabbitmq": {
					Image: "rabbitmq:4-management-alpine",
					Ports: []string{
						"${RABBITMQ_AMQP_PORT:-5672}:5672",
						"${RABBITMQ_MGMT_PORT:-15672}:15672",
					},
					Environment: map[string]string{
						"RABBITMQ_DEFAULT_USER": "${RABBITMQ_USER:-guest}",
						"RABBITMQ_DEFAULT_PASS": "${RABBITMQ_PASSWORD:-guest}",
					},
					Volumes: []string{"rabbitmq_data:/var/lib/rabbitmq"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD", "rabbitmq-diagnostics", "check_port_connectivity"},
						Interval: "10s",
						Timeout:  "5s",
						Retries:  5,
					},
				},
			},
			Volumes: []string{"rabbitmq_data"},
			EnvVars: map[string]string{
				"RABBITMQ_AMQP_PORT": "5672",
				"RABBITMQ_MGMT_PORT": "15672",
				"RABBITMQ_USER":      "guest",
				"RABBITMQ_PASSWORD":  "guest",
			},
			ReadmeIntro: "AMQP on port `${RABBITMQ_AMQP_PORT:-5672}`. Management UI at http://localhost:${RABBITMQ_MGMT_PORT:-15672} (user: `${RABBITMQ_USER:-guest}` / pass: `${RABBITMQ_PASSWORD:-guest}`).",
		},

		// ── 6. Kafka ──────────────────────────────────────────────────────
		"kafka": {
			ID:          "kafka",
			Name:        "Kafka",
			Description: "Apache Kafka with KRaft mode (no ZooKeeper)",
			Tag:         "messaging",
			Services: map[string]DockerService{
				"kafka": {
					Image: "apache/kafka:latest",
					Ports: []string{"${KAFKA_PORT:-9092}:9092"},
					Environment: map[string]string{
						"KAFKA_NODE_ID":                                  "1",
						"KAFKA_PROCESS_ROLES":                            "broker,controller",
						"KAFKA_LISTENERS":                                "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093",
						"KAFKA_ADVERTISED_LISTENERS":                     "PLAINTEXT://localhost:${KAFKA_PORT:-9092}",
						"KAFKA_CONTROLLER_LISTENER_NAMES":                "CONTROLLER",
						"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP":           "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT",
						"KAFKA_CONTROLLER_QUORUM_VOTERS":                 "1@localhost:9093",
						"KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR":         "1",
						"KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR": "1",
						"KAFKA_TRANSACTION_STATE_LOG_MIN_ISR":            "1",
						"KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS":         "0",
						"KAFKA_NUM_PARTITIONS":                           "3",
					},
					Volumes: []string{"kafka_data:/var/lib/kafka/data"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"},
						Interval: "10s",
						Timeout:  "10s",
						Retries:  10,
					},
				},
			},
			Volumes: []string{"kafka_data"},
			EnvVars: map[string]string{
				"KAFKA_PORT": "9092",
			},
			ReadmeIntro: "Bootstrap server at `localhost:${KAFKA_PORT:-9092}`. Uses KRaft mode — no ZooKeeper required. Use `kafka-topics.sh --bootstrap-server localhost:${KAFKA_PORT:-9092} --list` to verify.",
		},

		// ── 7. Kafka UI ───────────────────────────────────────────────────
		"kafka-ui": {
			ID:          "kafka-ui",
			Name:        "Kafka UI",
			Description: "Web UI for Apache Kafka management",
			Tag:         "ui",
			Services: map[string]DockerService{
				"kafka-ui": {
					Image: "provectuslabs/kafka-ui:latest",
					Ports: []string{"${KAFKA_UI_PORT:-8080}:8080"},
					Environment: map[string]string{
						"KAFKA_CLUSTERS_0_NAME":             "local",
						"KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS": "host.docker.internal:${KAFKA_PORT:-9092}",
					},
					Restart: "unless-stopped",
				},
			},
			EnvVars: map[string]string{
				"KAFKA_UI_PORT": "8080",
				"KAFKA_PORT":    "9092",
			},
			ReadmeIntro: "Web UI at http://localhost:${KAFKA_UI_PORT:-8080}. Connects to an existing local Kafka broker via `host.docker.internal:${KAFKA_PORT:-9092}`.",
		},

		// ── 8. Mock Server ────────────────────────────────────────────────
		"mock-server": {
			ID:          "mock-server",
			Name:        "Mock Server",
			Description: "REST API mock server (JSON Server)",
			Tag:         "api",
			Services: map[string]DockerService{
				"mock-server": {
					Image:   "williamyeh/json-server:latest",
					Ports:   []string{"${MOCK_PORT:-3000}:3000"},
					Volumes: []string{"./mock-db.json:/data/db.json"},
					Command: "--watch /data/db.json --host 0.0.0.0",
					Restart: "unless-stopped",
				},
			},
			EnvVars: map[string]string{
				"MOCK_PORT": "3000",
			},
			ReadmeIntro: "REST API mock at http://localhost:${MOCK_PORT:-3000}. Create a `mock-db.json` file in the same directory with your data. See https://github.com/typicode/json-server for the schema.",
			ReadmeSteps: []string{"Create `mock-db.json` with your data", "Start the container", "Access at http://localhost:3000"},
		},

		// ── 9. REST Mock + PostgreSQL ─────────────────────────────────────
		"rest-mock+postgres": {
			ID:          "rest-mock+postgres",
			Name:        "REST Mock + PostgreSQL",
			Description: "JSON Server mock API backed by PostgreSQL",
			Tag:         "combo",
			Services: map[string]DockerService{
				"postgres": {
					Image: "postgres:16-alpine",
					Ports: []string{"${POSTGRES_PORT:-5432}:5432"},
					Environment: map[string]string{
						"POSTGRES_USER":     "${POSTGRES_USER:-postgres}",
						"POSTGRES_PASSWORD": "${POSTGRES_PASSWORD:-postgres}",
						"POSTGRES_DB":       "${POSTGRES_DB:-adomnia}",
					},
					Volumes: []string{"postgres_data:/var/lib/postgresql/data"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"},
						Interval: "10s",
						Timeout:  "5s",
						Retries:  5,
					},
				},
				"mock-server": {
					Image:   "williamyeh/json-server:latest",
					Ports:   []string{"${MOCK_PORT:-3000}:3000"},
					Volumes: []string{"./mock-db.json:/data/db.json"},
					Command: "--watch /data/db.json --host 0.0.0.0",
					Restart: "unless-stopped",
				},
			},
			Volumes: []string{"postgres_data"},
			EnvVars: map[string]string{
				"POSTGRES_PORT":     "5432",
				"POSTGRES_USER":     "postgres",
				"POSTGRES_PASSWORD": "postgres",
				"POSTGRES_DB":       "adomnia",
				"MOCK_PORT":         "3000",
			},
			ReadmeIntro: "REST API mock at http://localhost:${MOCK_PORT:-3000} with PostgreSQL at `localhost:${POSTGRES_PORT:-5432}`.",
		},

		// ── 10. REST Mock + Kafka ─────────────────────────────────────────
		"rest-mock+kafka": {
			ID:          "rest-mock+kafka",
			Name:        "REST Mock + Kafka",
			Description: "JSON Server mock API with Kafka event streaming",
			Tag:         "combo",
			Services: map[string]DockerService{
				"kafka": {
					Image: "apache/kafka:latest",
					Ports: []string{"${KAFKA_PORT:-9092}:9092"},
					Environment: map[string]string{
						"KAFKA_NODE_ID":                                  "1",
						"KAFKA_PROCESS_ROLES":                            "broker,controller",
						"KAFKA_LISTENERS":                                "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093",
						"KAFKA_ADVERTISED_LISTENERS":                     "PLAINTEXT://localhost:${KAFKA_PORT:-9092}",
						"KAFKA_CONTROLLER_LISTENER_NAMES":                "CONTROLLER",
						"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP":           "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT",
						"KAFKA_CONTROLLER_QUORUM_VOTERS":                 "1@localhost:9093",
						"KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR":         "1",
						"KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR": "1",
						"KAFKA_TRANSACTION_STATE_LOG_MIN_ISR":            "1",
						"KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS":         "0",
						"KAFKA_NUM_PARTITIONS":                           "3",
					},
					Volumes: []string{"kafka_data:/var/lib/kafka/data"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"},
						Interval: "10s",
						Timeout:  "10s",
						Retries:  10,
					},
				},
				"mock-server": {
					Image:   "williamyeh/json-server:latest",
					Ports:   []string{"${MOCK_PORT:-3000}:3000"},
					Volumes: []string{"./mock-db.json:/data/db.json"},
					Command: "--watch /data/db.json --host 0.0.0.0",
					Restart: "unless-stopped",
				},
			},
			Volumes: []string{"kafka_data"},
			EnvVars: map[string]string{
				"KAFKA_PORT": "9092",
				"MOCK_PORT":  "3000",
			},
			ReadmeIntro: "REST API mock at http://localhost:${MOCK_PORT:-3000} with Kafka at `localhost:${KAFKA_PORT:-9092}`.",
		},

		// ── 11. Kafka + UI ────────────────────────────────────────────────
		"kafka+ui": {
			ID:          "kafka+ui",
			Name:        "Kafka + UI",
			Description: "Apache Kafka with web management UI",
			Tag:         "combo",
			Services: map[string]DockerService{
				"kafka": {
					Image: "apache/kafka:latest",
					Ports: []string{"${KAFKA_PORT:-9092}:9092"},
					Environment: map[string]string{
						"KAFKA_NODE_ID":                                  "1",
						"KAFKA_PROCESS_ROLES":                            "broker,controller",
						"KAFKA_LISTENERS":                                "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093",
						"KAFKA_ADVERTISED_LISTENERS":                     "PLAINTEXT://localhost:${KAFKA_PORT:-9092}",
						"KAFKA_CONTROLLER_LISTENER_NAMES":                "CONTROLLER",
						"KAFKA_LISTENER_SECURITY_PROTOCOL_MAP":           "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT",
						"KAFKA_CONTROLLER_QUORUM_VOTERS":                 "1@localhost:9093",
						"KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR":         "1",
						"KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR": "1",
						"KAFKA_TRANSACTION_STATE_LOG_MIN_ISR":            "1",
						"KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS":         "0",
						"KAFKA_NUM_PARTITIONS":                           "3",
					},
					Volumes: []string{"kafka_data:/var/lib/kafka/data"},
					Restart: "unless-stopped",
					HealthCheck: &HealthCheck{
						Test:     []string{"CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"},
						Interval: "10s",
						Timeout:  "10s",
						Retries:  10,
					},
				},
				"kafka-ui": {
					Image: "provectuslabs/kafka-ui:latest",
					Ports: []string{"${KAFKA_UI_PORT:-8080}:8080"},
					Environment: map[string]string{
						"KAFKA_CLUSTERS_0_NAME":             "local",
						"KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS": "kafka:9092",
					},
					DependsOn: []string{"kafka"},
					Restart:   "unless-stopped",
				},
			},
			Volumes: []string{"kafka_data"},
			EnvVars: map[string]string{
				"KAFKA_PORT":    "9092",
				"KAFKA_UI_PORT": "8080",
			},
			ReadmeIntro: "Kafka at `localhost:${KAFKA_PORT:-9092}`. Web UI at http://localhost:${KAFKA_UI_PORT:-8080}.",
		},

		// ── 12. OpenTelemetry Collector ───────────────────────────────────
		"otel": {
			ID:          "otel",
			Name:        "OpenTelemetry Collector",
			Description: "OTel Collector for traces, metrics, and logs",
			Tag:         "observability",
			Services: map[string]DockerService{
				"otel-collector": {
					Image: "otel/opentelemetry-collector-contrib:latest",
					Ports: []string{
						"${OTEL_GRPC_PORT:-4317}:4317",
						"${OTEL_HTTP_PORT:-4318}:4318",
						"${OTEL_METRICS_PORT:-8888}:8888",
					},
					Volumes: []string{"./otel-config.yaml:/etc/otelcol/config.yaml"},
					Command: "--config /etc/otelcol/config.yaml",
					Restart: "unless-stopped",
				},
			},
			EnvVars: map[string]string{
				"OTEL_GRPC_PORT":    "4317",
				"OTEL_HTTP_PORT":    "4318",
				"OTEL_METRICS_PORT": "8888",
			},
			ReadmeIntro: "gRPC endpoint at `localhost:${OTEL_GRPC_PORT:-4317}`, HTTP at `localhost:${OTEL_HTTP_PORT:-4318}`. Create an `otel-config.yaml` with your pipeline configuration.",
			ReadmeSteps: []string{"Create `otel-config.yaml` with receivers/processors/exporters", "Start the container", "Send telemetry via OTLP"},
		},

		// ── 13. Jaeger ────────────────────────────────────────────────────
		"jaeger": {
			ID:          "jaeger",
			Name:        "Jaeger",
			Description: "Distributed tracing platform, all-in-one",
			Tag:         "observability",
			Services: map[string]DockerService{
				"jaeger": {
					Image: "jaegertracing/all-in-one:latest",
					Ports: []string{
						"${JAEGER_UI_PORT:-16686}:16686",
						"${JAEGER_GRPC_PORT:-4317}:4317",
						"${JAEGER_THRIFT_PORT:-6831}:6831/udp",
						"${JAEGER_THRIFT_HTTP_PORT:-14268}:14268",
					},
					Environment: map[string]string{
						"COLLECTOR_OTLP_ENABLED": "true",
					},
					Restart: "unless-stopped",
				},
			},
			EnvVars: map[string]string{
				"JAEGER_UI_PORT":          "16686",
				"JAEGER_GRPC_PORT":        "4317",
				"JAEGER_THRIFT_PORT":      "6831",
				"JAEGER_THRIFT_HTTP_PORT": "14268",
			},
			ReadmeIntro: "Jaeger UI at http://localhost:${JAEGER_UI_PORT:-16686}. OTLP gRPC at `localhost:${JAEGER_GRPC_PORT:-4317}`, Thrift at `localhost:${JAEGER_THRIFT_PORT:-6831}`.",
		},

		// ── 14. Prometheus ────────────────────────────────────────────────
		"prometheus": {
			ID:          "prometheus",
			Name:        "Prometheus",
			Description: "Metrics collection and alerting",
			Tag:         "observability",
			Services: map[string]DockerService{
				"prometheus": {
					Image:   "prom/prometheus:latest",
					Ports:   []string{"${PROMETHEUS_PORT:-9090}:9090"},
					Volumes: []string{"./prometheus.yml:/etc/prometheus/prometheus.yml", "prometheus_data:/prometheus"},
					Command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus",
					Restart: "unless-stopped",
				},
			},
			Volumes: []string{"prometheus_data"},
			EnvVars: map[string]string{
				"PROMETHEUS_PORT": "9090",
			},
			ReadmeIntro: "Prometheus UI at http://localhost:${PROMETHEUS_PORT:-9090}. Create a `prometheus.yml` configuration file with your scrape targets.",
			ReadmeSteps: []string{"Create `prometheus.yml` with scrape configs", "Start the container", "Access at http://localhost:9090"},
		},

		// ── 15. Grafana ───────────────────────────────────────────────────
		"grafana": {
			ID:          "grafana",
			Name:        "Grafana",
			Description: "Observability dashboards and visualization",
			Tag:         "observability",
			Services: map[string]DockerService{
				"grafana": {
					Image: "grafana/grafana:latest",
					Ports: []string{"${GRAFANA_PORT:-3000}:3000"},
					Environment: map[string]string{
						"GF_SECURITY_ADMIN_USER":     "${GRAFANA_USER:-admin}",
						"GF_SECURITY_ADMIN_PASSWORD": "${GRAFANA_PASSWORD:-admin}",
					},
					Volumes: []string{"grafana_data:/var/lib/grafana"},
					Restart: "unless-stopped",
				},
			},
			Volumes: []string{"grafana_data"},
			EnvVars: map[string]string{
				"GRAFANA_PORT":     "3000",
				"GRAFANA_USER":     "admin",
				"GRAFANA_PASSWORD": "admin",
			},
			ReadmeIntro: "Grafana UI at http://localhost:${GRAFANA_PORT:-3000} (user: `${GRAFANA_USER:-admin}` / pass: `${GRAFANA_PASSWORD:-admin}`). Add Prometheus as a data source from the Connections menu.",
		},
	}
}
