// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum AuthorizationState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthorizationOpened = "opened",
    AuthorizationPermitted = "tooling-permitted",
};

export class Capabilities {
    "schemaVersion": number;
    "projectOpen": boolean;
    "projectCreate": boolean;
    "documents": boolean;
    "toolchain": boolean;
    "processes": boolean;
    "lsp": boolean;
    "terminal": boolean;
    "debug": boolean;
    "tests": boolean;
    "multipleSessions": boolean;
    "separateWindows": boolean;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("projectOpen" in $$source)) {
            this["projectOpen"] = false;
        }
        if (!("projectCreate" in $$source)) {
            this["projectCreate"] = false;
        }
        if (!("documents" in $$source)) {
            this["documents"] = false;
        }
        if (!("toolchain" in $$source)) {
            this["toolchain"] = false;
        }
        if (!("processes" in $$source)) {
            this["processes"] = false;
        }
        if (!("lsp" in $$source)) {
            this["lsp"] = false;
        }
        if (!("terminal" in $$source)) {
            this["terminal"] = false;
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("tests" in $$source)) {
            this["tests"] = false;
        }
        if (!("multipleSessions" in $$source)) {
            this["multipleSessions"] = false;
        }
        if (!("separateWindows" in $$source)) {
            this["separateWindows"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

export class CodeActionEntry {
    "id": string;
    "title": string;
    "kind"?: string;
    "preferred"?: boolean;
    "disabled"?: string;

    /** Creates a new CodeActionEntry instance. */
    constructor($$source: Partial<CodeActionEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeActionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): CodeActionEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeActionEntry($$parsedSource as Partial<CodeActionEntry>);
    }
}

export class CompletionEntry {
    "label": string;
    "kind": number;
    "detail"?: string;
    "documentation"?: string;
    "sortText"?: string;
    "filterText"?: string;
    "insertText": string;
    "snippet": boolean;
    "range"?: EditorRange | null;
    "additionalEdits"?: EditorTextEdit[];
    "preselect"?: boolean;
    "deprecated"?: boolean;

    /** Creates a new CompletionEntry instance. */
    constructor($$source: Partial<CompletionEntry> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = 0;
        }
        if (!("insertText" in $$source)) {
            this["insertText"] = "";
        }
        if (!("snippet" in $$source)) {
            this["snippet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletionEntry {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField8_0($$parsedSource["range"]);
        }
        if ("additionalEdits" in $$parsedSource) {
            $$parsedSource["additionalEdits"] = $$createField9_0($$parsedSource["additionalEdits"]);
        }
        return new CompletionEntry($$parsedSource as Partial<CompletionEntry>);
    }
}

export class CompletionResult {
    "version": number;
    "incomplete": boolean;
    "items": CompletionEntry[];

    /** Creates a new CompletionResult instance. */
    constructor($$source: Partial<CompletionResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("incomplete" in $$source)) {
            this["incomplete"] = false;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletionResult {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        return new CompletionResult($$parsedSource as Partial<CompletionResult>);
    }
}

export class CreateProjectRequest {
    "parentPath": string;
    "name": string;
    "modulePath": string;
    "confirmed": boolean;

    /** Creates a new CreateProjectRequest instance. */
    constructor($$source: Partial<CreateProjectRequest> = {}) {
        if (!("parentPath" in $$source)) {
            this["parentPath"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("modulePath" in $$source)) {
            this["modulePath"] = "";
        }
        if (!("confirmed" in $$source)) {
            this["confirmed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateProjectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateProjectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateProjectRequest($$parsedSource as Partial<CreateProjectRequest>);
    }
}

export class DependencyActionRequest {
    "sessionId": SessionID;
    "moduleDirectory": string;
    "action": string;
    "modulePath": string;
    "version": string;
    "localPath"?: string;
    "confirmed": boolean;

    /** Creates a new DependencyActionRequest instance. */
    constructor($$source: Partial<DependencyActionRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("moduleDirectory" in $$source)) {
            this["moduleDirectory"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("modulePath" in $$source)) {
            this["modulePath"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("confirmed" in $$source)) {
            this["confirmed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyActionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DependencyActionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DependencyActionRequest($$parsedSource as Partial<DependencyActionRequest>);
    }
}

export class DependencyState {
    "moduleDirectory": string;
    "modulePath": string;
    "goModPath": string;
    "goSumPresent": boolean;
    "dependencies": GoDependency[];
    "replacements": GoReplacement[];

    /** Creates a new DependencyState instance. */
    constructor($$source: Partial<DependencyState> = {}) {
        if (!("moduleDirectory" in $$source)) {
            this["moduleDirectory"] = "";
        }
        if (!("modulePath" in $$source)) {
            this["modulePath"] = "";
        }
        if (!("goModPath" in $$source)) {
            this["goModPath"] = "";
        }
        if (!("goSumPresent" in $$source)) {
            this["goSumPresent"] = false;
        }
        if (!("dependencies" in $$source)) {
            this["dependencies"] = [];
        }
        if (!("replacements" in $$source)) {
            this["replacements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DependencyState instance from a string or object.
     */
    static createFrom($$source: any = {}): DependencyState {
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField4_0($$parsedSource["dependencies"]);
        }
        if ("replacements" in $$parsedSource) {
            $$parsedSource["replacements"] = $$createField5_0($$parsedSource["replacements"]);
        }
        return new DependencyState($$parsedSource as Partial<DependencyState>);
    }
}

export class DiagnosticsReport {
    "uri": string;
    "path": string;
    "relativePath"?: string;
    "documentId"?: DocumentID;
    "diagnostics": EditorDiagnostic[];

    /** Creates a new DiagnosticsReport instance. */
    constructor($$source: Partial<DiagnosticsReport> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticsReport instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticsReport {
        const $$createField4_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField4_0($$parsedSource["diagnostics"]);
        }
        return new DiagnosticsReport($$parsedSource as Partial<DiagnosticsReport>);
    }
}

export class Document {
    "id": DocumentID;
    "sessionId": SessionID;
    "uri": string;
    "path": string;
    "relativePath": string;
    "name": string;
    "language": string;
    "version": number;
    "dirty": boolean;
    "readOnly"?: boolean;
    "external"?: boolean;

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("dirty" in $$source)) {
            this["dirty"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Document($$parsedSource as Partial<Document>);
    }
}

export class DocumentDiskState {
    "documentId": DocumentID;
    "changed": boolean;
    "content"?: string;
    "diskToken": string;
    "modifiedAt": string;

    /** Creates a new DocumentDiskState instance. */
    constructor($$source: Partial<DocumentDiskState> = {}) {
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }
        if (!("changed" in $$source)) {
            this["changed"] = false;
        }
        if (!("diskToken" in $$source)) {
            this["diskToken"] = "";
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentDiskState instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentDiskState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentDiskState($$parsedSource as Partial<DocumentDiskState>);
    }
}

export type DocumentID = string;

export class DocumentSymbolsResult {
    "version": number;
    "symbols": SymbolNode[];

    /** Creates a new DocumentSymbolsResult instance. */
    constructor($$source: Partial<DocumentSymbolsResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("symbols" in $$source)) {
            this["symbols"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentSymbolsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentSymbolsResult {
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("symbols" in $$parsedSource) {
            $$parsedSource["symbols"] = $$createField1_0($$parsedSource["symbols"]);
        }
        return new DocumentSymbolsResult($$parsedSource as Partial<DocumentSymbolsResult>);
    }
}

export class EditorDiagnostic {
    "range": EditorRange;
    "severity": number;
    "message": string;
    "source"?: string;
    "code"?: string;

    /** Creates a new EditorDiagnostic instance. */
    constructor($$source: Partial<EditorDiagnostic> = {}) {
        if (!("range" in $$source)) {
            this["range"] = (new EditorRange());
        }
        if (!("severity" in $$source)) {
            this["severity"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorDiagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorDiagnostic {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        return new EditorDiagnostic($$parsedSource as Partial<EditorDiagnostic>);
    }
}

export class EditorLocation {
    "uri": string;
    "path": string;
    "relativePath"?: string;
    "external": boolean;
    "range": EditorRange;
    "preview"?: string;

    /**
     * Usage vale declaration, read, write o import per i risultati di Find Usages.
     */
    "usage"?: string;

    /** Creates a new EditorLocation instance. */
    constructor($$source: Partial<EditorLocation> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("external" in $$source)) {
            this["external"] = false;
        }
        if (!("range" in $$source)) {
            this["range"] = (new EditorRange());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorLocation instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorLocation {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField4_0($$parsedSource["range"]);
        }
        return new EditorLocation($$parsedSource as Partial<EditorLocation>);
    }
}

export class EditorRange {
    "startLine": number;
    "startColumn": number;
    "endLine": number;
    "endColumn": number;

    /** Creates a new EditorRange instance. */
    constructor($$source: Partial<EditorRange> = {}) {
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("startColumn" in $$source)) {
            this["startColumn"] = 0;
        }
        if (!("endLine" in $$source)) {
            this["endLine"] = 0;
        }
        if (!("endColumn" in $$source)) {
            this["endColumn"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorRange instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditorRange($$parsedSource as Partial<EditorRange>);
    }
}

export class EditorTextEdit {
    "range": EditorRange;
    "text": string;

    /** Creates a new EditorTextEdit instance. */
    constructor($$source: Partial<EditorTextEdit> = {}) {
        if (!("range" in $$source)) {
            this["range"] = (new EditorRange());
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorTextEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorTextEdit {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        return new EditorTextEdit($$parsedSource as Partial<EditorTextEdit>);
    }
}

/**
 * EnvironmentEntry rappresenta una variabile d'ambiente di una configurazione Run.
 * Le voci marcate Secret non persistono il valore: viene richiesto all'avvio e
 * resta soltanto in memoria per la durata della sessione.
 */
export class EnvironmentEntry {
    "key": string;
    "value"?: string;
    "secret"?: boolean;

    /** Creates a new EnvironmentEntry instance. */
    constructor($$source: Partial<EnvironmentEntry> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvironmentEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentEntry($$parsedSource as Partial<EnvironmentEntry>);
    }
}

export class Execution {
    "id": RunID;
    "sessionId": SessionID;
    "kind": string;
    "status": string;
    "command": string;
    "workingDirectory": string;
    "pid"?: number;
    "startedAt": string;
    "finishedAt"?: string | null;
    "exitCode"?: number | null;
    "durationMillis": number;
    "error"?: string;

    /** Creates a new Execution instance. */
    constructor($$source: Partial<Execution> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("durationMillis" in $$source)) {
            this["durationMillis"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Execution instance from a string or object.
     */
    static createFrom($$source: any = {}): Execution {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Execution($$parsedSource as Partial<Execution>);
    }
}

export class FileChange {
    "uri": string;
    "path": string;
    "relativePath": string;
    "documentId"?: DocumentID;
    "edits": EditorTextEdit[];
    "newContent": string;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("edits" in $$source)) {
            this["edits"] = [];
        }
        if (!("newContent" in $$source)) {
            this["newContent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edits" in $$parsedSource) {
            $$parsedSource["edits"] = $$createField4_0($$parsedSource["edits"]);
        }
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

export class FileEntry {
    "name": string;
    "relativePath": string;
    "directory": boolean;
    "ignored"?: boolean;
    "size"?: number;
    "modifiedAt": string;
    "language"?: string;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = false;
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class FormatResult {
    "version": number;
    "edits": EditorTextEdit[];

    /** Creates a new FormatResult instance. */
    constructor($$source: Partial<FormatResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("edits" in $$source)) {
            this["edits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormatResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FormatResult {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("edits" in $$parsedSource) {
            $$parsedSource["edits"] = $$createField1_0($$parsedSource["edits"]);
        }
        return new FormatResult($$parsedSource as Partial<FormatResult>);
    }
}

export class GoDependency {
    "path": string;
    "version": string;
    "indirect": boolean;

    /** Creates a new GoDependency instance. */
    constructor($$source: Partial<GoDependency> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("indirect" in $$source)) {
            this["indirect"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoDependency instance from a string or object.
     */
    static createFrom($$source: any = {}): GoDependency {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoDependency($$parsedSource as Partial<GoDependency>);
    }
}

export class GoModule {
    "path": string;
    "modulePath"?: string;

    /** Creates a new GoModule instance. */
    constructor($$source: Partial<GoModule> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoModule instance from a string or object.
     */
    static createFrom($$source: any = {}): GoModule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoModule($$parsedSource as Partial<GoModule>);
    }
}

export class GoReplacement {
    "path": string;
    "version"?: string;
    "newPath": string;
    "newVersion"?: string;
    "local": boolean;

    /** Creates a new GoReplacement instance. */
    constructor($$source: Partial<GoReplacement> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("newPath" in $$source)) {
            this["newPath"] = "";
        }
        if (!("local" in $$source)) {
            this["local"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoReplacement instance from a string or object.
     */
    static createFrom($$source: any = {}): GoReplacement {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoReplacement($$parsedSource as Partial<GoReplacement>);
    }
}

export class GoplsInfo {
    "available": boolean;
    "binary"?: string;
    "version"?: string;
    "source"?: string;
    "managedDir"?: string;
    "error"?: string;

    /** Creates a new GoplsInfo instance. */
    constructor($$source: Partial<GoplsInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoplsInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GoplsInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoplsInfo($$parsedSource as Partial<GoplsInfo>);
    }
}

export class HighlightEntry {
    "range": EditorRange;

    /**
     * Kind è text, read o write.
     */
    "kind": string;

    /** Creates a new HighlightEntry instance. */
    constructor($$source: Partial<HighlightEntry> = {}) {
        if (!("range" in $$source)) {
            this["range"] = (new EditorRange());
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HighlightEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HighlightEntry {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        return new HighlightEntry($$parsedSource as Partial<HighlightEntry>);
    }
}

export class HighlightsResult {
    "version": number;
    "highlights": HighlightEntry[];

    /** Creates a new HighlightsResult instance. */
    constructor($$source: Partial<HighlightsResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("highlights" in $$source)) {
            this["highlights"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HighlightsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HighlightsResult {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("highlights" in $$parsedSource) {
            $$parsedSource["highlights"] = $$createField1_0($$parsedSource["highlights"]);
        }
        return new HighlightsResult($$parsedSource as Partial<HighlightsResult>);
    }
}

export class HoverResult {
    "version": number;
    "markdown": string;
    "range"?: EditorRange | null;

    /** Creates a new HoverResult instance. */
    constructor($$source: Partial<HoverResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("markdown" in $$source)) {
            this["markdown"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HoverResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HoverResult {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField2_0($$parsedSource["range"]);
        }
        return new HoverResult($$parsedSource as Partial<HoverResult>);
    }
}

export class InlayHintEntry {
    "line": number;
    "column": number;
    "label": string;
    "kind": number;
    "paddingLeft": boolean;
    "paddingRight": boolean;

    /** Creates a new InlayHintEntry instance. */
    constructor($$source: Partial<InlayHintEntry> = {}) {
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = 0;
        }
        if (!("paddingLeft" in $$source)) {
            this["paddingLeft"] = false;
        }
        if (!("paddingRight" in $$source)) {
            this["paddingRight"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InlayHintEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): InlayHintEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InlayHintEntry($$parsedSource as Partial<InlayHintEntry>);
    }
}

export class InlayHintsResult {
    "version": number;
    "hints": InlayHintEntry[];

    /** Creates a new InlayHintsResult instance. */
    constructor($$source: Partial<InlayHintsResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("hints" in $$source)) {
            this["hints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InlayHintsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InlayHintsResult {
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hints" in $$parsedSource) {
            $$parsedSource["hints"] = $$createField1_0($$parsedSource["hints"]);
        }
        return new InlayHintsResult($$parsedSource as Partial<InlayHintsResult>);
    }
}

export class InstallToolchainRequest {
    "sessionId": SessionID;
    "version": string;
    "confirmed": boolean;
    "activate": boolean;

    /** Creates a new InstallToolchainRequest instance. */
    constructor($$source: Partial<InstallToolchainRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("confirmed" in $$source)) {
            this["confirmed"] = false;
        }
        if (!("activate" in $$source)) {
            this["activate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallToolchainRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallToolchainRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallToolchainRequest($$parsedSource as Partial<InstallToolchainRequest>);
    }
}

export class InstalledToolchain {
    "version": string;
    "goBinary": string;

    /** Creates a new InstalledToolchain instance. */
    constructor($$source: Partial<InstalledToolchain> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("goBinary" in $$source)) {
            this["goBinary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstalledToolchain instance from a string or object.
     */
    static createFrom($$source: any = {}): InstalledToolchain {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstalledToolchain($$parsedSource as Partial<InstalledToolchain>);
    }
}

/**
 * LanguageServerFeatures descrive le funzioni opzionali annunciate da gopls all'avvio.
 */
export class LanguageServerFeatures {
    "semanticTokens": boolean;
    "tokenTypes": string[];
    "tokenModifiers": string[];
    "inlayHints": boolean;
    "documentHighlight": boolean;
    "callHierarchy": boolean;

    /** Creates a new LanguageServerFeatures instance. */
    constructor($$source: Partial<LanguageServerFeatures> = {}) {
        if (!("semanticTokens" in $$source)) {
            this["semanticTokens"] = false;
        }
        if (!("tokenTypes" in $$source)) {
            this["tokenTypes"] = [];
        }
        if (!("tokenModifiers" in $$source)) {
            this["tokenModifiers"] = [];
        }
        if (!("inlayHints" in $$source)) {
            this["inlayHints"] = false;
        }
        if (!("documentHighlight" in $$source)) {
            this["documentHighlight"] = false;
        }
        if (!("callHierarchy" in $$source)) {
            this["callHierarchy"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageServerFeatures instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageServerFeatures {
        const $$createField1_0 = $$createType18;
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tokenTypes" in $$parsedSource) {
            $$parsedSource["tokenTypes"] = $$createField1_0($$parsedSource["tokenTypes"]);
        }
        if ("tokenModifiers" in $$parsedSource) {
            $$parsedSource["tokenModifiers"] = $$createField2_0($$parsedSource["tokenModifiers"]);
        }
        return new LanguageServerFeatures($$parsedSource as Partial<LanguageServerFeatures>);
    }
}

export class LanguageServerSettings {
    "gofumpt": boolean;
    "staticcheck": boolean;
    "placeholders": boolean;
    "semanticLinks": boolean;

    /** Creates a new LanguageServerSettings instance. */
    constructor($$source: Partial<LanguageServerSettings> = {}) {
        if (!("gofumpt" in $$source)) {
            this["gofumpt"] = false;
        }
        if (!("staticcheck" in $$source)) {
            this["staticcheck"] = false;
        }
        if (!("placeholders" in $$source)) {
            this["placeholders"] = false;
        }
        if (!("semanticLinks" in $$source)) {
            this["semanticLinks"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageServerSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageServerSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanguageServerSettings($$parsedSource as Partial<LanguageServerSettings>);
    }
}

export enum LanguageServerState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LanguageServerStopped = "stopped",
    LanguageServerStarting = "starting",
    LanguageServerReady = "ready",
    LanguageServerCrashed = "crashed",
    LanguageServerUnavailable = "unavailable",
};

export class LanguageServerStatus {
    "sessionId": SessionID;
    "state": LanguageServerState;
    "binary"?: string;
    "version"?: string;
    "pid"?: number;
    "restarts": number;
    "error"?: string;

    /**
     * Features elenca ciò che il gopls in esecuzione supporta davvero: l'editor nasconde il resto.
     */
    "features"?: LanguageServerFeatures | null;

    /** Creates a new LanguageServerStatus instance. */
    constructor($$source: Partial<LanguageServerStatus> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = LanguageServerState.$zero;
        }
        if (!("restarts" in $$source)) {
            this["restarts"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageServerStatus {
        const $$createField7_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("features" in $$parsedSource) {
            $$parsedSource["features"] = $$createField7_0($$parsedSource["features"]);
        }
        return new LanguageServerStatus($$parsedSource as Partial<LanguageServerStatus>);
    }
}

export class LintResult {
    "linter": string;
    "reports": DiagnosticsReport[];
    "issueCount": number;
    "truncated": boolean;
    "durationMs": number;

    /** Creates a new LintResult instance. */
    constructor($$source: Partial<LintResult> = {}) {
        if (!("linter" in $$source)) {
            this["linter"] = "";
        }
        if (!("reports" in $$source)) {
            this["reports"] = [];
        }
        if (!("issueCount" in $$source)) {
            this["issueCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LintResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LintResult {
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reports" in $$parsedSource) {
            $$parsedSource["reports"] = $$createField1_0($$parsedSource["reports"]);
        }
        return new LintResult($$parsedSource as Partial<LintResult>);
    }
}

export class LinterInfo {
    "available": boolean;
    "kind"?: string;
    "binary"?: string;
    "version"?: string;
    "source"?: string;
    "configPath"?: string;
    "error"?: string;

    /** Creates a new LinterInfo instance. */
    constructor($$source: Partial<LinterInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LinterInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinterInfo($$parsedSource as Partial<LinterInfo>);
    }
}

export class OpenDocument {
    "document": Document;
    "content": string;
    "diskToken": string;
    "modifiedAt": string;

    /** Creates a new OpenDocument instance. */
    constructor($$source: Partial<OpenDocument> = {}) {
        if (!("document" in $$source)) {
            this["document"] = (new Document());
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("diskToken" in $$source)) {
            this["diskToken"] = "";
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenDocument instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenDocument {
        const $$createField0_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("document" in $$parsedSource) {
            $$parsedSource["document"] = $$createField0_0($$parsedSource["document"]);
        }
        return new OpenDocument($$parsedSource as Partial<OpenDocument>);
    }
}

export class Project {
    "id": string;
    "name": string;
    "rootPath": string;
    "realPath": string;
    "goModPath"?: string;
    "goWorkPath"?: string;
    "modules": GoModule[];
    "looseGoDirs"?: string[];
    "authorization": AuthorizationState;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rootPath" in $$source)) {
            this["rootPath"] = "";
        }
        if (!("realPath" in $$source)) {
            this["realPath"] = "";
        }
        if (!("modules" in $$source)) {
            this["modules"] = [];
        }
        if (!("authorization" in $$source)) {
            this["authorization"] = AuthorizationState.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        const $$createField6_0 = $$createType25;
        const $$createField7_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modules" in $$parsedSource) {
            $$parsedSource["modules"] = $$createField6_0($$parsedSource["modules"]);
        }
        if ("looseGoDirs" in $$parsedSource) {
            $$parsedSource["looseGoDirs"] = $$createField7_0($$parsedSource["looseGoDirs"]);
        }
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * QuickDefinitionResult è il sorgente della dichiarazione da mostrare in popup, senza lasciare il file corrente.
 */
export class QuickDefinitionResult {
    "found": boolean;
    "location": EditorLocation;
    "code": string;
    "startLine": number;
    "truncated": boolean;

    /** Creates a new QuickDefinitionResult instance. */
    constructor($$source: Partial<QuickDefinitionResult> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("location" in $$source)) {
            this["location"] = (new EditorLocation());
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickDefinitionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuickDefinitionResult {
        const $$createField1_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("location" in $$parsedSource) {
            $$parsedSource["location"] = $$createField1_0($$parsedSource["location"]);
        }
        return new QuickDefinitionResult($$parsedSource as Partial<QuickDefinitionResult>);
    }
}

export class QuickOpenResult {
    "name": string;
    "relativePath": string;
    "language": string;

    /** Creates a new QuickOpenResult instance. */
    constructor($$source: Partial<QuickOpenResult> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickOpenResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QuickOpenResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickOpenResult($$parsedSource as Partial<QuickOpenResult>);
    }
}

export class RecentProject {
    "name": string;
    "rootPath": string;
    "realPath": string;
    "available": boolean;
    "openedAt": string;

    /** Creates a new RecentProject instance. */
    constructor($$source: Partial<RecentProject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rootPath" in $$source)) {
            this["rootPath"] = "";
        }
        if (!("realPath" in $$source)) {
            this["realPath"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("openedAt" in $$source)) {
            this["openedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentProject instance from a string or object.
     */
    static createFrom($$source: any = {}): RecentProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentProject($$parsedSource as Partial<RecentProject>);
    }
}

/**
 * RecoveredBuffer è un buffer non salvato ritrovato dopo un riavvio: viene
 * proposto all'utente come recupero esplicito, mai riapplicato da solo.
 */
export class RecoveredBuffer {
    "sessionId": SessionID;
    "relativePath": string;
    "content": string;
    "savedAt": string;
    "diskChanged": boolean;
    "missing": boolean;

    /** Creates a new RecoveredBuffer instance. */
    constructor($$source: Partial<RecoveredBuffer> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("savedAt" in $$source)) {
            this["savedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("diskChanged" in $$source)) {
            this["diskChanged"] = false;
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecoveredBuffer instance from a string or object.
     */
    static createFrom($$source: any = {}): RecoveredBuffer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecoveredBuffer($$parsedSource as Partial<RecoveredBuffer>);
    }
}

export class RecursiveCall {
    "function": string;
    "range": EditorRange;

    /** Creates a new RecursiveCall instance. */
    constructor($$source: Partial<RecursiveCall> = {}) {
        if (!("function" in $$source)) {
            this["function"] = "";
        }
        if (!("range" in $$source)) {
            this["range"] = (new EditorRange());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecursiveCall instance from a string or object.
     */
    static createFrom($$source: any = {}): RecursiveCall {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField1_0($$parsedSource["range"]);
        }
        return new RecursiveCall($$parsedSource as Partial<RecursiveCall>);
    }
}

export class RecursiveCallsResult {
    "version": number;
    "calls": RecursiveCall[];

    /** Creates a new RecursiveCallsResult instance. */
    constructor($$source: Partial<RecursiveCallsResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("calls" in $$source)) {
            this["calls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecursiveCallsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RecursiveCallsResult {
        const $$createField1_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("calls" in $$parsedSource) {
            $$parsedSource["calls"] = $$createField1_0($$parsedSource["calls"]);
        }
        return new RecursiveCallsResult($$parsedSource as Partial<RecursiveCallsResult>);
    }
}

export class RenameTarget {
    "version": number;
    "range": EditorRange;
    "placeholder": string;

    /** Creates a new RenameTarget instance. */
    constructor($$source: Partial<RenameTarget> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("range" in $$source)) {
            this["range"] = (new EditorRange());
        }
        if (!("placeholder" in $$source)) {
            this["placeholder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameTarget {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField1_0($$parsedSource["range"]);
        }
        return new RenameTarget($$parsedSource as Partial<RenameTarget>);
    }
}

export class RunConfiguration {
    "id": string;
    "sessionId": SessionID;
    "name": string;
    "kind": RunConfigurationKind;
    "target": string;
    "files"?: string[];
    "binaryPath"?: string;
    "workingDirectory": string;
    "goArguments": string[];
    "programArguments": string[];
    "buildTags": string[];
    "environment": EnvironmentEntry[];
    "order": number;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new RunConfiguration instance. */
    constructor($$source: Partial<RunConfiguration> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = RunConfigurationKind.$zero;
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }
        if (!("goArguments" in $$source)) {
            this["goArguments"] = [];
        }
        if (!("programArguments" in $$source)) {
            this["programArguments"] = [];
        }
        if (!("buildTags" in $$source)) {
            this["buildTags"] = [];
        }
        if (!("environment" in $$source)) {
            this["environment"] = [];
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunConfiguration instance from a string or object.
     */
    static createFrom($$source: any = {}): RunConfiguration {
        const $$createField5_0 = $$createType18;
        const $$createField8_0 = $$createType18;
        const $$createField9_0 = $$createType18;
        const $$createField10_0 = $$createType18;
        const $$createField11_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField5_0($$parsedSource["files"]);
        }
        if ("goArguments" in $$parsedSource) {
            $$parsedSource["goArguments"] = $$createField8_0($$parsedSource["goArguments"]);
        }
        if ("programArguments" in $$parsedSource) {
            $$parsedSource["programArguments"] = $$createField9_0($$parsedSource["programArguments"]);
        }
        if ("buildTags" in $$parsedSource) {
            $$parsedSource["buildTags"] = $$createField10_0($$parsedSource["buildTags"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField11_0($$parsedSource["environment"]);
        }
        return new RunConfiguration($$parsedSource as Partial<RunConfiguration>);
    }
}

/**
 * RunConfigurationKind elenca i perimetri di esecuzione supportati da una configurazione salvata.
 */
export enum RunConfigurationKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RunKindPackage = "package",
    RunKindFiles = "files",
    RunKindBuild = "build",
    RunKindBinary = "binary",
    RunKindTest = "test",
};

export type RunID = string;

export class RunRequest {
    "sessionId": SessionID;
    "kind": string;
    "target": string;

    /**
     * ExtraTargets contiene i target aggiuntivi di una configurazione a lista
     * di file: vengono accodati subito dopo Target, prima degli argomenti del
     * programma, per rispettare l'ordine richiesto da `go run`.
     */
    "extraTargets"?: string[];
    "workingDirectory": string;
    "goArguments": string[];
    "programArguments": string[];
    "buildTags": string[];
    "environment": { [_ in string]?: string };

    /** Creates a new RunRequest instance. */
    constructor($$source: Partial<RunRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }
        if (!("goArguments" in $$source)) {
            this["goArguments"] = [];
        }
        if (!("programArguments" in $$source)) {
            this["programArguments"] = [];
        }
        if (!("buildTags" in $$source)) {
            this["buildTags"] = [];
        }
        if (!("environment" in $$source)) {
            this["environment"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RunRequest {
        const $$createField3_0 = $$createType18;
        const $$createField5_0 = $$createType18;
        const $$createField6_0 = $$createType18;
        const $$createField7_0 = $$createType18;
        const $$createField8_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extraTargets" in $$parsedSource) {
            $$parsedSource["extraTargets"] = $$createField3_0($$parsedSource["extraTargets"]);
        }
        if ("goArguments" in $$parsedSource) {
            $$parsedSource["goArguments"] = $$createField5_0($$parsedSource["goArguments"]);
        }
        if ("programArguments" in $$parsedSource) {
            $$parsedSource["programArguments"] = $$createField6_0($$parsedSource["programArguments"]);
        }
        if ("buildTags" in $$parsedSource) {
            $$parsedSource["buildTags"] = $$createField7_0($$parsedSource["buildTags"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField8_0($$parsedSource["environment"]);
        }
        return new RunRequest($$parsedSource as Partial<RunRequest>);
    }
}

export class SearchMatch {
    "relativePath": string;
    "line": number;
    "column": number;
    "endColumn": number;
    "preview": string;

    /** Creates a new SearchMatch instance. */
    constructor($$source: Partial<SearchMatch> = {}) {
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("endColumn" in $$source)) {
            this["endColumn"] = 0;
        }
        if (!("preview" in $$source)) {
            this["preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchMatch($$parsedSource as Partial<SearchMatch>);
    }
}

export class SearchQuery {
    "sessionId": SessionID;
    "pattern": string;
    "regex": boolean;
    "caseSensitive": boolean;
    "wholeWord": boolean;
    "include": string[];
    "exclude": string[];

    /** Creates a new SearchQuery instance. */
    constructor($$source: Partial<SearchQuery> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("regex" in $$source)) {
            this["regex"] = false;
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("wholeWord" in $$source)) {
            this["wholeWord"] = false;
        }
        if (!("include" in $$source)) {
            this["include"] = [];
        }
        if (!("exclude" in $$source)) {
            this["exclude"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchQuery {
        const $$createField5_0 = $$createType18;
        const $$createField6_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("include" in $$parsedSource) {
            $$parsedSource["include"] = $$createField5_0($$parsedSource["include"]);
        }
        if ("exclude" in $$parsedSource) {
            $$parsedSource["exclude"] = $$createField6_0($$parsedSource["exclude"]);
        }
        return new SearchQuery($$parsedSource as Partial<SearchQuery>);
    }
}

export class SearchResult {
    "matches": SearchMatch[];
    "filesScanned": number;
    "truncated": boolean;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }
        if (!("filesScanned" in $$source)) {
            this["filesScanned"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField0_0($$parsedSource["matches"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class SemanticTokensResult {
    "version": number;
    "data": number[];

    /** Creates a new SemanticTokensResult instance. */
    constructor($$source: Partial<SemanticTokensResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SemanticTokensResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SemanticTokensResult {
        const $$createField1_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new SemanticTokensResult($$parsedSource as Partial<SemanticTokensResult>);
    }
}

export class Session {
    "id": SessionID;
    "project": Project;
    "openedAt": string;
    "updatedAt": string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project" in $$source)) {
            this["project"] = (new Project());
        }
        if (!("openedAt" in $$source)) {
            this["openedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField1_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField1_0($$parsedSource["project"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export type SessionID = string;

/**
 * SessionView è lo stato di interfaccia ripristinabile di una sessione: quali
 * file erano aperti, quale era attivo e come era disposto il layout. Non
 * contiene mai il contenuto dei file.
 */
export class SessionView {
    "openPaths"?: string[];
    "activePath"?: string;
    "activeConfigId"?: string;
    "projectWidth"?: number;
    "structureWidth"?: number;
    "bottomHeight"?: number;
    "structureOpen": boolean;
    "bottomOpen": boolean;
    "terminalPanelOpen": boolean;
    "showIgnoredEntries": boolean;

    /** Creates a new SessionView instance. */
    constructor($$source: Partial<SessionView> = {}) {
        if (!("structureOpen" in $$source)) {
            this["structureOpen"] = false;
        }
        if (!("bottomOpen" in $$source)) {
            this["bottomOpen"] = false;
        }
        if (!("terminalPanelOpen" in $$source)) {
            this["terminalPanelOpen"] = false;
        }
        if (!("showIgnoredEntries" in $$source)) {
            this["showIgnoredEntries"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionView instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionView {
        const $$createField0_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("openPaths" in $$parsedSource) {
            $$parsedSource["openPaths"] = $$createField0_0($$parsedSource["openPaths"]);
        }
        return new SessionView($$parsedSource as Partial<SessionView>);
    }
}

export class SignatureEntry {
    "label": string;
    "documentation"?: string;
    "parameters": SignatureParameter[];

    /** Creates a new SignatureEntry instance. */
    constructor($$source: Partial<SignatureEntry> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("parameters" in $$source)) {
            this["parameters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignatureEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SignatureEntry {
        const $$createField2_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parameters" in $$parsedSource) {
            $$parsedSource["parameters"] = $$createField2_0($$parsedSource["parameters"]);
        }
        return new SignatureEntry($$parsedSource as Partial<SignatureEntry>);
    }
}

export class SignatureParameter {
    "label": string;
    "documentation"?: string;

    /** Creates a new SignatureParameter instance. */
    constructor($$source: Partial<SignatureParameter> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignatureParameter instance from a string or object.
     */
    static createFrom($$source: any = {}): SignatureParameter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SignatureParameter($$parsedSource as Partial<SignatureParameter>);
    }
}

export class SignatureResult {
    "version": number;
    "signatures": SignatureEntry[];
    "activeSignature": number;
    "activeParameter": number;

    /** Creates a new SignatureResult instance. */
    constructor($$source: Partial<SignatureResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("signatures" in $$source)) {
            this["signatures"] = [];
        }
        if (!("activeSignature" in $$source)) {
            this["activeSignature"] = 0;
        }
        if (!("activeParameter" in $$source)) {
            this["activeParameter"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SignatureResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SignatureResult {
        const $$createField1_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("signatures" in $$parsedSource) {
            $$parsedSource["signatures"] = $$createField1_0($$parsedSource["signatures"]);
        }
        return new SignatureResult($$parsedSource as Partial<SignatureResult>);
    }
}

export class SymbolNode {
    "name": string;
    "detail"?: string;
    "kind": number;
    "range": EditorRange;
    "selectionRange": EditorRange;
    "children"?: SymbolNode[];

    /** Creates a new SymbolNode instance. */
    constructor($$source: Partial<SymbolNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = 0;
        }
        if (!("range" in $$source)) {
            this["range"] = (new EditorRange());
        }
        if (!("selectionRange" in $$source)) {
            this["selectionRange"] = (new EditorRange());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SymbolNode instance from a string or object.
     */
    static createFrom($$source: any = {}): SymbolNode {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField3_0($$parsedSource["range"]);
        }
        if ("selectionRange" in $$parsedSource) {
            $$parsedSource["selectionRange"] = $$createField4_0($$parsedSource["selectionRange"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new SymbolNode($$parsedSource as Partial<SymbolNode>);
    }
}

export type TerminalID = string;

/**
 * TerminalRequest descrive l'apertura di un nuovo terminale.
 */
export class TerminalRequest {
    "sessionId": SessionID;
    "name": string;
    "shell"?: string;
    "shellArguments"?: string[];
    "workingDirectory"?: string;
    "environment"?: { [_ in string]?: string };
    "columns"?: number;
    "rows"?: number;

    /** Creates a new TerminalRequest instance. */
    constructor($$source: Partial<TerminalRequest> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalRequest {
        const $$createField3_0 = $$createType18;
        const $$createField5_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shellArguments" in $$parsedSource) {
            $$parsedSource["shellArguments"] = $$createField3_0($$parsedSource["shellArguments"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField5_0($$parsedSource["environment"]);
        }
        return new TerminalRequest($$parsedSource as Partial<TerminalRequest>);
    }
}

/**
 * TerminalSession descrive un terminale interattivo dal punto di vista dell'interfaccia.
 */
export class TerminalSession {
    "id": TerminalID;
    "sessionId": SessionID;
    "name": string;
    "shell": string;
    "workingDirectory": string;
    "status": string;
    "pid"?: number;
    "startedAt": string;
    "exitedAt"?: string | null;
    "exitCode"?: number | null;
    "error"?: string;

    /** Creates a new TerminalSession instance. */
    constructor($$source: Partial<TerminalSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("shell" in $$source)) {
            this["shell"] = "";
        }
        if (!("workingDirectory" in $$source)) {
            this["workingDirectory"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSession instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalSession($$parsedSource as Partial<TerminalSession>);
    }
}

export class ToolchainConfiguration {
    "goBinary": string;
    "environment"?: { [_ in string]?: string };

    /** Creates a new ToolchainConfiguration instance. */
    constructor($$source: Partial<ToolchainConfiguration> = {}) {
        if (!("goBinary" in $$source)) {
            this["goBinary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainConfiguration instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainConfiguration {
        const $$createField1_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField1_0($$parsedSource["environment"]);
        }
        return new ToolchainConfiguration($$parsedSource as Partial<ToolchainConfiguration>);
    }
}

export class ToolchainInfo {
    "available": boolean;
    "goBinary"?: string;
    "version"?: string;
    "goroot"?: string;
    "gopath"?: string;
    "goproxy"?: string;
    "goprivate"?: string;
    "gomodcache"?: string;
    "error"?: string;

    /** Creates a new ToolchainInfo instance. */
    constructor($$source: Partial<ToolchainInfo> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolchainInfo($$parsedSource as Partial<ToolchainInfo>);
    }
}

export class ToolchainInstallation {
    "id": string;
    "sessionId": SessionID;
    "version": string;
    "status": string;
    "downloadedBytes": number;
    "totalBytes": number;
    "message"?: string;
    "goBinary"?: string;
    "log": string[];

    /** Creates a new ToolchainInstallation instance. */
    constructor($$source: Partial<ToolchainInstallation> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("downloadedBytes" in $$source)) {
            this["downloadedBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("log" in $$source)) {
            this["log"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainInstallation instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainInstallation {
        const $$createField8_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField8_0($$parsedSource["log"]);
        }
        return new ToolchainInstallation($$parsedSource as Partial<ToolchainInstallation>);
    }
}

export class ToolchainRelease {
    "version": string;
    "filename": string;
    "sha256": string;
    "size": number;
    "stable": boolean;
    "os": string;
    "arch": string;

    /** Creates a new ToolchainRelease instance. */
    constructor($$source: Partial<ToolchainRelease> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("stable" in $$source)) {
            this["stable"] = false;
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolchainRelease instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolchainRelease {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolchainRelease($$parsedSource as Partial<ToolchainRelease>);
    }
}

export class WorkspaceChange {
    "label"?: string;
    "files": FileChange[];

    /** Creates a new WorkspaceChange instance. */
    constructor($$source: Partial<WorkspaceChange> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceChange instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceChange {
        const $$createField1_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new WorkspaceChange($$parsedSource as Partial<WorkspaceChange>);
    }
}

export class WorkspaceSymbol {
    "name": string;
    "kind": number;
    "container"?: string;
    "location": EditorLocation;

    /** Creates a new WorkspaceSymbol instance. */
    constructor($$source: Partial<WorkspaceSymbol> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = 0;
        }
        if (!("location" in $$source)) {
            this["location"] = (new EditorLocation());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSymbol instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceSymbol {
        const $$createField3_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("location" in $$parsedSource) {
            $$parsedSource["location"] = $$createField3_0($$parsedSource["location"]);
        }
        return new WorkspaceSymbol($$parsedSource as Partial<WorkspaceSymbol>);
    }
}

// Private type creation functions
const $$createType0 = EditorRange.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = EditorTextEdit.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = CompletionEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = GoDependency.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = GoReplacement.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = EditorDiagnostic.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = SymbolNode.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = HighlightEntry.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = InlayHintEntry.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($Create.Any);
const $$createType19 = LanguageServerFeatures.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = DiagnosticsReport.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = Document.createFrom;
const $$createType24 = GoModule.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = EditorLocation.createFrom;
const $$createType27 = RecursiveCall.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = EnvironmentEntry.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = $Create.Map($Create.Any, $Create.Any);
const $$createType32 = SearchMatch.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = $Create.Array($Create.Any);
const $$createType35 = Project.createFrom;
const $$createType36 = SignatureParameter.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = SignatureEntry.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = FileChange.createFrom;
const $$createType41 = $Create.Array($$createType40);
