// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum AuthorizationState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthorizationOpened = "opened",
    AuthorizationPermitted = "tooling-permitted",
};

export class Capabilities {
    "schemaVersion": number;
    "projectOpen": boolean;
    "projectCreate": boolean;
    "documents": boolean;
    "toolchain": boolean;
    "processes": boolean;
    "lsp": boolean;
    "terminal": boolean;
    "debug": boolean;
    "tests": boolean;
    "multipleSessions": boolean;
    "separateWindows": boolean;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("projectOpen" in $$source)) {
            this["projectOpen"] = false;
        }
        if (!("projectCreate" in $$source)) {
            this["projectCreate"] = false;
        }
        if (!("documents" in $$source)) {
            this["documents"] = false;
        }
        if (!("toolchain" in $$source)) {
            this["toolchain"] = false;
        }
        if (!("processes" in $$source)) {
            this["processes"] = false;
        }
        if (!("lsp" in $$source)) {
            this["lsp"] = false;
        }
        if (!("terminal" in $$source)) {
            this["terminal"] = false;
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("tests" in $$source)) {
            this["tests"] = false;
        }
        if (!("multipleSessions" in $$source)) {
            this["multipleSessions"] = false;
        }
        if (!("separateWindows" in $$source)) {
            this["separateWindows"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

export class GoModule {
    "path": string;
    "modulePath"?: string;

    /** Creates a new GoModule instance. */
    constructor($$source: Partial<GoModule> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GoModule instance from a string or object.
     */
    static createFrom($$source: any = {}): GoModule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GoModule($$parsedSource as Partial<GoModule>);
    }
}

export class Project {
    "id": string;
    "name": string;
    "rootPath": string;
    "realPath": string;
    "goModPath"?: string;
    "goWorkPath"?: string;
    "modules": GoModule[];
    "authorization": AuthorizationState;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rootPath" in $$source)) {
            this["rootPath"] = "";
        }
        if (!("realPath" in $$source)) {
            this["realPath"] = "";
        }
        if (!("modules" in $$source)) {
            this["modules"] = [];
        }
        if (!("authorization" in $$source)) {
            this["authorization"] = AuthorizationState.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modules" in $$parsedSource) {
            $$parsedSource["modules"] = $$createField6_0($$parsedSource["modules"]);
        }
        return new Project($$parsedSource as Partial<Project>);
    }
}

export class Session {
    "id": SessionID;
    "project": Project;
    "openedAt": string;
    "updatedAt": string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project" in $$source)) {
            this["project"] = (new Project());
        }
        if (!("openedAt" in $$source)) {
            this["openedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField1_0($$parsedSource["project"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export type SessionID = string;

// Private type creation functions
const $$createType0 = GoModule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Project.createFrom;
