// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Unit è un'unità di build riconosciuta da un language adapter dentro la cartella del progetto.
 */
export class Unit {
    /**
     * Language è l'ID del linguaggio che l'ha rilevata (es. "go").
     */
    "language": string;

    /**
     * Kind è il tipo di unità per quel linguaggio (es. "module", "workspace", "loose").
     */
    "kind": string;

    /**
     * Root è la cartella dell'unità, assoluta.
     */
    "root": string;

    /**
     * Name è il nome logico (module path, artifactId, nome del pacchetto); può essere vuoto.
     */
    "name"?: string;

    /**
     * Manifest è il file che definisce l'unità (es. "go.mod"), assoluto; vuoto se non c'è.
     */
    "manifest"?: string;

    /** Creates a new Unit instance. */
    constructor($$source: Partial<Unit> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Unit instance from a string or object.
     */
    static createFrom($$source: any = {}): Unit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Unit($$parsedSource as Partial<Unit>);
    }
}
