import type { Lang } from '@/lib/i18n'

// Every in-game string lives here. The English shape is the contract, so a
// missing Italian line fails type-checking instead of showing up blank.
const en = {
  dashReady: 'DASH READY', dashCharging: 'DASH CHARGING', keysDash: 'dash',
  // developer power-ups
  powerRevert: '+1 git revert  ·  press R',
  powerBreakpoint: 'BREAKPOINT HIT  ·  world paused',
  powerSudo: 'sudo !!  ·  root access granted',
  powerGc: 'GARBAGE COLLECTOR  ·  memory freed',
  revertUsed: 'git revert HEAD~3s',
  revertEmpty: 'No revert left. Find a ↺ chip.',
  freed: (address: string) => `free(${address}) ✓`,
  breakpointBanner: 'Paused on breakpoint',
  sudoBanner: 'root@a0:~#',
  rewindBanner: 'git revert',
  keysRevert: 'git revert',
  powersIntro: 'Power-ups: ↺ git revert (R) · ⏸ Breakpoint · # sudo · ♻ Garbage Collector.',
  statScore: 'Score', statCombo: 'Best chain',
  nextLevel: 'Next environment', stageClear: 'Hotfix secured!',
  stageHints: ['Space twice: double jump. X: dash through bugs. Follow the glowing launch trails!', 'Dash through firewalls with X. Chain bits and bugs to boost your score!', 'Platforms crumble: keep moving. Jump over the wave, then land on the green core.'],
  bossDefeated: 'LEGACY REFACTORED!', bossWarning: 'WAVE INCOMING / JUMP',
  bossOpen: 'CORE OPEN / JUMP ON TOP', bossLocked: 'CORE SHIELDED',
  dialogLabel: 'a0: Bug Hunt',
  brandSubtitle: '01 / LOCALHOST · FRIDAY DEPLOY',
  audioOn: 'Mute audio',
  audioOff: 'Unmute audio',
  gentle: 'Gentle effects',
  gentleTitle: 'Gentle effects: fewer particles, no screen shake',
  pause: 'Pause',
  resume: 'Resume',
  pauseTitle: 'Pause · Esc',
  backToApp: 'Back to adOmnia',
  canvasLabel: 'Bug Hunt: platforms, bits and bugs. Use A/D or the arrows to move and Space to jump.',
  hudLabel: 'Game status',
  healthLabel: (health: number) => `${health} of 3 health points`,
  hotfixFound: 'HOTFIX ✓',
  findHotfix: 'FIND THE HOTFIX',
  introEyebrow: 'Friday, 5:59 PM',
  winEyebrow: 'Pipeline green · Production is safe',
  pauseEyebrow: 'Deploy paused',
  introTitle: 'A tiny deploy.',
  introTitleAccent: 'A huge problem.',
  introQuote: '“It works on my machine.”',
  introBody: 'The bugs escaped from the terminals. You are a0: jump on them, grab the bits and save the weekend.',
  missionTitle: 'Recover the Hotfix. Light up the pipeline.',
  missionBody: 'There is a secret branch too, for anyone who can’t resist a detour.',
  start: 'Save the weekend',
  introTip: 'Space again in the air to recover a jump. X or Shift to dash. Chain pickups for up to x5 points.',
  record: (time: string) => ` Your record: ${time}.`,
  winTitle: 'Build passed.',
  winTitleAccent: 'Breathe, a0.',
  winBody: 'Production is safe again. This time it really works.',
  statTime: 'Time',
  statBits: 'Bits collected',
  statDeaths: 'Deaths',
  medalRecord: 'New personal best',
  medalSecret: 'Secret branch found',
  medalBugs: 'Every ticket closed',
  winQuote: 'New ticket: “The button is slightly off.”',
  playAgain: 'One more run',
  backToWork: 'Back to work',
  pauseTitle1: 'The deploy',
  pauseTitle2: 'can wait.',
  pauseBodyCheckpoint: 'Your checkpoint is safe. Pick it up whenever you like.',
  pauseBody: 'Take a moment. a0 will wait right here.',
  restart: 'Restart campaign',
  exit: 'Exit',
  pauseTip: 'Esc to resume · Audio and effects live up top.',
  keysMove: 'move',
  keysJump: 'double jump',
  keysPause: 'pause',
  keySpace: 'Space',
  checkpointSaved: 'Checkpoint saved',
  findCheckpoint: 'Find the checkpoint',
  // canvas popups
  retry: 'New attempt. You’re close.',
  rollback: 'Rollback successful.',
  notAFeature: 'That wasn’t a feature.',
  secretFound: 'SECRET BRANCH!  git stash happiness',
  bits: (n: number) => `${n} BITS!`,
  hotfixPickup: 'HOTFIX FOUND  ·  Go deploy!',
  bugClosed: ['BUG CLOSED ✓', 'Ticket resolved. For real.', 'Last bug? Don’t say it.'],
  commitSaved: 'COMMIT SAVED ✓',
  missingHotfix: 'Missing the Hotfix! ←',
  // canvas signs
  signFriday: '5:59 PM  ·  FRIDAY',
  signFridayQuote: '“It’s just a small change.”',
  signBug: 'BUG IN PRODUCTION',
  signBugHint: 'Jump on it. Then close the ticket.',
  signCommit: 'GIT COMMIT',
  signCommitSaved: 'Checkpoint saved. Breathe.',
  signCommitHint: 'Respawn here, no fear.',
  signPush: 'LAST PUSH',
  signPushHint: 'The weekend is on the other side.',
  signSurprise: '↗  git checkout surprise',
  signSecret: '// SECRET BRANCH',
  gatePassed: 'BUILD PASSED',
  gateLocked: 'HOTFIX REQUIRED',
}

export type BugHuntCopy = typeof en

const it: BugHuntCopy = {
  dashReady: 'SCATTO PRONTO', dashCharging: 'SCATTO IN RICARICA', keysDash: 'scatto',
  powerRevert: '+1 git revert  ·  premi R',
  powerBreakpoint: 'BREAKPOINT  ·  mondo in pausa',
  powerSudo: 'sudo !!  ·  accesso root',
  powerGc: 'GARBAGE COLLECTOR  ·  memoria liberata',
  revertUsed: 'git revert HEAD~3s',
  revertEmpty: 'Nessun revert. Cerca un chip ↺.',
  freed: (address) => `free(${address}) ✓`,
  breakpointBanner: 'In pausa sul breakpoint',
  sudoBanner: 'root@a0:~#',
  rewindBanner: 'git revert',
  keysRevert: 'git revert',
  powersIntro: 'Poteri: ↺ git revert (R) · ⏸ Breakpoint · # sudo · ♻ Garbage Collector.',
  statScore: 'Punteggio', statCombo: 'Serie migliore',
  nextLevel: 'Prossimo ambiente', stageClear: 'Hotfix al sicuro!',
  stageHints: ['Spazio due volte: doppio salto. X: travolgi i bug. Segui le scie delle rampe!', 'Attraversa i firewall con X. Colleziona bit e bug in serie per fare punti!', 'Le piattaforme cedono: continua a muoverti. Salta l’onda, poi atterra sul nucleo verde.'],
  bossDefeated: 'LEGACY REFACTORED!', bossWarning: 'ONDA IN ARRIVO / SALTA',
  bossOpen: 'NUCLEO APERTO / SALTACI SOPRA', bossLocked: 'NUCLEO PROTETTO',
  dialogLabel: 'a0: Bug Hunt',
  brandSubtitle: '01 / LOCALHOST · DEPLOY DEL VENERDÌ',
  audioOn: 'Disattiva audio',
  audioOff: 'Attiva audio',
  gentle: 'Effetti delicati',
  gentleTitle: 'Effetti delicati: meno particelle, niente scuotimenti',
  pause: 'Pausa',
  resume: 'Riprendi',
  pauseTitle: 'Pausa · Esc',
  backToApp: 'Torna ad adOmnia',
  canvasLabel: 'Bug Hunt: piattaforme, bit e bug. Usa A/D o le frecce per muoverti e Spazio per saltare.',
  hudLabel: 'Stato partita',
  healthLabel: (health) => `${health} punti salute su 3`,
  hotfixFound: 'HOTFIX ✓',
  findHotfix: 'TROVA L’HOTFIX',
  introEyebrow: 'Venerdì, ore 17:59',
  winEyebrow: 'Pipeline verde · Production al sicuro',
  pauseEyebrow: 'Deploy in pausa',
  introTitle: 'Un piccolo deploy.',
  introTitleAccent: 'Un grosso problema.',
  introQuote: '«Sul mio computer funzionava.»',
  introBody: 'I bug sono scappati dai terminali. Tu sei a0: saltaci sopra, raccogli i bit e salva il weekend.',
  missionTitle: 'Recupera l’Hotfix. Accendi la pipeline.',
  missionBody: 'C’è anche un ramo segreto, per chi non sa resistere a una deviazione.',
  start: 'Salviamo il weekend',
  introTip: 'Premi ancora Spazio in aria per recuperare un salto. X o Shift per scattare. Raccogli in serie per punti fino a x5.',
  record: (time) => ` Il tuo record: ${time}.`,
  winTitle: 'Build passed.',
  winTitleAccent: 'Respira, a0.',
  winBody: 'Production è di nuovo al sicuro. Stavolta funziona davvero.',
  statTime: 'Tempo',
  statBits: 'Bit raccolti',
  statDeaths: 'Morti',
  medalRecord: 'Nuovo record personale',
  medalSecret: 'Ramo segreto trovato',
  medalBugs: 'Tutti i ticket chiusi',
  winQuote: 'Nuovo ticket: «Il pulsante è leggermente spostato.»',
  playAgain: 'Un’altra partita',
  backToWork: 'Torna al lavoro',
  pauseTitle1: 'Il deploy',
  pauseTitle2: 'può aspettare.',
  pauseBodyCheckpoint: 'Il checkpoint è al sicuro. Riparti quando vuoi.',
  pauseBody: 'Prenditi un momento. a0 ti aspetta qui.',
  restart: 'Ricomincia campagna',
  exit: 'Esci',
  pauseTip: 'Esc per riprendere · Audio ed effetti si regolano in alto.',
  keysMove: 'muovi',
  keysJump: 'doppio salto',
  keysPause: 'pausa',
  keySpace: 'Spazio',
  checkpointSaved: 'Checkpoint salvato',
  findCheckpoint: 'Trova il checkpoint',
  retry: 'Nuovo tentativo. Ci sei quasi.',
  rollback: 'Rollback riuscito.',
  notAFeature: 'Non era una feature.',
  secretFound: 'RAMO SEGRETO!  git stash felicità',
  bits: (n) => `${n} BIT!`,
  hotfixPickup: 'HOTFIX TROVATO  ·  Vai al deploy!',
  bugClosed: ['BUG CHIUSO ✓', 'Ticket risolto. Per davvero.', 'Ultimo bug? Non dirlo.'],
  commitSaved: 'COMMIT SALVATO ✓',
  missingHotfix: 'Manca l’Hotfix! ←',
  signFriday: '17:59  ·  VENERDÌ',
  signFridayQuote: '«È solo una piccola modifica.»',
  signBug: 'BUG IN PRODUZIONE',
  signBugHint: 'Saltaci sopra. Poi chiudi il ticket.',
  signCommit: 'GIT COMMIT',
  signCommitSaved: 'Checkpoint salvato. Respira.',
  signCommitHint: 'Qui puoi ripartire senza paura.',
  signPush: 'ULTIMO PUSH',
  signPushHint: 'Il weekend è dall’altra parte.',
  signSurprise: '↗  git checkout sorpresa',
  signSecret: '// RAMO SEGRETO',
  gatePassed: 'BUILD PASSED',
  gateLocked: 'HOTFIX RICHIESTO',
}

export const BUG_HUNT_COPY: Record<Lang, BugHuntCopy> = { en, it }
