import type { Lang } from '@/lib/i18n'

// Every in-game string lives here. The English shape is the contract, so a
// missing Italian line fails type-checking instead of showing up blank.
const en = {
  nullLocked: 'Defeat NullPointer first! ←', cpuWarning: 'CPU 97% · scenery slowed / controls online',
  gravitySafe: 'GRAVITY SAFE ZONE ↓', lessonHint: 'Read the warning. The floor remains a safe way out.',
  bossPhases: ['SOAP STORM', 'LEGACY OVERRIDE', 'MONOLITH PANIC MODE'],
  gameOverTitle: 'Out of lives.', gameOverBody: 'No lives left for this deploy. Start a new campaign and try again.',
  rewindQuip: 'It worked on my machine.', checkpointQuip: 'Committed. Breathe.', edgeQuip: 'Totally intentional.',
  bossDoubleWave: 'DOUBLE SOAP / DOUBLE JUMP',
  rushStart: 'BONUS RUSH! 6 bits / 8 seconds', rushWon: 'RUSH COMPLETE! +500',
  rushLabel: 'BONUS RUSH', rank: 'Rank', rushMedal: 'Bonus rushes',
  chainHint: 'Every bug hit recharges your dash. Stomp, dash, repeat!',
  dashReady: 'DASH READY', dashCharging: 'DASH CHARGING', keysDash: 'dash',
  // developer power-ups
  powerRevert: '+1 git revert  ·  press R',
  powerBreakpoint: 'BREAKPOINT HIT  ·  world paused',
  powerSudo: 'sudo !!  ·  root access granted',
  powerGc: 'GARBAGE COLLECTOR  ·  memory freed',
  revertUsed: 'git revert HEAD~3s',
  revertEmpty: 'No revert left. Find a ↺ chip.',
  freed: (address: string) => `free(${address}) ✓`,
  breakpointBanner: 'Paused on breakpoint',
  sudoBanner: 'root@a0:~#',
  rewindBanner: 'git revert',
  keysRevert: 'git revert',
  powersIntro: 'Power-ups: ↺ git revert (R) · ⏸ Breakpoint · # sudo · ♻ Garbage Collector.',
  // debug gun and reactive bugs
  keysFire: 'fire',
  keysCrouch: 'crouch',
  keysAimUp: 'aim up',
  fireHint: 'Hold F to fire debug packets. They kill bugs and shoot down incoming bolts.',
  shotReady: 'LOG()',
  bugAlert: 'IT SAW YOU',
  // magnetic grapple
  keysGrapple: 'grapple',
  grappleHint: 'Hold E near a glowing node to latch on. W / S reel the cable, Space launches you.',
  grappleMiss: 'No node in range.',
  grappleLaunch: 'LAUNCH!',
  // DELETE wave chase
  purgeLabel: 'OVERHEAT',
  purgeWarning: 'SERVER OVERHEAT · RUN, a0, RUN!',
  purgeCleared: 'TRANSACTION ROLLED BACK  +400',
  purgeDeath: 'Deleted. No WHERE clause.',
  statScore: 'Score', statCombo: 'Best chain',
  livesLabel: 'LIVES',
  difficultyLabel: 'Difficulty',
  difficultyNames: { development: 'Development', testing: 'Testing', production: 'Production' },
  infiniteLives: 'Unlimited lives',
  infiniteRule: 'Unlimited lives. Hits still knock you back; falls return you to the checkpoint. No game over.',
  finiteRule: 'Lives cover the whole campaign. Each hit or fall costs one. Checkpoints do not refill them.',
  livesRule: 'Only three lives for the whole campaign. Each hit or fall costs one. At zero: game over. Checkpoints do not refill lives.',
  controlsTitle: 'Controls',
  goalTitle: 'The goal',
  goalBody: 'Grab the Hotfix, then reach the exit. Three environments: Buggy Dev Desk, Production Datacenter, Legacy Dimension.',
  nextLevel: 'Next environment', stageClear: 'Hotfix secured!',
  stageHints: ['Keys collapse! Space: double jump. X: dash. F: fire. Defeat NullPointer before the exit.', 'Fans lift you. Ride the racks, dodge flying bugs. CPU pressure slows scenery, never your controls. Escape the overheating server!', 'Learn GRAVITY / OFFLINE / CLONES. The boss combines them. In Panic Mode, shoot CORE, SESSION and SOAP before the final hit.'],
  // the Monolith rewrites one rule per phase, announced before it bites
  bossRule: '⚠ SYSTEM PATCH IN',
  bossCmd: { gravity: 'GRAVITY_OVERRIDE', clones: 'fork() → 3 clones', offline: 'systemctl stop platforms' },
  bossCmdHint: {
    gravity: '5 seconds upside down. Green zone: normal gravity. Shoot the glowing endpoints with F.',
    clones: 'Three clones charge. Shoot them with F or let them run past.',
    offline: 'The arena slabs drop one by one. Do not stand still.',
  },
  bossDefeated: 'LEGACY REFACTORED!', bossWarning: 'SOAP INCOMING / JUMP',
  bossName: 'LEGACY MONOLITH',
  bossQuote: '“Time to update the rules!”',
  bossTaunt: 'MORE SOAP FOR YOU!',
  bossNoteWorks: 'IT WORKS ON MY MACHINE',
  bossNoteTouch: 'DON’T TOUCH IT!',
  bossWallCode: 'SAME CODE SINCE 2006',
  bossWallLegacy: 'LEGACY NEVER DIES',
  bossOpen: 'CORE OPEN / JUMP ON TOP', bossLocked: 'CORE SHIELDED',
  dialogLabel: 'a0: Bug Hunt',
  brandSubtitle: '01 / LOCALHOST · FRIDAY DEPLOY',
  audioOn: 'Mute audio',
  audioOff: 'Unmute audio',
  gentle: 'Gentle effects',
  gentleTitle: 'Gentle effects: fewer particles, no screen shake',
  pause: 'Pause',
  resume: 'Resume',
  pauseTitle: 'Pause · Esc',
  backToApp: 'Back to adOmnia',
  canvasLabel: 'Bug Hunt: platforms, bits and bugs. Use A/D or the arrows to move and Space to jump.',
  hudLabel: 'Game status',
  healthLabel: (health: number, max = 3) => `${health} of ${max} lives`,
  hotfixFound: 'HOTFIX ✓',
  findHotfix: 'FIND THE HOTFIX',
  introEyebrow: 'Friday, 5:59 PM',
  winEyebrow: 'Pipeline green · Production is safe',
  pauseEyebrow: 'Deploy paused',
  introTitle: 'A tiny deploy.',
  introTitleAccent: 'A huge problem.',
  introQuote: '“It works on my machine.”',
  introBody: 'The bugs escaped from the terminals. You are a0: jump on them, grab the bits and save the weekend.',
  missionTitle: 'Recover the Hotfix. Light up the pipeline.',
  missionBody: 'There is a secret branch too, for anyone who can’t resist a detour.',
  start: 'Save the weekend',
  introTip: 'Space again in the air to recover a jump. X or Shift to dash, F to fire. E to grapple the nodes: swing, launch, shoot, repeat.',
  record: (time: string) => ` Your record: ${time}.`,
  winTitle: 'Build passed.',
  winTitleAccent: 'Breathe, a0.',
  winBody: 'Production is safe again. This time it really works.',
  statTime: 'Time',
  statBits: 'Bits collected',
  statDeaths: 'Deaths',
  medalRecord: 'New personal best',
  medalSecret: 'Secret branch found',
  medalBugs: 'Every ticket closed',
  winQuote: 'New ticket: “The button is slightly off.”',
  playAgain: 'One more run',
  backToWork: 'Back to work',
  pauseTitle1: 'The deploy',
  pauseTitle2: 'can wait.',
  pauseBodyCheckpoint: 'Your checkpoint is safe. Pick it up whenever you like.',
  pauseBody: 'Take a moment. a0 will wait right here.',
  restart: 'Restart campaign',
  exit: 'Exit',
  pauseTip: 'Esc to resume · Audio and effects live up top.',
  keysMove: 'move',
  keysJump: 'double jump',
  keysPause: 'pause',
  keySpace: 'Space',
  checkpointSaved: 'Checkpoint saved',
  findCheckpoint: 'Find the checkpoint',
  // canvas popups
  retry: 'New attempt. You’re close.',
  rollback: 'Rollback successful.',
  notAFeature: 'That wasn’t a feature.',
  secretFound: 'SECRET BRANCH!  git stash happiness',
  bits: (n: number) => `${n} BITS!`,
  hotfixPickup: 'HOTFIX FOUND  ·  Go deploy!',
  bugClosed: ['BUG CLOSED ✓', 'Ticket resolved. For real.', 'Last bug? Don’t say it.'],
  commitSaved: 'COMMIT SAVED ✓',
  missingHotfix: 'Missing the Hotfix! ←',
  // canvas signs
  signFriday: '5:59 PM  ·  FRIDAY',
  signFridayQuote: '“It’s just a small change.”',
  signBug: 'BUG IN PRODUCTION',
  signBugHint: 'Jump on it. Then close the ticket.',
  signCommit: 'GIT COMMIT',
  signCommitSaved: 'Checkpoint saved. Breathe.',
  signCommitHint: 'Respawn here, no fear.',
  signPush: 'LAST PUSH',
  signPushHint: 'The weekend is on the other side.',
  signSurprise: '↗  git checkout surprise',
  signSecret: '// SECRET BRANCH',
  gatePassed: 'BUILD PASSED',
  gateLocked: 'HOTFIX REQUIRED',
}

export type BugHuntCopy = typeof en

const it: BugHuntCopy = {
  nullLocked: 'Sconfiggi prima NullPointer! ←', cpuWarning: 'CPU 97% · scenario lento / comandi attivi',
  gravitySafe: 'GRAVITY SAFE ZONE ↓', lessonHint: 'Leggi l’avviso. Puoi sempre uscire dalla zona.',
  bossPhases: ['SOAP STORM', 'LEGACY OVERRIDE', 'MONOLITH PANIC MODE'],
  gameOverTitle: 'Vite esaurite.', gameOverBody: 'Hai esaurito le vite di questo deploy. Ricomincia la campagna e riprova.',
  rewindQuip: 'Sul mio PC funzionava.', checkpointQuip: 'Salvato. Respiriamo.', edgeQuip: 'Era tutto calcolato.',
  bossDoubleWave: 'DOPPIO SOAP / DOPPIO SALTO',
  rushStart: 'BONUS RUSH! 6 bit / 8 secondi', rushWon: 'RUSH COMPLETATA! +500',
  rushLabel: 'BONUS RUSH', rank: 'Grado', rushMedal: 'Sfide bonus',
  chainHint: 'Ogni bug colpito ricarica lo scatto. Rimbalza, scatta, ripeti!',
  dashReady: 'SCATTO PRONTO', dashCharging: 'SCATTO IN RICARICA', keysDash: 'scatto',
  powerRevert: '+1 git revert  ·  premi R',
  powerBreakpoint: 'BREAKPOINT  ·  mondo in pausa',
  powerSudo: 'sudo !!  ·  accesso root',
  powerGc: 'GARBAGE COLLECTOR  ·  memoria liberata',
  revertUsed: 'git revert HEAD~3s',
  revertEmpty: 'Nessun revert. Cerca un chip ↺.',
  freed: (address) => `free(${address}) ✓`,
  breakpointBanner: 'In pausa sul breakpoint',
  sudoBanner: 'root@a0:~#',
  rewindBanner: 'git revert',
  keysRevert: 'git revert',
  powersIntro: 'Poteri: ↺ git revert (R) · ⏸ Breakpoint · # sudo · ♻ Garbage Collector.',
  keysFire: 'spara',
  keysCrouch: 'abbassati',
  keysAimUp: 'mira in alto',
  fireHint: 'Tieni premuto F per sparare pacchetti di debug. Uccidono i bug e abbattono i colpi in arrivo.',
  shotReady: 'LOG()',
  bugAlert: 'TI HA VISTO',
  keysGrapple: 'rampino',
  grappleHint: 'Tieni E vicino a un nodo luminoso per agganciarti. W / S regolano il cavo, Spazio ti lancia.',
  grappleMiss: 'Nessun nodo a portata.',
  grappleLaunch: 'LANCIO!',
  purgeLabel: 'OVERHEAT',
  purgeWarning: 'SERVER OVERHEAT · CORRI, a0, CORRI!',
  purgeCleared: 'TRANSAZIONE ANNULLATA  +400',
  purgeDeath: 'Cancellato. Senza WHERE.',
  statScore: 'Punteggio', statCombo: 'Serie migliore',
  livesLabel: 'VITE',
  difficultyLabel: 'Difficoltà',
  difficultyNames: { development: 'Sviluppo', testing: 'Collaudo', production: 'Produzione' },
  infiniteLives: 'Vite infinite',
  infiniteRule: 'Vite infinite. I colpi ti respingono e le cadute ti riportano al checkpoint. Nessun game over.',
  finiteRule: 'Le vite valgono per tutta la campagna. Ogni colpo o caduta ne consuma una. I checkpoint non le ricaricano.',
  livesRule: 'Solo tre vite per tutta la campagna. Ogni colpo o caduta ne consuma una. A zero: game over. I checkpoint non ricaricano le vite.',
  controlsTitle: 'Comandi',
  goalTitle: 'Obiettivo',
  goalBody: 'Prendi l’Hotfix, poi raggiungi l’uscita. Tre ambienti: Buggy Dev Desk, Production Datacenter, Legacy Dimension.',
  nextLevel: 'Prossimo ambiente', stageClear: 'Hotfix al sicuro!',
  stageHints: ['I tasti cedono! Spazio: doppio salto. X: scatto. F: spara. Sconfiggi NullPointer prima di uscire.', 'Sali con ventole e ascensori. Schiva i bug volanti. La CPU rallenta lo scenario, mai i comandi. Fuggi dal server surriscaldato!', 'Impara GRAVITY / OFFLINE / CLONES. Il boss li combina. In Panic Mode spara a CORE, SESSION e SOAP prima del colpo finale.'],
  bossRule: '⚠ PATCH DI SISTEMA TRA',
  bossCmd: { gravity: 'GRAVITY_OVERRIDE', clones: 'fork() → 3 cloni', offline: 'systemctl stop piattaforme' },
  bossCmdHint: {
    gravity: '5 secondi a testa in giù. Zona verde: gravità normale. F sugli endpoint luminosi.',
    clones: 'Tre cloni ti caricano. Sparagli con F o falli sfilare.',
    offline: 'Le piattaforme dell’arena cadono a turno. Non restare fermo.',
  },
  bossDefeated: 'LEGACY REFACTORED!', bossWarning: 'SOAP IN ARRIVO / SALTA',
  bossName: 'LEGACY MONOLITH',
  bossQuote: '«È ora di aggiornare le regole!»',
  bossTaunt: 'ALTRO SOAP PER TE!',
  bossNoteWorks: 'FUNZIONA SUL MIO PC',
  bossNoteTouch: 'NON TOCCARLO!',
  bossWallCode: 'STESSO CODICE DAL 2006',
  bossWallLegacy: 'IL LEGACY NON MUORE MAI',
  bossOpen: 'NUCLEO APERTO / SALTACI SOPRA', bossLocked: 'NUCLEO PROTETTO',
  dialogLabel: 'a0: Bug Hunt',
  brandSubtitle: '01 / LOCALHOST · DEPLOY DEL VENERDÌ',
  audioOn: 'Disattiva audio',
  audioOff: 'Attiva audio',
  gentle: 'Effetti delicati',
  gentleTitle: 'Effetti delicati: meno particelle, niente scuotimenti',
  pause: 'Pausa',
  resume: 'Riprendi',
  pauseTitle: 'Pausa · Esc',
  backToApp: 'Torna ad adOmnia',
  canvasLabel: 'Bug Hunt: piattaforme, bit e bug. Usa A/D o le frecce per muoverti e Spazio per saltare.',
  hudLabel: 'Stato partita',
  healthLabel: (health, max = 3) => `${health} vite su ${max}`,
  hotfixFound: 'HOTFIX ✓',
  findHotfix: 'TROVA L’HOTFIX',
  introEyebrow: 'Venerdì, ore 17:59',
  winEyebrow: 'Pipeline verde · Production al sicuro',
  pauseEyebrow: 'Deploy in pausa',
  introTitle: 'Un piccolo deploy.',
  introTitleAccent: 'Un grosso problema.',
  introQuote: '«Sul mio computer funzionava.»',
  introBody: 'I bug sono scappati dai terminali. Tu sei a0: saltaci sopra, raccogli i bit e salva il weekend.',
  missionTitle: 'Recupera l’Hotfix. Accendi la pipeline.',
  missionBody: 'C’è anche un ramo segreto, per chi non sa resistere a una deviazione.',
  start: 'Salviamo il weekend',
  introTip: 'Premi ancora Spazio in aria per recuperare un salto. X o Shift per scattare, F per sparare. E per il rampino: oscilla, lanciati, spara, ripeti.',
  record: (time) => ` Il tuo record: ${time}.`,
  winTitle: 'Build passed.',
  winTitleAccent: 'Respira, a0.',
  winBody: 'Production è di nuovo al sicuro. Stavolta funziona davvero.',
  statTime: 'Tempo',
  statBits: 'Bit raccolti',
  statDeaths: 'Morti',
  medalRecord: 'Nuovo record personale',
  medalSecret: 'Ramo segreto trovato',
  medalBugs: 'Tutti i ticket chiusi',
  winQuote: 'Nuovo ticket: «Il pulsante è leggermente spostato.»',
  playAgain: 'Un’altra partita',
  backToWork: 'Torna al lavoro',
  pauseTitle1: 'Il deploy',
  pauseTitle2: 'può aspettare.',
  pauseBodyCheckpoint: 'Il checkpoint è al sicuro. Riparti quando vuoi.',
  pauseBody: 'Prenditi un momento. a0 ti aspetta qui.',
  restart: 'Ricomincia campagna',
  exit: 'Esci',
  pauseTip: 'Esc per riprendere · Audio ed effetti si regolano in alto.',
  keysMove: 'muovi',
  keysJump: 'doppio salto',
  keysPause: 'pausa',
  keySpace: 'Spazio',
  checkpointSaved: 'Checkpoint salvato',
  findCheckpoint: 'Trova il checkpoint',
  retry: 'Nuovo tentativo. Ci sei quasi.',
  rollback: 'Rollback riuscito.',
  notAFeature: 'Non era una feature.',
  secretFound: 'RAMO SEGRETO!  git stash felicità',
  bits: (n) => `${n} BIT!`,
  hotfixPickup: 'HOTFIX TROVATO  ·  Vai al deploy!',
  bugClosed: ['BUG CHIUSO ✓', 'Ticket risolto. Per davvero.', 'Ultimo bug? Non dirlo.'],
  commitSaved: 'COMMIT SALVATO ✓',
  missingHotfix: 'Manca l’Hotfix! ←',
  signFriday: '17:59  ·  VENERDÌ',
  signFridayQuote: '«È solo una piccola modifica.»',
  signBug: 'BUG IN PRODUZIONE',
  signBugHint: 'Saltaci sopra. Poi chiudi il ticket.',
  signCommit: 'GIT COMMIT',
  signCommitSaved: 'Checkpoint salvato. Respira.',
  signCommitHint: 'Qui puoi ripartire senza paura.',
  signPush: 'ULTIMO PUSH',
  signPushHint: 'Il weekend è dall’altra parte.',
  signSurprise: '↗  git checkout sorpresa',
  signSecret: '// RAMO SEGRETO',
  gatePassed: 'BUILD PASSED',
  gateLocked: 'HOTFIX RICHIESTO',
}

export const BUG_HUNT_COPY: Record<Lang, BugHuntCopy> = { en, it }
