// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApiBySlug(arg1) {
  return window['go']['main']['ApiCollectionStore']['GetApiBySlug'](arg1);
}

export function GetCatalog() {
  return window['go']['main']['ApiCollectionStore']['GetCatalog']();
}

export function GetCatalogFromPath(arg1) {
  return window['go']['main']['ApiCollectionStore']['GetCatalogFromPath'](arg1);
}

export function SearchApis(arg1) {
  return window['go']['main']['ApiCollectionStore']['SearchApis'](arg1);
}

export function SetCollectionsDir(arg1) {
  return window['go']['main']['ApiCollectionStore']['SetCollectionsDir'](arg1);
}

export function SetEmbeddedFS(arg1) {
  return window['go']['main']['ApiCollectionStore']['SetEmbeddedFS'](arg1);
}
