// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetApiBySlug(arg1, arg2) {
  return window['go']['main']['ApiCollectionStore']['GetApiBySlug'](arg1, arg2);
}

export function GetCatalog(arg1) {
  return window['go']['main']['ApiCollectionStore']['GetCatalog'](arg1);
}

export function GetCatalogFromPath(arg1, arg2) {
  return window['go']['main']['ApiCollectionStore']['GetCatalogFromPath'](arg1, arg2);
}

export function SearchApis(arg1, arg2) {
  return window['go']['main']['ApiCollectionStore']['SearchApis'](arg1, arg2);
}

export function SetCollectionsDir(arg1) {
  return window['go']['main']['ApiCollectionStore']['SetCollectionsDir'](arg1);
}
