// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDevLogs() {
  return window['go']['main']['App']['ClearDevLogs']();
}

export function CompareFolders(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareFolders'](arg1, arg2, arg3);
}

export function CreateMarkdownFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateMarkdownFile'](arg1, arg2, arg3);
}

export function DeleteMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteMarkdownFile'](arg1, arg2);
}

export function ExecuteHTTP(arg1) {
  return window['go']['main']['App']['ExecuteHTTP'](arg1);
}

export function GetDevLogs() {
  return window['go']['main']['App']['GetDevLogs']();
}

export function GetServerPort() {
  return window['go']['main']['App']['GetServerPort']();
}

export function GetSidecarToken() {
  return window['go']['main']['App']['GetSidecarToken']();
}

export function GetStartupWindowChrome() {
  return window['go']['main']['App']['GetStartupWindowChrome']();
}

export function GetVaultTimeout() {
  return window['go']['main']['App']['GetVaultTimeout']();
}

export function ImportMarkdownFolderToWorkspace(arg1) {
  return window['go']['main']['App']['ImportMarkdownFolderToWorkspace'](arg1);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function ListLogFiles() {
  return window['go']['main']['App']['ListLogFiles']();
}

export function ListMarkdownFiles(arg1) {
  return window['go']['main']['App']['ListMarkdownFiles'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenDevLogsFolder() {
  return window['go']['main']['App']['OpenDevLogsFolder']();
}

export function ReadFolderDiffFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFolderDiffFile'](arg1, arg2, arg3);
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function ReadMarkdownFile(arg1) {
  return window['go']['main']['App']['ReadMarkdownFile'](arg1);
}

export function RecordFrontendLog(arg1, arg2) {
  return window['go']['main']['App']['RecordFrontendLog'](arg1, arg2);
}

export function RenameMarkdownFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameMarkdownFile'](arg1, arg2, arg3);
}

export function SaveMarkdownFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveMarkdownFileAs'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveBinaryFileBase64(arg1, arg2) {
  return window['go']['main']['App']['SaveBinaryFileBase64'](arg1, arg2);
}

export function SignPdfDocumentBase64(arg1) {
  return window['go']['main']['App']['SignPdfDocumentBase64'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetDevMode(arg1) {
  return window['go']['main']['App']['SetDevMode'](arg1);
}

export function SetVaultTimeout(arg1) {
  return window['go']['main']['App']['SetVaultTimeout'](arg1);
}

export function StorageDelete(arg1, arg2) {
  return window['go']['main']['App']['StorageDelete'](arg1, arg2);
}

export function StorageGet(arg1, arg2) {
  return window['go']['main']['App']['StorageGet'](arg1, arg2);
}

export function StorageGetAll(arg1) {
  return window['go']['main']['App']['StorageGetAll'](arg1);
}

export function StorageList(arg1, arg2) {
  return window['go']['main']['App']['StorageList'](arg1, arg2);
}

export function StoragePut(arg1, arg2, arg3) {
  return window['go']['main']['App']['StoragePut'](arg1, arg2, arg3);
}

export function VerifyPdfSignatureBase64(arg1) {
  return window['go']['main']['App']['VerifyPdfSignatureBase64'](arg1);
}

export function InspectSigningCertificateBase64(arg1) {
  return window['go']['main']['App']['InspectSigningCertificateBase64'](arg1);
}

export function WriteMarkdownAgentGraph(arg1, arg2) {
  return window['go']['main']['App']['WriteMarkdownAgentGraph'](arg1, arg2);
}

export function WriteMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['WriteMarkdownFile'](arg1, arg2);
}
