// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {browser} from '../models';

export function ClearConsoleLogs():Promise<void>;

export function ClearDeviceEmulation():Promise<void>;

export function ClearThrottling():Promise<void>;

export function ClearTraffic():Promise<void>;

export function Connect():Promise<void>;

export function ConnectToTarget(arg1:string):Promise<void>;

export function ConnectToTargetByID(arg1:number,arg2:string):Promise<void>;

export function DeleteCookie(arg1:string,arg2:string):Promise<void>;

export function DisableDebugger():Promise<void>;

export function Disconnect():Promise<void>;

export function DiscoverEndpoints():Promise<Array<browser.DebugEndpoint>>;

export function EmulateDevice(arg1:number,arg2:number,arg3:boolean,arg4:number):Promise<void>;

export function EnableConsole():Promise<void>;

export function EnableDOM():Promise<void>;

export function EnableDebugger():Promise<void>;

export function EnableDebuggingOnBrowser(arg1:number):Promise<void>;

export function EvalJS(arg1:string):Promise<browser.ConsoleEntry>;

export function GetBreakpoints():Promise<Array<browser.BreakpointInfo>>;

export function GetComputedStyle(arg1:number):Promise<Record<string, string>>;

export function GetConsoleLogs():Promise<Array<browser.ConsoleEntry>>;

export function GetCookies():Promise<Array<browser.CookieEntry>>;

export function GetDOMBreakpoints():Promise<Array<browser.DOMBreakpointInfo>>;

export function GetDebugStatus():Promise<browser.DebugStatus>;

export function GetDocument(arg1:number):Promise<browser.DOMNode>;

export function GetIndexedDBDatabases():Promise<Array<string>>;

export function GetLocalStorage():Promise<Array<browser.StorageItem>>;

export function GetNodeHTML(arg1:number):Promise<string>;

export function GetPageSource():Promise<string>;

export function GetPausedState():Promise<browser.PausedState>;

export function GetPerformanceMetrics():Promise<Record<string, number>>;

export function GetRequestBody(arg1:string):Promise<string>;

export function GetResponseBody(arg1:string):Promise<string>;

export function GetScriptSource(arg1:string):Promise<string>;

export function GetScripts():Promise<Array<browser.ScriptInfo>>;

export function GetSessionStorage():Promise<Array<browser.StorageItem>>;

export function GetSourceFileContent(arg1:string):Promise<string>;

export function GetSourceFiles():Promise<Array<browser.SourceFileInfo>>;

export function GetTargetInfo():Promise<Record<string, any>>;

export function GetThrottleProfiles():Promise<Array<browser.ThrottleProfile>>;

export function GetTraffic():Promise<Array<browser.DebugNetworkEntry>>;

export function GetTrafficFiltered(arg1:string):Promise<Array<browser.DebugNetworkEntry>>;

export function HandleConsoleEvent(arg1:Record<string, any>):Promise<void>;

export function HandleDebuggerEvent(arg1:string,arg2:Record<string, any>):Promise<void>;

export function HideHighlight():Promise<void>;

export function HighlightNode(arg1:number):Promise<void>;

export function IsConnected():Promise<boolean>;

export function LaunchBrowser(arg1:string):Promise<void>;

export function LaunchBrowserForDebug(arg1:string,arg2:number):Promise<Array<browser.DebugTarget>>;

export function ListTargets(arg1:number):Promise<Array<browser.DebugTarget>>;

export function NavigateTarget(arg1:string):Promise<void>;

export function QuerySelector(arg1:string):Promise<browser.DOMNode>;

export function ReloadPageNoCache():Promise<void>;

export function RemoveBreakpoint(arg1:string):Promise<void>;

export function RemoveDOMBreakpoint(arg1:number,arg2:string):Promise<void>;

export function Resume():Promise<void>;

export function SetBreakpoint(arg1:string,arg2:number,arg3:string):Promise<string>;

export function SetBreakpointByScriptID(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function SetDOMBreakpoint(arg1:number,arg2:string):Promise<void>;

export function SetThrottling(arg1:number,arg2:number,arg3:number):Promise<void>;

export function StepInto():Promise<void>;

export function StepOut():Promise<void>;

export function StepOver():Promise<void>;

export function StopBrowser():Promise<void>;

export function TakeScreenshot(arg1:string,arg2:number):Promise<string>;