// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCollectionToFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportRequestToFolder(arg1:string,arg2:string):Promise<string>;

export function ImportCollectionFromFolder(arg1:string):Promise<string>;

export function InspectCollectionFolder(arg1:string,arg2:string):Promise<string>;
