// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docker} from '../models';

export function GenerateLab(arg1:Array<string>):Promise<docker.LabOutput>;

export function GetPresets():Promise<Array<docker.PresetDef>>;

export function LabDown(arg1:string):Promise<string>;

export function LabList():Promise<Array<docker.LabInfo>>;

export function LabLogs(arg1:string,arg2:number):Promise<string>;

export function LabStatus(arg1:string):Promise<Array<docker.ContainerStatus>>;

export function LabUp(arg1:Array<string>):Promise<docker.LabRunResult>;
