// @ts-check
// This file is automatically generated. DO NOT EDIT

export function GenerateLab(arg1) {
  return window['go']['main']['DockerLab']['GenerateLab'](arg1);
}

export function GetPresets() {
  return window['go']['main']['DockerLab']['GetPresets']();
}

export function LabDown(arg1) {
  return window['go']['main']['DockerLab']['LabDown'](arg1);
}

export function LabList() {
  return window['go']['main']['DockerLab']['LabList']();
}

export function LabLogs(arg1, arg2) {
  return window['go']['main']['DockerLab']['LabLogs'](arg1, arg2);
}

export function LabStatus(arg1) {
  return window['go']['main']['DockerLab']['LabStatus'](arg1);
}

export function LabUp(arg1) {
  return window['go']['main']['DockerLab']['LabUp'](arg1);
}
