// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function AbortIntegration(arg1:string):Promise<void>;

export function AbortOperation(arg1:string):Promise<string>;

export function AddIgnorePattern(arg1:string,arg2:string):Promise<void>;

export function AddRemote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddSubmodule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddWorktree(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function AmendCommit(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function ApplyHunk(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ApplyPatch(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<string>;

export function BisectMark(arg1:string,arg2:string):Promise<string>;

export function BisectReset(arg1:string):Promise<string>;

export function BisectRun(arg1:string,arg2:string):Promise<string>;

export function BisectStart(arg1:string,arg2:string,arg3:string):Promise<string>;

export function BlameFile(arg1:string,arg2:string):Promise<string>;

export function BlameLines(arg1:string,arg2:string):Promise<string>;

export function ChangesDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckoutBranch(arg1:string,arg2:string):Promise<void>;

export function CheckoutCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckoutConflictSide(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckoutRemoteBranch(arg1:string,arg2:string):Promise<void>;

export function CherryPick(arg1:string,arg2:Array<string>,arg3:boolean,arg4:string,arg5:boolean):Promise<string>;

export function Clone(arg1:string,arg2:string):Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<string>;

export function CommitAll(arg1:string,arg2:string):Promise<string>;

export function CommitPaths(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function CompareCommits(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CompareRefs(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CompareWebURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ConfigureUser(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ContinueOperation(arg1:string):Promise<string>;

export function CreateAndCheckoutBranch(arg1:string,arg2:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function CreateBranchFromCommit(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<string>;

export function CreatePatch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateTagFromCommit(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean):Promise<string>;

export function DeleteLocalBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteRemoteBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTag(arg1:string,arg2:string):Promise<void>;

export function DisableSparseCheckout(arg1:string):Promise<void>;

export function ExtractHeadToNewBranch(arg1:string,arg2:string):Promise<string>;

export function Fetch(arg1:string):Promise<void>;

export function FileAtCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FileDiff(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function FileHistory(arg1:string,arg2:string,arg3:number):Promise<string>;

export function ForcePush(arg1:string,arg2:string):Promise<string>;

export function GenerateRevertMessage(arg1:string,arg2:string):Promise<string>;

export function GetCommitMeta(arg1:string,arg2:string):Promise<string>;

export function GetConflictFileVersions(arg1:string,arg2:string):Promise<string>;

export function GetFileDiff(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetRebaseTodo(arg1:string,arg2:string):Promise<string>;

export function GetRepoState(arg1:string):Promise<string>;

export function GetStatus(arg1:string):Promise<string>;

export function GetWorkingTreeFileSnapshot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitHubCreatePR(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<git.PullRequest>;

export function GitHubListPRs(arg1:string,arg2:string):Promise<Array<git.PullRequest>>;

export function GitHubValidateToken(arg1:string):Promise<string>;

export function HostCreatePR(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<git.PullRequest>;

export function HostListPRs(arg1:string,arg2:string,arg3:string):Promise<Array<git.PullRequest>>;

export function HostPush(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function HostValidateToken(arg1:string,arg2:string,arg3:string):Promise<string>;

export function InitRepo(arg1:string):Promise<void>;

export function IsGitInstalled():Promise<boolean>;

export function ListSubmodules(arg1:string):Promise<string>;

export function ListWorktrees(arg1:string):Promise<string>;

export function Log(arg1:string,arg2:number):Promise<string>;

export function MergeBranch(arg1:string,arg2:string):Promise<void>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Overview(arg1:string,arg2:number):Promise<string>;

export function Pull(arg1:string,arg2:string):Promise<void>;

export function Push(arg1:string,arg2:string):Promise<void>;

export function RebaseBranch(arg1:string,arg2:string):Promise<void>;

export function RebaseOnto(arg1:string,arg2:string):Promise<string>;

export function Reflog(arg1:string,arg2:number):Promise<string>;

export function RemoteWebURL(arg1:string):Promise<string>;

export function RemoveFile(arg1:string,arg2:string):Promise<void>;

export function RemoveRemote(arg1:string,arg2:string):Promise<void>;

export function RemoveSubmodule(arg1:string,arg2:string):Promise<void>;

export function RemoveWorktree(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ResetBranch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ResetHard(arg1:string,arg2:string):Promise<void>;

export function RestoreFile(arg1:string,arg2:string):Promise<void>;

export function RestoreFileFromCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RevertCommit(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function RunTerminalCommand(arg1:string,arg2:string):Promise<string>;

export function SaveConflictResolution(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchHistory(arg1:string,arg2:string):Promise<string>;

export function SetSparseCheckout(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SetUpstream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Show(arg1:string,arg2:string):Promise<string>;

export function SkipOperation(arg1:string):Promise<string>;

export function SparseCheckoutList(arg1:string):Promise<string>;

export function SquashHeadIntoPrevious(arg1:string):Promise<string>;

export function StageAll(arg1:string):Promise<void>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function StartInteractiveRebase(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Stash(arg1:string):Promise<void>;

export function StashApply(arg1:string,arg2:string):Promise<void>;

export function StashDrop(arg1:string,arg2:string):Promise<void>;

export function StashPaths(arg1:string,arg2:Array<string>):Promise<void>;

export function StashPop(arg1:string):Promise<void>;

export function StashShow(arg1:string,arg2:string):Promise<string>;

export function UndoLastCommit(arg1:string,arg2:boolean):Promise<string>;

export function UndoToReflog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UnstageAll(arg1:string):Promise<void>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;

export function UpdateSubmodules(arg1:string,arg2:string):Promise<void>;
