// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitAll(arg1:string,arg2:string):Promise<string>;

export function GetStatus(arg1:string):Promise<string>;

export function InitRepo(arg1:string):Promise<void>;

export function IsGitInstalled():Promise<boolean>;

export function Log(arg1:string,arg2:number):Promise<string>;

export function Pull(arg1:string,arg2:string):Promise<void>;

export function Push(arg1:string,arg2:string):Promise<void>;
