// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortIntegration(arg1) {
  return window['go']['main']['GitSync']['AbortIntegration'](arg1);
}

export function CheckoutConflictSide(arg1, arg2, arg3) {
  return window['go']['main']['GitSync']['CheckoutConflictSide'](arg1, arg2, arg3);
}

export function CommitAll(arg1, arg2) {
  return window['go']['main']['GitSync']['CommitAll'](arg1, arg2);
}

export function GetStatus(arg1) {
  return window['go']['main']['GitSync']['GetStatus'](arg1);
}

export function InitRepo(arg1) {
  return window['go']['main']['GitSync']['InitRepo'](arg1);
}

export function IsGitInstalled() {
  return window['go']['main']['GitSync']['IsGitInstalled']();
}

export function Log(arg1, arg2) {
  return window['go']['main']['GitSync']['Log'](arg1, arg2);
}

export function Overview(arg1, arg2) {
  return window['go']['main']['GitSync']['Overview'](arg1, arg2);
}

export function Pull(arg1, arg2) {
  return window['go']['main']['GitSync']['Pull'](arg1, arg2);
}

export function Push(arg1, arg2) {
  return window['go']['main']['GitSync']['Push'](arg1, arg2);
}

export function StageFile(arg1, arg2) {
  return window['go']['main']['GitSync']['StageFile'](arg1, arg2);
}
