// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DisablePlugin(arg1:string):Promise<void>;

export function EmitEvent(arg1:main.PluginEvent):Promise<Array<main.HookResult>>;

export function EnablePlugin(arg1:string):Promise<void>;

export function FireEvent(arg1:main.PluginEvent):Promise<boolean>;

export function GetAvailableEvents():Promise<Array<string>>;

export function GetPlugin(arg1:string):Promise<main.PluginInstance>;

export function GetPluginSettings(arg1:string):Promise<Record<string, string>>;

export function GetPlugins():Promise<Array<main.PluginInstance>>;

export function GetPythonRuntimeStatus():Promise<main.RuntimeStatus>;

export function GetRegisteredHooks():Promise<Record<string, Array<string>>>;

export function Init():Promise<void>;

export function InstallPlugin(arg1:string):Promise<main.PluginInstance>;

export function InstallPluginPackage(arg1:string,arg2:Record<string, string>):Promise<main.PluginInstance>;

export function InstallPythonPlugin(arg1:string):Promise<void>;

export function LoadPluginState():Promise<void>;

export function SavePluginState():Promise<void>;

export function SetPluginSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Shutdown():Promise<void>;

export function UninstallPlugin(arg1:string):Promise<void>;
