// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckContrast(arg1) {
  return window['go']['main']['ThemeManager']['CheckContrast'](arg1);
}

export function DeleteTheme(arg1) {
  return window['go']['main']['ThemeManager']['DeleteTheme'](arg1);
}

export function ExportTheme(arg1) {
  return window['go']['main']['ThemeManager']['ExportTheme'](arg1);
}

export function GetActiveThemeID() {
  return window['go']['main']['ThemeManager']['GetActiveThemeID']();
}

export function GetBuiltinThemes() {
  return window['go']['main']['ThemeManager']['GetBuiltinThemes']();
}

export function GetChangedSkins() {
  return window['go']['main']['ThemeManager']['GetChangedSkins']();
}

export function GetExtendedBuiltinThemes() {
  return window['go']['main']['ThemeManager']['GetExtendedBuiltinThemes']();
}

export function GetSkinsDirectory() {
  return window['go']['main']['ThemeManager']['GetSkinsDirectory']();
}

export function GetTheme(arg1) {
  return window['go']['main']['ThemeManager']['GetTheme'](arg1);
}

export function GetThemes() {
  return window['go']['main']['ThemeManager']['GetThemes']();
}

export function GetTokenNamespace() {
  return window['go']['main']['ThemeManager']['GetTokenNamespace']();
}

export function ImportSkinFromURL(arg1) {
  return window['go']['main']['ThemeManager']['ImportSkinFromURL'](arg1);
}

export function ImportTheme(arg1) {
  return window['go']['main']['ThemeManager']['ImportTheme'](arg1);
}

export function ImportThemeFile(arg1) {
  return window['go']['main']['ThemeManager']['ImportThemeFile'](arg1);
}

export function IsWatching() {
  return window['go']['main']['ThemeManager']['IsWatching']();
}

export function SaveSkinToDirectory(arg1) {
  return window['go']['main']['ThemeManager']['SaveSkinToDirectory'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['ThemeManager']['SaveTheme'](arg1);
}

export function ScanProjectThemesDirectory() {
  return window['go']['main']['ThemeManager']['ScanProjectThemesDirectory']();
}

export function ScanSkinsDirectory() {
  return window['go']['main']['ThemeManager']['ScanSkinsDirectory']();
}

export function SetActiveThemeID(arg1) {
  return window['go']['main']['ThemeManager']['SetActiveThemeID'](arg1);
}

export function StartWatching() {
  return window['go']['main']['ThemeManager']['StartWatching']();
}

export function StopWatching() {
  return window['go']['main']['ThemeManager']['StopWatching']();
}

export function ValidateTheme(arg1) {
  return window['go']['main']['ThemeManager']['ValidateTheme'](arg1);
}
