// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {themes} from '../models';

export function CheckContrast(arg1:themes.Theme):Promise<Array<themes.ContrastResult>>;

export function DeleteTheme(arg1:string):Promise<void>;

export function ExportTheme(arg1:string):Promise<string>;

export function GetActiveThemeID():Promise<string>;

export function GetBuiltinThemes():Promise<Array<themes.Theme>>;

export function GetChangedSkins():Promise<Array<string>>;

export function GetExtendedBuiltinThemes():Promise<Array<themes.Theme>>;

export function GetSkinsDirectory():Promise<string>;

export function GetTheme(arg1:string):Promise<themes.Theme>;

export function GetThemes():Promise<Array<themes.Theme>>;

export function GetTokenNamespace():Promise<Record<string, Array<themes.TokenDefinition>>>;

export function ImportSkinFromURL(arg1:string):Promise<themes.Theme>;

export function ImportTheme(arg1:string):Promise<themes.Theme>;

export function ImportThemeFile(arg1:string):Promise<themes.Theme>;

export function IsWatching():Promise<boolean>;

export function SaveSkinToDirectory(arg1:themes.Theme):Promise<string>;

export function SaveTheme(arg1:themes.Theme):Promise<void>;

export function ScanProjectThemesDirectory():Promise<Array<themes.Theme>>;

export function ScanSkinsDirectory():Promise<Array<themes.Theme>>;

export function SetActiveThemeID(arg1:string):Promise<void>;

export function StartWatching():Promise<void>;

export function StopWatching():Promise<void>;

export function ValidateTheme(arg1:themes.Theme):Promise<themes.ThemeValidationResult>;